### ISSUE TITLE
Top left corner missing 

### ISSUE THREAD

**Issue by cvanelteren** [kovidgoyal/kitty#1533] opened 2019-04-11 13:38 UTC
Hi,

I am wondering whether this a kitty related issue. The top left corner of my termial is missing input. See the attatched picture. Is this related to  a kitty setting I am missing?
![image](https://user-images.githubusercontent.com/19485143/55961742-d1a6b700-5c6f-11e9-95d9-53b4053983f9.png)

**Comment by Luflosi** [comment] 2019-04-11 13:39
This is probably a duplicate of #1484.

**Comment by cvanelteren** [comment] 2019-04-11 14:16
Thanks for the comment. Unfortunately, the fix does not work for me.  It causes my graphics driver to not be recongized for some reason yielding kitty to not start at all. I will have a look at this later.

**Comment by kovidgoyal** [comment] 2019-04-11 14:41
This is a dup of #1484

**Closed by kovidgoyal** 2019-04-11 14:41 UTC
