### ISSUE TITLE
macOS split fullscreen breaks Kitty windowing

### ISSUE THREAD

**Issue by albingroen** [kovidgoyal/kitty#3747] opened 2021-06-19 09:00 UTC
**Describe the bug**
After entering full screen split mode with Kitty and some other application in macOS, and then exit out of it, macOS still seems to think Kitty is in full-screen mode. This makes managing Kitty with something like Amethyst or Magnet not work. You can also not move the window to another desktop, since macOS still thinks is full screen.

**To Reproduce**
1. Open Kitty in full-screen split mode with some other application 
2. Exit fullscreen split mode
3. Try moving the window to another desktop
4. See it not working

**Environment details**
```
kitty 0.21.1 created by Kovid Goyal
Darwin MacBook-Pro-3.lan 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.4 BuildVersion:	20F71
Loaded config files:
  /Users/albin/.config/kitty/kitty.conf

Config options different from defaults:
active_border_color     Color(red=54, green=54, blue=54)
active_tab_background   Color(red=85, green=85, blue=85)
active_tab_foreground   Color(red=255, green=255, blue=255)
background              Color(red=40, green=40, blue=40)
cursor                  Color(red=146, green=131, blue=116)
enabled_layouts         ['tall', 'fat', 'grid', 'horizontal', 'vertical', 'stack']
font_size               18.0
foreground              Color(red=251, green=241, blue=199)
inactive_border_color   Color(red=54, green=54, blue=54)
inactive_tab_background Color(red=40, green=40, blue=40)
inactive_tab_foreground Color(red=85, green=85, blue=85)
selection_background    Color(red=235, green=219, blue=178)
selection_foreground    Color(red=146, green=131, blue=116)
Added shortcuts:
	cmd+f KeyAction('launch', ('--type=overlay', '--stdin-source=@screen_scrollback', '/usr/local/bin/fzf', '--no-sort', '--no-mouse', '--exact', '-i'))
	alt+cmd+h KeyAction('resize_window', ('wider', 3))
	alt+cmd+j KeyAction('resize_window', ('shorter', 3))
	alt+cmd+k KeyAction('resize_window', ('taller', 3))
	alt+cmd+l KeyAction('resize_window', ('narrower', 3))
	alt+cmd+left KeyAction('neighboring_window', ('left',))
	alt+cmd+right KeyAction('neighboring_window', ('right',))
	alt+cmd+up KeyAction('neighboring_window', ('top',))
	alt+cmd+down KeyAction('neighboring_window', ('bottom',))
Changed shortcuts:
	cmd+t KeyAction('new_tab_with_cwd')
	cmd+enter KeyAction('new_window_with_cwd')

```

**Additional context**
Once you get Kitty into this state, it seems nearly impossible to get out of it. I've tried:

- Restarting Kitty
- Running Kitty `--config NONE`
- Reinstalling Kitty
- Restarting macOS
- Running `killall Dock`

And nothing helped. macOS still thinks it's a fullscreen window, even though it isn't.

**Comment by Luflosi** [comment] 2021-06-19 13:52
I could not reproduce your problem on macOS 10.15 Catalina. I might try it on Big Sur later.

**Comment by albingroen** [comment] 2021-06-19 14:43
I'm running on Big Sur 11.4. I've been trying to solve this all day long and it's starting to drive me crazy...

**Comment by Luflosi** [comment] 2021-06-22 22:48
I was not able to reproduce your problem on macOS 11.4. Can you please create a video where you show exactly what you're doing? Maybe I followed your steps to reproduce the behaviour differently than you intended. Here is exactly hat I did:

1. Open Sublime Text
2. Open kitty
3. Hover over the green fullscreen icon of kitty
4. Click "move to the left side of the screen" (roughly translated from german)
5. Click the Sublime Text window on the right
6. Activate Mission Control
7. Drag the virtual desktop with both windows down to exit fullscreen split mode
8. Deactivate Mission Control
9. Drag the kitty window to the very right of the screen, until it moves to another virtual desktop

**Comment by albingroen** [comment] 2021-06-23 08:03
Yeah no, that isn't really what I meant, but now it's actually working again, so I don't really want to go into that state again, to be honest.

But here are the steps again to reproduce:

1. Open Kitty and another app in macOS split fullscreen mode
2. When in this mode, click the green button of the non-Kitty application.
3. Now Kitty should be in fullscreen mode, and the other one shouldn't
4. Now in my case, I couldn't even access the Kitty window. Each time I would "tab" to that window, it would just shoot me back to the desktop I came from. So, what I would have to do is to find the Kitty icon in the macOS dock, and quit it from there. Then when I opened it again and tried to move it to another desktop, macOS just wouldn't let me, since it still thought it was a fullscreen window.

I hope that's more detailed.

**Comment by Luflosi** [comment] 2021-06-24 15:21
With these new steps, I still can't reproduce your problem. After clicking the green button of the non-kitty application, <kbd>cmd</kbd>+<kbd>tab</kbd> switches to the fullscreen kitty window for me as expected.

**Comment by albingroen** [comment] 2021-06-25 14:58
Okay, maybe it's got something to do with the wm I'm using, which is Alacritty

**Comment by kovidgoyal** [comment] 2021-06-25 15:03
I also cannot replicate, closing

**Closed by kovidgoyal** 2021-06-25 15:03 UTC
Labels: bug
