### ISSUE TITLE
ctrl+shift+equal does not trigger any event (works in glfw events test)

### ISSUE THREAD

**Issue by gustafj** [kovidgoyal/kitty#488] opened 2018-04-23 18:50 UTC
The `ctrl+shift+equal` and `ctrl+shift+minus` mapping does not trigger any event for me.
I have tried the default config & mapping (font size inc / dec) along with custom settings, e.g `shift+control+equal KeyAction(func='send_text', args=['normal', 'equal'])` & `shift+control+minus KeyAction(func='send_text', args=['normal', 'minus'])`.
Other `ctrl+shift+<key>` mappings work, e.g. `ctrl+shift+backspace`.

The event test from GLFW is successfull, see output below, thus an event is recognized in GLFL.

Any specific debugging I can do?

```
Library initialized
Creating windowed mode window 1 (640x480)
Error: Wayland: Focusing a window requires user interaction
Main loop starting
...
00000007 to 1 at 6,829: Key 0x0155 Scancode 0x001d (LEFT CONTROL) (with no mods) was pressed
00000008 to 1 at 8,623: Key 0x0154 Scancode 0x002a (LEFT SHIFT) (with control) was pressed
```
**```00000009 to 1 at 10,076: Key 0x003d Scancode 0x000d (EQUAL) (with shift control) was pressed```**
```
0000000a to 1 at 10,076: Character 0x0000002b (+) with modifiers (with shift control) input
0000000b to 1 at 10,140: Key 0x003d Scancode 0x000d (EQUAL) (with shift control) was released
0000000c to 1 at 10,140: Character 0x0000002b (+) with modifiers (with shift control) input

0000000d to 1 at 19,945: Key 0x002d Scancode 0x000c (MINUS) (with shift control) was pressed
0000000e to 1 at 19,945: Character 0x0000005f (_) with modifiers (with shift control) input
0000000f to 1 at 20,006: Key 0x002d Scancode 0x000c (MINUS) (with shift control) was released
00000010 to 1 at 20,006: Character 0x0000005f (_) with modifiers (with shift control) input

00000011 to 1 at 20,512: Key 0x0154 Scancode 0x002a (LEFT SHIFT) (with shift control) was released
00000012 to 1 at 20,529: Key 0x0155 Scancode 0x001d (LEFT CONTROL) (with control) was released
```

**Comment by kovidgoyal** [comment] 2018-04-24 00:31
Run kitty with

GLFW_DEBUG_KEYBOARD=1 kitty

kitty uses a patched version of glfw that does not share any keyboard handling with the original.

**Comment by gustafj** [comment] 2018-04-24 06:10
The mappings has been working in the past (unfortunately don't know which version).
Currently running 0.9.0, but also 0.8.4 behaved in the same way.

Input source is defined as EN_US:

Output from `=`
```
scancode: 0x15 release: 0 clean_sym: dead_acute composed_sym: equal text: = mods: numlock glfw_key: UNKNOWN
scancode: 0x15 release: 1 clean_sym: dead_acute mods: numlock glfw_key: UNKNOWN
```

Output from `ctrl+shift+equal`
```
scancode: 0x25 release: 0 clean_sym: Control_L composed_sym: Control_L mods: numlock glfw_key: LEFT CONTROL
scancode: 0x32 release: 0 clean_sym: Shift_L composed_sym: Shift_L mods: ctrl+numlock glfw_key: LEFT SHIFT
scancode: 0x15 release: 0 clean_sym: dead_acute composed_sym: plus mods: ctrl+shift+numlock glfw_key: UNKNOWN
scancode: 0x15 release: 1 clean_sym: dead_acute mods: ctrl+shift+numlock glfw_key: UNKNOWN
scancode: 0x32 release: 1 clean_sym: Shift_L mods: ctrl+shift+numlock glfw_key: LEFT SHIFT
scancode: 0x25 release: 1 clean_sym: Control_L mods: ctrl+numlock glfw_key: LEFT CONTROL
```

Output from `-`
```
scancode: 0x14 release: 0 clean_sym: plus composed_sym: minus text: - mods: numlock glfw_key: UNKNOWN
scancode: 0x14 release: 1 clean_sym: plus mods: numlock glfw_key: UNKNOWN
```

Output from `ctrl+shift+minus`
```
scancode: 0x25 release: 0 clean_sym: Control_L composed_sym: Control_L mods: numlock glfw_key: LEFT CONTROL
scancode: 0x32 release: 0 clean_sym: Shift_L composed_sym: Shift_L mods: ctrl+numlock glfw_key: LEFT SHIFT
scancode: 0x14 release: 0 clean_sym: plus composed_sym: underscore mods: ctrl+shift+numlock glfw_key: UNKNOWN
scancode: 0x14 release: 1 clean_sym: plus mods: ctrl+shift+numlock glfw_key: UNKNOWN
scancode: 0x32 release: 1 clean_sym: Shift_L mods: ctrl+shift+numlock glfw_key: LEFT SHIFT
scancode: 0x25 release: 1 clean_sym: Control_L mods: ctrl+numlock glfw_key: LEFT CONTROL
```

**Comment by gustafj** [comment] 2018-04-24 12:11
Thanks for the feedback!

I have two keyboard layouts configured (in Gnome), SV_SE and EN_US. 
After swapping the order to EN_US, SV_SE the mappings work in kitty, though they are active both when EN_US is active and SV_SE.

So it appears that switching layouts is not working correctly, and/or the primary layout has side effects.
Are you doing the key mapping based on scancode or keysym?


GLFW events test output with layouts swapped, EN_US active (and primary):
```
00000005 to 1 at 7,667: Key 0x0155 Scancode 0x001d (LEFT CONTROL) (with no mods) was pressed
00000006 to 1 at 7,667: Key 0x0154 Scancode 0x002a (LEFT SHIFT) (with control) was pressed
00000007 to 1 at 8,482: Key 0x003d Scancode 0x000d (EQUAL) (with shift control) was pressed
00000008 to 1 at 8,482: Character 0x0000002b (+) with modifiers (with shift control) input
00000009 to 1 at 8,562: Key 0x003d Scancode 0x000d (EQUAL) (with shift control) was released
0000000a to 1 at 8,562: Character 0x0000002b (+) with modifiers (with shift control) input
0000000b to 1 at 10,426: Key 0x0155 Scancode 0x001d (LEFT CONTROL) (with shift control) was released
0000000c to 1 at 10,426: Key 0x0154 Scancode 0x002a (LEFT SHIFT) (with shift) was released
```

GLFW events test output with layouts swapped, SV_SE active (EN_US primary):
```
0000000f to 1 at 13,411: Key 0x0155 Scancode 0x001d (LEFT CONTROL) (with no mods) was pressed
00000010 to 1 at 13,411: Key 0x0154 Scancode 0x002a (LEFT SHIFT) (with control) was pressed
00000011 to 1 at 13,762: Key 0x003d Scancode 0x000d (EQUAL) (with shift control) was pressed
00000012 to 1 at 13,855: Key 0x003d Scancode 0x000d (EQUAL) (with shift control) was released
00000013 to 1 at 14,667: Key 0x0155 Scancode 0x001d (LEFT CONTROL) (with shift control) was released
00000014 to 1 at 14,667: Key 0x0154 Scancode 0x002a (LEFT SHIFT) (with shift) was released
```


Kitty output with EN_US, SV_SE configured (EN_US active and primary):
```
[114 14:06:06.579791] [PARSE ERROR] Unknown OSC code: 7
scancode: 0x25 release: 0 clean_sym: Control_L composed_sym: Control_L mods: none glfw_key: LEFT CONTROL
scancode: 0x32 release: 0 clean_sym: Shift_L composed_sym: Shift_L mods: ctrl+numlock glfw_key: LEFT SHIFT
scancode: 0x15 release: 0 clean_sym: equal composed_sym: plus mods: ctrl+shift+numlock glfw_key: EQUAL
scancode: 0x15 release: 1 clean_sym: equal mods: ctrl+shift+numlock glfw_key: EQUAL
scancode: 0x25 release: 1 clean_sym: Control_L mods: ctrl+shift+numlock glfw_key: LEFT CONTROL
scancode: 0x32 release: 1 clean_sym: Shift_L mods: shift+numlock glfw_key: LEFT SHIFT
```

Kitty output with EN_US, SV_SE configured (SV_SE active):
```
scancode: 0x25 release: 0 clean_sym: Control_L composed_sym: Control_L mods: numlock glfw_key: LEFT CONTROL
scancode: 0x32 release: 0 clean_sym: Shift_L composed_sym: Shift_L mods: ctrl+numlock glfw_key: LEFT SHIFT
scancode: 0x15 release: 0 clean_sym: equal compose not complete, ignoring.
scancode: 0x15 release: 1 clean_sym: equal mods: ctrl+shift+numlock glfw_key: EQUAL
scancode: 0x32 release: 1 clean_sym: Shift_L mods: ctrl+shift+numlock glfw_key: LEFT SHIFT
scancode: 0x25 release: 1 clean_sym: Control_L mods: ctrl+numlock glfw_key: LEFT CONTROL
```

FYI:
I am running wayland, and was running with the X11 backend. Wayland backend did not start:
```
env KITTY_ENABLE_WAYLAND=1 kitty
xdg_wm_base@8: error 4: wl_surface@17 already has a buffer committed
[114 12:01:12.714933] [glfw error 65544]: Wayland: Focusing a window requires user interaction
[114 12:01:12.714951] [glfw error 65544]: Wayland: Window position retrieval not supported
```

**Comment by kovidgoyal** [comment] 2018-04-24 12:27
As far as I can see there is no state preserved when the keymap is changed see the function glfw_xkb_compile_keymap() where both state and compose_state are re-initialized when the X server delivers a XkbMapNotifyEvent. state and compose_state are the only state involved in converting scancodes to keysyms.

**Comment by kovidgoyal** [comment] 2018-04-26 03:09
As I cannot see anything wrong in the code, and cannot reproduce this issue, I am closing this bug report, feel free to re-open if you see something I missed.

**Comment by gustafj** [comment] 2018-04-26 12:15
This does not trigger a full keymap change, only a layout change.
And thus XkbMapNotify is not triggered.

However a XkbStateNotify is triggered with XkbGroupState bit set in state_event->changed.
Which seems to be silently ignored as it is now.
Unfortunately I'm unfamiliar with XKB, so I dunno how to perform a layout change.

I also noted that this code block `else if (event->type == _glfw.x11.xkb.eventBase) {...}` is specific to kitty and not part of standard GLFW which might explain why the behaviour in the GLFW evtest behaves differently.

**Comment by kovidgoyal** [comment] 2018-04-26 12:38
I dont understand what you are saying. XkBStateNotify is never ignored, it is always passed to libxkb which updates state as per the event (see glfw_xkb_update_modifiers()). And the check for `(event->type == _glfw.x11.xkb.eventBase)` is most definitely required (see man XkbQueryExtension). All events from the XKB extension have their types set to that value, that's how you recognize the event belongs to the Xkb extension. The original glfw did not use it because it did not listen for state or map notify events at all, as it did not support changing keyboard layouts at all. 

So I'm not clear as to where you think the bug is.

Not to mention that according to the docs keyboard state has nothing to do with layout. Changing the layout must generate a MapNotify event, which is what it does on my system. Why is layout change not generating MapNotify on your system?

https://www.x.org/releases/X11R7.6/doc/libX11/specs/XKB/xkblib.html#keyboard_state
https://www.x.org/releases/X11R7.6/doc/libX11/specs/XKB/xkblib.html#xkb_keyboard_mapping

**Comment by gustafj** [comment] 2018-04-26 13:37
I did not mean that XkbStateNotify was ignored, I only meant that "group" changes seemed to be ignored. Sorry for the bad wording.

If I change (add, modify, remove) a layout from the `Region & Language` setting in gnome, then indeed a MapNotify event is triggered, but as long as I have less that 4 listed layouts I am able to switch between them without triggering a MapNotify (e.g using key combination, or the language drop-down menu).

If I have 4 or more then a MapNotify is triggered for every 4th step (change between 1-3 does not trigger a MapNotify, however 1 -> 4 does, but 4 -> 5 does not, while 4 -> 2 does).

Instead these trigger a StateNotify with XkbGroupState (0x10) set in state_event->change (value is 0x90).
This seems to be in line with the docs:
> Changing to a different group changes the keyboard state to produce characters from a different group. Groups are typically used to switch between keysyms of different languages and locales. 
> The Xkb extension supports up to four keysym groups.

It would appear that `xkb_state_update_mask` should be able to handle this, but it appears it does not.

**Comment by kovidgoyal** [comment] 2018-04-26 13:52
Hmm not sure what I can do about this. It seems like a bug in libxkbcommon. Perhaps one way to workaround it is to rebuild the map on every group state change? But that might be both slow and also wrong, because rebuilding the map discards modifier and compose state information.

**Comment by kovidgoyal** [comment] 2018-04-26 13:56
Looking at the example in the libxkbcommon repo: https://github.com/xkbcommon/libxkbcommon/blob/master/test/interactive-x11.c

it also only calls xkb_state_update_mask on statenotify events. Which is what we do as well. Maybe you should open a bug report in the libxkbcommon repo asking about the correct way to handle this situation.

**Comment by kovidgoyal** [comment] 2018-04-27 01:36
According to the debug output you posted with GLFW_DEBUG_KEYBOARD the problem was in the call to xkb_state_key_get_syms() because the state value was incorrect after switching, because xkb was not handling the group change statenotify event. xkb_state_key_get_syms() is called before any glfw/kitty code is involved so I dont see where there could be a bug.

**Comment by kovidgoyal** [comment] 2018-04-27 01:47
Actually, on second thoughts, I think I know what the problem is, clean_state needs to be updated with the group status as well. Currently it is used to get the key pressed without modifiers and without groups. I suppose it should be changed to be without modifiers, but with groups. Although given the insanity of XKB I'm sure that will break something else.

**Comment by gustafj** [comment] 2018-04-27 07:37
I added `xkb_state_update_mask(xkb->clean_state, 0, 0, 0, base_group, latched_group, locked_group);` to `glfw_xkb_update_modifiers` and so far it works, will use this patched version for a while and see if it breaks something else.

But hopefully this should be it :smiley:, thanks for the support!

**Closed** 2018-04-27 10:03 UTC
