### ISSUE TITLE
Kitty 0.22.1 hangs on Apple Silicon / M1

### ISSUE THREAD

**Issue by ahmedre** [kovidgoyal/kitty#3890] opened 2021-07-31 20:33 UTC
**Describe the bug**
On Kitty 0.22.1, if I open a terminal and type any two characters, the first character appears and then the terminal just hangs. If I quit and try again, I can repro this 100%. This is only happening on Apple Silicon (on the M1), it works fine on Intel Macs.

This doesn't happen on 0.21.2 nor on 0.22.0, but happens on 0.22.1.

**To Reproduce**
1. Open a new instance of Kitty
2. Type any two characters (ls) or hit enter
3. Kitty hangs

**Screenshots**
<img width="703" alt="Screen Shot 2021-08-01 at 12 30 05 AM" src="https://user-images.githubusercontent.com/47771/127751790-2a2d0367-93ba-444f-b695-44ef1fd0fdf1.png">

One of these terminals is after cmd+n after the first one hangs.

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+, on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

Shortcut does nothing for me :( Command line parameter says "unknown option."

**Additional context**

Problem happens with`kitty --config NONE`also.

**Comment by ahmedre** [comment] 2021-07-31 22:56
as an update, on Intel Macs, this same one doesn't happen, but I found a reproducible way to get a similar hang on Intel based Macs (though to be honest, I didn't try the previous versions of Kitty with this repro on Intel Macs yet to see if I can repro with them) - 

1. launch Kitty.
2. hit ctrl+d so no Kitty terminal is open.
3. if you have screensavers that a launch when in a corner, go to the corner and let the screensaver start (I wait 1 second usually).
4. move the mouse or press a key to wake up the computer
5. tap the Kitty icon in the dock

expected: new Kitty terminal ready to go
actual: new Kitty terminal with no prompt, no cursor, etc.

**Comment by kidonng** [comment] 2021-08-01 01:18
I can confirm Kitty also hangs on Intel Macs. I kept a open Kitty window and closed the lid, and when I open the lid and wake up the laptop this morning, Kitty hangs.

**Comment by kovidgoyal** [comment] 2021-08-01 02:27
Do a bisect, most likely it is because of #3875

**Comment by zzhaolei** [comment] 2021-08-01 02:37
After the update, enter any character hang in the full-screen

**Comment by kovidgoyal** [comment] 2021-08-01 03:31
The issue with hanging on sleep/screensaver is a long standing one, its a bug In CVDisplay link, and can be easily worked around, see #2016 that has nothing to do with this issue.

**Comment by kidonng** [comment] 2021-08-01 04:48
> The issue with hanging on sleep/screensaver is a long standing one, its a bug In CVDisplay link, and can be easily worked around, see #2016 that has nothing to do with this issue.

Ah OK, this is the first time I experienced this and this new issue immediately caught my eye.

**Comment by kovidgoyal** [comment] 2021-08-01 07:26
Doesnt reproduce for me on my Intel mac, but after staring at the code for some time, here is a possible fix: https://github.com/kovidgoyal/kitty/commit/ade4e67b51922f9e43ce30917ca3f4681e9676c3

please test it and let me know if it works or not. Build kitty like this: https://sw.kovidgoyal.net/kitty/build/

**Comment by ahmedre** [comment] 2021-08-01 22:44
@kovidgoyal thank you - that fixes it for me on the m1 (not sure if it matters or not, but I did not do `make app` - I only did `make` and ran `./kitty/launcher/kitty`).

**Comment by zzhaolei** [comment] 2021-08-02 02:33
For Me, after compiling the latest code, everything is fine

**Comment by kovidgoyal** [comment] 2021-08-02 02:39
Closing as fixed.

**Closed by kovidgoyal** 2021-08-02 02:39 UTC
Labels: bug

**Comment by zzhaolei** [comment] 2021-08-03 04:02
@kovidgoyal This issue has been fixed in 0.22.2. However, when setting the attribute `hide_window_decorations yes`, this problem occurs again.

**Comment by kovidgoyal** [comment] 2021-08-03 04:09
On Mon, Aug 02, 2021 at 09:02:54PM -0700, dO.Ob -> zhaolei wrote:
> @kovidgoyal This issue has been fixed in 0.22.2. However, when setting the attribute `hide_window_decorations yes`, this problem occurs again.

Post an exact set of steps to reproduce the problem with a minimal
kitty.conf

**Comment by zzhaolei** [comment] 2021-08-03 06:11
@kovidgoyal This is all configuration：

```conf
# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

# -- General ------------------------------------

shell       /usr/local/bin/fish --login

include     themes/colors/base16-dracula-256.conf
include     themes/tabs/powerline.conf

font_size           18.0

font_family         Cascadia Code
disable_ligatures   always

# use slashed zero
font_features       CascadiaCode-Regular +zero

# scroll
scrollback_lines                10000
scrollback_pager_history_size   10
scrollback_fill_enlarged_window yes

wheel_scroll_multiplier     5.0
touch_scroll_multiplier     10.0

macos_thicken_font          0.55
window_padding_width        6 6 6 6

hide_window_decorations     yes


# -- Shortcuts ------------------------------------

# set font size
map kitty_mod+0         change_font_size all 0
map kitty_mod+equal     change_font_size all +1.0
map kitty_mod+minus     change_font_size all -1.0

# scrollback
map ctrl+l              combine : clear_terminal scroll     active : send_text all \x0c
map cmd+k               combine : clear_terminal scrollback active : send_text all \x0c

# change window size
map kitty_mod+up        toggle_maximized

# split window
enabled_layouts         splits:split_axis=horizontal
map cmd+enter           launch --cwd=current --location=vsplit
map cmd+shift+enter     launch --cwd=current --location=hsplit

map cmd+n               new_os_window
map cmd+w               close_window

map cmd+1               goto_tab 1
map cmd+2               goto_tab 2
map cmd+3               goto_tab 3
map cmd+4               goto_tab 4
map cmd+5               goto_tab 5
map cmd+6               goto_tab 6
map cmd+7               goto_tab 7
map cmd+8               goto_tab 8
map cmd+9               goto_tab 9

mouse_map cmd+left      click   grabbed,ungrabbed mouse_click_url

# disable shortcuts
map       cmd+r             no-op
mouse_map left              click   grabbed,ungrabbed no-op
mouse_map shift+left        click   grabbed,ungrabbed no-op
mouse_map ctrl+shift+left   press   grabbed,ungrabbed no-op
mouse_map ctrl+shift+left   release grabbed,ungrabbed no-op

```

**Comment by kovidgoyal** [comment] 2021-08-03 07:22
Doesn't reproduce for me with the following:

1) Run: kitty --config NONE -o hide_window_decorations=y
2) Press ctrl+shift+f11 to toggle full screen
3) Click inside the full screen window 
4) type something, it shows up

**Comment by kovidgoyal** [comment] 2021-08-03 11:48
You cant input anything because the window doesnt have focus. *click in
it*. There was a reason I included step 3 above.

**Comment by zzhaolei** [comment] 2021-08-03 14:21
No, I did step 3, but I still can’t type it in.

But it doesn't matter. I turned it off and it works

**Comment by bitwalker** [comment] 2021-08-03 14:57
Just wanted to chime in and say that I've been experiencing this as well. I've built v0.22.2 and will report back by tomorrow if it is still happening on my system, fingers crossed its fixed though.

Oddly enough, it seemed to predictably happen after sleep, but there was at least one time where I didn't let my laptop sleep but it still happened. Unfortunately it caught me off guard so I wasn't paying attention to what caused it, but I'm suspecting that the screensaver turned on for a second, or was activating, and that's why. Anyway, if I notice any other root causes I'll follow up.

**Comment by zzhaolei** [comment] 2021-08-03 14:59
I'm sorry. After I've performed step 3, it's working!

**Comment by zzhaolei** [comment] 2021-08-03 15:03
@bitwalker If the program is compiled locally, the old program is started when the first step `(kitty --config NONE -o hide_window_decorations=y)` is executed. 

Maybe you should run `./kitty/launcher/kitty --config NONE -o hide_window_decorations=y`?
