### ISSUE TITLE
Closing a tab copies line below the cursor to the first line 

### ISSUE THREAD

**Issue by Janiczek** [kovidgoyal/kitty#725] opened 2018-07-15 21:30 UTC
Let's say I have a tab with `vim` open. I open a new tab, close it, and get garbled output for the original tab.

Here's a video:
![kitty2](https://user-images.githubusercontent.com/149425/42738610-c9c977e2-8886-11e8-946a-cf45a8b2e0d2.gif)

In it I'm creating a new tab, closing the tab (Ctrl+D) and clearing the screen (Ctrl+L).
Each time I get into the original tab, the line below the cursor gets copied to the first line, which it probably shouldn't.

------

Related, but I'm not sure if you'll want this as separate issues:
* Even moving between tabs (not closing one of them) does show some garbled output, but different from when closing the tab, and I wasn't able to figure out the "rules."
* Resizing the `kitty` OS window does a similar thing.

_By the way, thanks for creating `kitty`! I needed something that fast :smile:_

**Comment by kovidgoyal** [comment] 2018-07-16 03:32
This was fixed a long time ago, are you running an up to date kitty? Current release is 0.11.3 If you are then feel free to re-open. Otherwise updating should fix it.

**Comment by Janiczek** [comment] 2018-07-16 07:33
Yes, I'm running the current version (downloaded from releases here on the GitHub repo). Linux x64.
```
$ kitty --version
kitty 0.11.3 created by Kovid Goyal
```

**Comment by kovidgoyal** [comment] 2018-07-16 07:35
Then create a minimal set of steps to re-create the issue and use the --dump-byes option to create a dump file and attach it, I will try to re-create with that.

**Comment by Janiczek** [comment] 2018-07-16 07:57
`$ kitty --dump-bytes=kittydump.txt >commands.txt`
[commands.txt](https://github.com/kovidgoyal/kitty/files/2196813/commands.txt)
[kittydump.txt](https://github.com/kovidgoyal/kitty/files/2196814/kittydump.txt)
What I did after the terminal opened is roughly:
1. `vim<Enter>` (open an editor)
2. `o`, `ABCDE<Enter>FGHIJ<Ctrl-C>`, `kk0` (write stuff to a scratch file and get the cursor to the start of the file)
3. `<Ctrl-T><Ctrl-D>` (new tab, exit it)
4. `<Ctrl-L>`, `j` (clear the screen, go down a line)
5. steps 3,4 again and then some cleanup (`ZQ`, `<Ctrl-D>`) - but the issue shows at the end of step 3.

**Comment by kovidgoyal** [comment] 2018-07-16 08:03
OK thanks I'll take a look when I have a moment.

**Comment by kovidgoyal** [comment] 2018-07-17 03:47
It's a little hard to see whats going o with that dump file as itand I can't recreate the issue with that set of steps. Could you close kitty immediately after the issue has happened when generating the dump file. That way I dont have to bisect it trying to find where the issue is occurring.

Oh and try using 

vim -u NONE

to simplify the amount of things vim does.

**Comment by Janiczek** [comment] 2018-07-17 07:14
Well that's interesting. With `vim -u NONE` it doesn't happen. I'll try to find out what configuration does it, maybe that will shed some light on it.

**Comment by kovidgoyal** [comment] 2018-07-17 07:41
I took a quick look at gruvbox and wow for a colorscheme it is pretty huge. If I had ot guess it would be something cursor related in gruvbox.vim

**Comment by kovidgoyal** [comment] 2018-07-19 00:20
I cannot reproduce using the steps you posted and a minimal vimrc with only
color gruvbox
in it (and gruvbox installed, of course)

Closing for now, since I have no way to reproduce. If you can find more information, feel free to update this bug report.

**Closed by kovidgoyal** 2018-07-19 00:20 UTC
