### ISSUE TITLE
Window placement and scaling issue on macOS Big Sur (11.1)

### ISSUE THREAD

**Issue by Frederick888** [kovidgoyal/kitty#3253] opened 2021-01-21 22:39 UTC
**Describe the bug**
In a dual-display set up, Kitty always starts in the display on the right.

And in case the active display is the left one, the scaling factor of the left display is used. Since I've got a 4K monitor and a 1080p one, depending on the display arrangement, font is either really small or large initially.

**To Reproduce**
1. With macOS Big Sur, have a 4K monitor on the left and a 1080p one on the right
2. Click something in the left 4K monitor
3. Start Kitty
4. Kitty is started in the right 1080p one, and font is really large

**Expected behavior**
Kitty starts in the active monitor and uses the correct scaling factor.

**Environment details**
OS: macOS 11.1

```
kitty 0.19.3 created by Kovid Goyal
Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
ProductName:    macOS ProductVersion:   11.1 BuildVersion:      20C69
Loaded config files: /Users/fzhang/.config/kitty/kitty.conf

Config options different from defaults:
background                         Color(red=25, green=25, blue=25)
background_opacity                 0.85
bold_font                          BitstreamVeraSansMono Nerd Font Mono
bold_italic_font                   BitstreamVeraSansMono Nerd Font Mono
color0                             Color(red=25, green=25, blue=25)
color1                             Color(red=243, green=0, blue=95)
color10                            Color(red=151, green=224, blue=35)
color11                            Color(red=223, green=213, blue=97)
color12                            Color(red=156, green=100, blue=254)
color13                            Color(red=243, green=0, blue=95)
color14                            Color(red=87, green=209, blue=234)
color15                            Color(red=246, green=246, blue=238)
color2                             Color(red=151, green=224, blue=35)
color3                             Color(red=250, green=132, blue=25)
color4                             Color(red=156, green=100, blue=254)
color5                             Color(red=243, green=0, blue=95)
color6                             Color(red=87, green=209, blue=234)
color7                             Color(red=196, green=196, blue=181)
color8                             Color(red=97, green=94, blue=75)
color9                             Color(red=243, green=0, blue=95)
copy_on_select                     clipboard
cursor                             Color(red=246, green=246, blue=236)
enable_audio_bell                  False
env                                {'SHELL': '/usr/local/bin/zsh'}
font_family                        BitstreamVeraSansMono Nerd Hybrid Font Mono
font_size                          12.0
foreground                         Color(red=196, green=196, blue=181)
initial_window_height              (900, 'px')
initial_window_width               (1440, 'px')
italic_font                        BitstreamVeraSansMono Nerd Font Mono
macos_quit_when_last_window_closed True
macos_traditional_fullscreen       True
mouse_hide_wait                    3.0
selection_background               Color(red=52, green=52, blue=52)
selection_foreground               Color(red=25, green=25, blue=25)
shell                              /usr/local/bin/zsh --login
strip_trailing_spaces              always
```

**Additional context**
This issue can be reproduced using `kitty --config NONE` (via `macos-launch-services-cmdline`).

**Comment by kovidgoyal** [comment] 2021-01-22 02:15
Not sure what you are asking for. kitty has to use some monitor's DPI,
and when you move the window to a different monitor it will adjust its
DPI. Beyond that I dont really see what it can do.

**Comment by Frederick888** [comment] 2021-01-22 03:12
@kovidgoyal Yup if I move Kitty to another monitor and back then the issue is gone.

Though previously on Catalina I didn't need to do this. Kitty always showed up on the current monitor (where the current active application is in) with the correct DPI.

**Comment by kovidgoyal** [comment] 2021-01-22 03:18
Hmm well kitty doesnt really control what monitor it shows up on, that's up to the window manager. You can see the code for getting the initial window dpi in glfw.c line 577 onwards. I dont really know what else kitty could do there. It creates a temp window, queries it for DPI and then uses that dpi for the actual window. I have no idea why the temp window and the real window are on different monitors

**Comment by kovidgoyal** [comment] 2021-01-22 03:21
One possibility is to check the dpi after showing the window and if it is different, rescale. See line 627 if you add a call to check the dpi there after the call to show th ewindow, is it different? I cant test this myself as I dont have the needed hardware.

**Comment by Frederick888** [comment] 2021-01-22 04:06
Yup that did fix the scaling issue!

```diff
diff --git a/kitty/glfw.c b/kitty/glfw.c
index 2dce3191..59a7b393 100644
--- a/kitty/glfw.c
+++ b/kitty/glfw.c
@@ -624,8 +624,15 @@ create_os_window(PyObject UNUSED *self, PyObject *args) {
         if (pret == NULL) return NULL;
         Py_DECREF(pret);
         if (x != -1 && y != -1) glfwSetWindowPos(glfw_window, x, y);
         glfwShowWindow(glfw_window);
+        get_window_content_scale(glfw_window, &xscale, &yscale, &xdpi, &ydpi);
+        fonts_data = load_fonts_data(global_state.font_sz_in_pts, xdpi, ydpi);
+        ret = PyObject_CallFunction(get_window_size, "IIddff", fonts_data->cell_width, fonts_data->cell_height, fonts_data->logical_dpi_x, fonts_data->logical_dpi_y, xscale, yscale);
+        if (ret != NULL) {
+            width = PyLong_AsLong(PyTuple_GET_ITEM(ret, 0)), height = PyLong_AsLong(PyTuple_GET_ITEM(ret, 1));
+            Py_CLEAR(ret);
+        }
     }
     if (is_first_window) {
         PyObject *ret = PyObject_CallFunction(load_programs, "O", is_semi_transparent ? Py_True : Py_False);
         if (ret == NULL) return NULL;
```

But Kitty still shows up in the wrong monitor. And I noticed that, before or after this patch, this only happens when Kitty is maximised (via `remember_window_size yes`) or started with `--start-as=fullscreen`.

**Comment by Frederick888** [comment] 2021-01-22 12:11
It seems that this is actually caused by incorrect window position.

```diff
diff --git a/kitty/glfw.c b/kitty/glfw.c
index 32c9e8e0..df71f5c5 100644
--- a/kitty/glfw.c
+++ b/kitty/glfw.c
@@ -416,8 +416,51 @@ make_os_window_context_current(OSWindow *w) {
         glfwMakeContextCurrent(w->handle);
     }
 }
 
+static int
+maxi(int a, int b) {
+    return a > b ? a : b;
+}
+
+static int
+mini(int a, int b) {
+    return a < b ? a : b;
+}
+
+static GLFWmonitor*
+get_current_monitor(GLFWwindow *window) {
+    // https://stackoverflow.com/questions/21421074/
+    // find current monitor by largest overlapping area of given window
+    int nmonitors, i;
+    int wx, wy, ww, wh;
+    int mx, my, mw, mh;
+    int overlap, bestoverlap;
+    GLFWmonitor *bestmonitor;
+    GLFWmonitor **monitors;
+
+    bestoverlap = 0;
+    bestmonitor = NULL;
+
+    glfwGetWindowPos(window, &wx, &wy);
+    glfwGetWindowSize(window, &ww, &wh);
+    monitors = glfwGetMonitors(&nmonitors);
+
+    for (i = 0; i < nmonitors; i++) {
+        glfwGetMonitorWorkarea(monitors[i], &mx, &my, &mw, &mh);
+
+        overlap =
+            maxi(0, mini(wx + ww, mx + mw) - maxi(wx, mx)) *
+            maxi(0, mini(wy + wh, my + mh) - maxi(wy, my));
+
+        if (bestoverlap < overlap) {
+            bestoverlap = overlap;
+            bestmonitor = monitors[i];
+        }
+    }
+
+    return bestmonitor;
+}
 
 static inline void
 get_window_content_scale(GLFWwindow *w, float *xscale, float *yscale, double *xdpi, double *ydpi) {
     *xscale = 1; *yscale = 1;
@@ -603,8 +646,15 @@ create_os_window(PyObject UNUSED *self, PyObject *args) {
     PyObject *ret = PyObject_CallFunction(get_window_size, "IIddff", fonts_data->cell_width, fonts_data->cell_height, fonts_data->logical_dpi_x, fonts_data->logical_dpi_y, xscale, yscale);
     if (ret == NULL) return NULL;
     int width = PyLong_AsLong(PyTuple_GET_ITEM(ret, 0)), height = PyLong_AsLong(PyTuple_GET_ITEM(ret, 1));
     Py_CLEAR(ret);
+    GLFWmonitor *monitor = get_current_monitor(temp_window ? temp_window : common_context);
+    if (monitor) {
+        int monitor_x, monitor_y;
+        glfwGetMonitorWorkarea(monitor, &monitor_x, &monitor_y, NULL, NULL);
+        x = x < monitor_x ? monitor_x : x;
+        y = y < monitor_y ? monitor_y : y;
+    }
     // The GLFW Wayland backend cannot create and show windows separately so we
     // cannot call the pre_show_callback. See
     // https://github.com/glfw/glfw/issues/1268 It doesn't matter since there
     // is no startup notification in Wayland anyway. It amazes me that anyone
```

This fixed the issue for me. Without it `x` & `y` are always `-1`.

**Comment by Frederick888** [comment] 2021-01-22 12:14
But the underlying issue might be that 
https://github.com/kovidgoyal/kitty/blob/0c784346cc3e606bab23d552b73c845d34cb79e4/kitty/glfw.c#L542
somehow stopped working on Big Sur.

**Comment by kovidgoyal** [comment] 2021-01-22 12:42
That line is just getting parameters from python. A value of -1 means no initial position is specified. Which is what we want, as we dont save and restore window positions only sizes.

**Comment by Frederick888** [comment] 2021-01-22 12:48
Huh, so do you reckon my patch is fine? If yes I can submit a PR.

**Comment by kovidgoyal** [comment] 2021-01-22 13:10
No, not really. Your patch essentially always places the window at the
top left of the monitor, which probably works well for you but not in
the general case. As far as I can tell, the problem is that when no
initial position is specified, the OS is moving the window off the
current monitor. Not really sure how to convince it not to do that.

**Comment by kovidgoyal** [comment] 2021-01-22 14:54
And I committed code to ensure the font size is changed if needed after the window is shown, so that part should be fixed. However, I still dont know how to convince macOS to not move the window off the monitor. You are sure that sizing the window to a size less than the available area doesnt work?

**Comment by Frederick888** [comment] 2021-01-22 14:54
May I know what https://github.com/kovidgoyal/kitty/blob/0c784346cc3e606bab23d552b73c845d34cb79e4/kitty/glfw.c#L581-L586 is for? didn't quite understand the commit message, but after removing these lines the window position issue is gone.

---

And by the way, another issue I've noticed under Big Sur is that when using `macos_traditional_fullscreen yes`, after entering fullscreen mode using hotkey or `--start-as fullscreen`, I cannot type anything unless I use mouse to click once on Kitty first. Any clue on this one?

**Comment by kovidgoyal** [comment] 2021-01-22 15:01
On Fri, Jan 22, 2021 at 06:54:38AM -0800, Frederick Zhang wrote:
> May I know what https://github.com/kovidgoyal/kitty/blob/0c784346cc3e606bab23d552b73c845d34cb79e4/kitty/glfw.c#L581-L586 is for? didn't quite understand the commit message, but after removing these lines the window position issue is gone.

That's a global window that is used to implement the macOS behavior of
closing all windows but not quitting the application.

> 
> ---
> 
> And by the way, another issue I've noticed under Big Sur is that when using `macos_traditional_fullscreen yes`, after entering fullscreen mode using hotkey or `--start-as fullscreen`, I cannot type anything unless I use mouse to click once on Kitty first. Any clue on this one?

#3100

**Comment by Frederick888** [comment] 2021-01-22 15:30
```diff
diff --git a/kitty/glfw.c b/kitty/glfw.c
index 32c9e8e0..45e1b9c4 100644
--- a/kitty/glfw.c
+++ b/kitty/glfw.c
@@ -585,9 +585,9 @@ create_os_window(PyObject UNUSED *self, PyObject *args) {
     GLFWwindow *common_context = global_state.num_os_windows ? global_state.os_windows[0].handle : NULL;
     GLFWwindow *temp_window = NULL;
 #ifdef __APPLE__
     if (!apple_preserve_common_context) {
-        apple_preserve_common_context = glfwCreateWindow(100, 200, "kitty", NULL, common_context);
+        apple_preserve_common_context = glfwCreateWindow(640, 480, "kitty", NULL, common_context);
     }
     if (!common_context) common_context = apple_preserve_common_context;
 #endif
     if (!global_state.is_wayland) {
```

...fixes this issue. I don't understand why though... I just noticed that the only difference between `apple_preserve_common_context` and `temp_window` is size so blindly gave it a shot.

Big Turd indeed lmao

**Closed** 2021-01-22 15:37 UTC
Labels: bug
