### ISSUE TITLE
Emojis with the sequence U+FE0F U+200D provoke weird display bugs

### ISSUE THREAD

**Issue by ariasuni** [kovidgoyal/kitty#414] opened 2018-03-22 16:32 UTC
I’m using Kitty 0.8.2.

When try I paste some emoji with this character sequence, for example: 

- [👩‍❤️‍💋‍👩 “Kiss: Woman, Woman”](https://emojipedia.org/kiss-woman-woman/)
- [👩‍❤️‍👩 “Couple With Heart: Woman, Woman”](https://emojipedia.org/couple-with-heart-woman-woman/)
- [🏴‍☠️ Pirate Flag](https://emojipedia.org/pirate-flag/)

it is displayed as several characters, and trying to move back and forward duplicates the emojis.

Also, the [🏳️ White Flag](https://emojipedia.org/waving-white-flag/) emoji alone triggers the same behavior.

Examples:

```
<CTRL-SHIFT-V>
🏳️
<LEFT>
🏳️🏳️
<LEFT>
🏳️🏳️
<LEFT>
🏳️🏳️🏳️
<BACKSPACE>
🏳️🏳️🏳️  # The cursor is half into the last flag
```

```
<CTRL-SHIFT-V>
👩❤️💋👩  # the first is displayed as a two width character, the others as one
<LEFT>
👩👩❤️💋👩
<LEFT>
👩👩 ❤️💋👩
<LEFT>
👩👩👩❤️💋👩  # at this point, the cursor is on the kiss mark
<LEFT>
👩👩👩 ❤️💋👩
<LEFT>
👩👩👩👩❤️💋👩
<BACKSPACE>
👩👩👩👩 💋👩  # still on the kiss mark
<BACKSPACE>
👩👩👩👩 👩
(etc.)
```

**Comment by kovidgoyal** [comment] 2018-03-22 16:51
Moving back and forth in what program? There are very few (almost none) terminal programs that understand complex multi-codepoint emoji. Kitty will display emoji as either one cell wide or two cells wide as per the unicode standartd. The problems come because most terminal programs dont follow the standard. 

Oh and the sequence U+FE0F U+200D is invalid, the variation selector U+FE0F has to come after the codepoint not before.

**Comment by ariasuni** [comment] 2018-03-22 17:05
> Moving back and forth in what program?

In bash or fish.

> Oh and the sequence U+FE0F U+200D is invalid, the variation selector U+FE0F has to come after the codepoint not before.

I copied the emoji from Emojipedia, where it’s displayed as one glyph so I guess what I copied into Kitty was the correct Unicode sequence.

**Comment by kovidgoyal** [comment] 2018-03-22 17:19
Yeah bash and fish have no clue about unicode, you cannot test anything with them.  IIRC kitty does not support zero width joiners, it's not a feature I am interested in implementing, as it is a big performance killer. So your examples with joined characters are going to display as multiple characters. However, U+FEOF works perfectly and I cannot reproduce any issues with duplication of characters when moving the cursor and using cat instead of bash. 

As for U+FEOF it must always come after an emoji codepoint, that is specified in the unicode standard. Which I think it does in your examples, I was just going by the bug title. Open vim for instance and type

```
<C-v>u2716<C-v>ufe0f
```

And you will see the multiplication sign become a colored multiplication emoji. But the cursor will be in the middle of the emoji because vim does not understand U+FE0F

I doubt you are going to have any luck with using the joiner and craiation selector codepoints with most terminal programs, they just dont support them. And of course kitty itself does not support the joiner.

**Closed by kovidgoyal** 2018-03-22 17:19 UTC

**Comment by ariasuni** [comment] 2018-03-23 23:30
I personally don’t care about complex emojis, but I care that my terminal doesn’t break when inserting some characters. I though this may be easy, or it may be hard and not worth it, I don’t know.

**Comment by kovidgoyal** [comment] 2018-03-24 03:34
Your terminal is not breaking, your terminal programs are breaking. As I said, try it with cat, not bash or fish. And yes, the terminal renders zwj incorrectly, but as I sad, that is deliberate, zwj does not really fit witht he design of a terminal as a character grid.

**Comment by ariasuni** [comment] 2018-03-24 07:39
OK, thanks for the answer.
