### ISSUE TITLE
Trouble with tmux ?

### ISSUE THREAD

**Issue by ptbrowne** [kovidgoyal/kitty#877] opened 2018-09-06 09:43 UTC
I just started using Kitty and am already impressed, it is very fast. Thank you ! I donated ;) Thank you for your work on Calibre also :)

I had some weird glitches though. I do not know if it is because of tmux. It is hard to describe so I took a screen recording.

Problems:

- bottom bar disappears
- prompt disappears
- top bar of the pane disappears
- multiple tomatos at the bottom (they should be in the bottom bar)

https://youtu.be/U5ILP7cKKkw

I don't know if they are problems of tmux or of kitty. Everything is working well under iTerm2 though but maybe it has special support for some tmux functions.

**Comment by maximbaz** [comment] 2018-09-06 10:56
Consider abandoning tmux and switching to kitty entirely, your life will be much simpler after that 😉

**Comment by kovidgoyal** [comment] 2018-09-06 11:29
Yeah I have to agree with @maximbaz one of my main motivations in developing kitty was to get rid of the need to use terminal multiplexers. 

That said, kitty should work fne with tmux, so if you can find some minimal kitty+tmux config+ set of steps to reporduce the issue, I will be happy to investigate and fix it.

**Comment by kovidgoyal** [comment] 2018-09-06 11:31
Note that once you have a minimal config, and a set of step to reproduce, you can either post the set of steps, or simply use the --dump-bytes kitty option to create a dump file I can use to try to reproduce.

**Comment by kovidgoyal** [comment] 2018-09-06 11:55
And I should note that one of the most common causes of issues with terminal applications is using unicode charactres, this is because kitty follows the latest unicode spec when calculating the number of cells a character occupies while many terminal applications do not and instead rely on outdated system wcwidth() functions. The mismatch between the two often causes rendering issues.

**Comment by ptbrowne** [comment] 2018-09-06 12:01
> Consider abandoning tmux and switching to kitty entirely, your life will be much simpler after that 😉

Alright I will try. Does kitty support tmux style commands ? For example to go to the right pane (window in kitty), I am accustomed to typing \` and then left arrow. \` puts me in control mode so that I do not have to have several keys pressed at once.

**Comment by kovidgoyal** [comment] 2018-09-06 12:02
You can create multi-key shortcuts if you prefer those, see the config docs for details, but basically

map a>b some_action

means you first press a then press b

**Comment by kovidgoyal** [comment] 2018-09-06 12:03
closing this bug report, if you wish to debug the tmux issue feel free to comment with the debug details I asked for and I will re-open

**Closed by kovidgoyal** 2018-09-06 12:03 UTC

**Comment by ptbrowne** [comment] 2018-09-06 12:57
Thank you, I managed to get it approximately like my old tmux config with 

```
 map `>` send_text all `
 map `>x close_window
 map `>c new_tab
 map `>s new_window
 map `>v new_window
 map `>q close_tab
 map `>space next_layout
 map `>left previous_window
 map `>right next_window
 map shift+left previous_tab
 map shift+right next_tab
 map `>, set_tab_title
```

Kudos for making something easily configurable !

Is there a way to reload the map config after saving the config file ? I tried to search for "reload", "config" etc... but could not find anything :)

**Comment by kovidgoyal** [comment] 2018-09-06 12:59
No, kitty does not support config reloading.
