### ISSUE TITLE
GNOME: High CPU usage when a dead-key is pending under Wayland

### ISSUE THREAD

**Issue by Chromosore** [kovidgoyal/kitty#5141] opened 2022-05-28 13:37 UTC
**Describe the bug**
This is a follow-up to #5105. It looks like the pre-edit text issue isn't fully solved. There is still a loop of pre-edit text update events when a dead-key is left pending. (I'm using kitty 0.25.1 obviously)

**To Reproduce**
You must use a keyboard layout that features dead-key, so not the English US layout. In my case, I'm using the French layout.
1. Press a dead-key under Wayland
2. Take a look at top. `gnome-shell` and `ibus-daemon` will be using about 100% of your CPU.

Here is a sample of the output of `kitty --debug-keyboard` when I press the `^` key (a dead-key with the French layout):
```
on_key_input: glfw key: 0x0 native_code: 0x0 action: PRESS mods: none text: '^' state: 1 
…
text-input: updating cursor position: left=287 top=23 width=11 height=21
updated pre-edit text: '^'
text-input: preedit_string event: text: ^ cursor_begin: 1 cursor_end: 1
text-input: done event: serial: 3621 current_commit_serial: 3621
…
```

<details>
<summary><b>Environment details</b></summary>

```
kitty 0.25.1 created by Kovid Goyal
Linux aqvitrine 5.17.11-300.fc36.x86_64 #1 SMP PREEMPT Wed May 25 15:04:05 UTC 2022 x86_64
S
Kernel 5.17.11-300.fc36.x86_64 on an x86_64 (/dev/tty)

Running under: Wayland
Frozen: True
Paths:
  kitty: /usr/local/stow/kitty-0.25.1/bin/kitty
  base dir: /usr/local/stow/kitty-0.25.1/lib/kitty
  extensions dir: /usr/local/stow/kitty-0.25.1/lib/kitty-extensions
  system shell: /usr/bin/fish
Loaded config files:
  /home/chromosore/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style   (True, False)
bell_on_tab             
clipboard_control       ('write-clipboard', 'write-primary')
confirm_os_window_close 0
font_size               13.0
initial_window_height   (37, 'cells')
initial_window_width    (110, 'cells')
macos_option_as_alt     2
remember_window_size    False
resize_in_steps         True
shell_integration       frozenset({'no-rc'})
symbol_map:
	U+e0a0 - U+e0a3 → PowerlineSymbols
	U+e0c0 - U+e0c7 → PowerlineSymbols
tab_activity_symbol     ​ •
tab_bar_edge            1
tab_bar_style           separator
tab_separator           
tab_title_template       {title} 
update_check_interval   0.0
url_prefixes            ('http', 'https', 'file', 'ftp', 'gemini', 'irc', 'gopher', 'mailto', 'news', 'git')
Colors:
	active_tab_background   #f0f0f0   
	active_tab_foreground   #5f5f5f   
	background              #fafafa   
	color0                  #5f5f61   
	color1                  #e8503f   
	color10                 #abb96e   
	color11                 #e1ad0b   
	color12                 #8c61a6   
	color13                 #eb314b   
	color14                 #23bce1   
	color15                 #fafafa   
	color2                  #00998c   
	color3                  #d87900   
	color4                  #527f8f   
	color5                  #db2d45   
	color6                  #159ccc   
	color7                  #f0f0f0   
	color8                  #888888   
	color9                  #d87900   
	cursor                  #5f5f61   
	cursor_text_color       #fafafa   
	foreground              #5f5f61   
	inactive_tab_background #f0f0f0   
	inactive_tab_foreground #888888   
	selection_background    #527f9f   
	selection_foreground    #fafafa   
	tab_bar_background      #f0f0f0   

Important environment variables seen by the kitty process:
	PATH                                /home/chromosore/.local/share/go/bin:/home/chromosore/.cargo/bin:/home/chromosore/.local/bin:/home/chromosore/.local/share/perl5/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
	LANG                                fr_FR.utf8
	EDITOR                              nvim
	SHELL                               /usr/bin/fish
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                chromosore
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 gnome-wayland
	XDG_SESSION_TYPE                    wayland
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /home/chromosore/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
```
</details>

**Additional context**
Using `kitty --config none` doesn't make any difference.

**Comment by kovidgoyal** [comment] 2022-05-30 01:58
Doesnt repro for me. Steps I tried:

1) In GNOME keyboard preferences set keyboard layout to English Intl with ALtGr dead keys
2) Set the compose key to right alt
3) Open kitty --debug-keyboard
4) Press right alt - there is no continuous debug output 
5) Press a twice - a with accent appears and still no continuous output

Can you come up with a reproducer using this keyboard layout?

**Comment by Chromosore** [comment] 2022-05-30 17:08
Ok so the problem was that in this layout `altgr` is used for both alternate keys and dead keys.
So to get a dead key, you'd have to press a key like `\`` or `^` with `altgr`. I've tested `altgr` + `\`` and it works (or bugs) as expected.

Anyway, this isn't really an annoying issue (for me at least) so don't feel pressured to fix it in any way. It is already nice to put much efforts into kitty!

**Comment by kovidgoyal** [comment] 2022-05-31 05:30
Still not able to reproduce I tried pressing

Altgr then shift + 6 (which is ^) no continuous loop
then pressed o and got o with circumflex on top as expected, without any
loop.

Am closing this for now as I cannot reproduce, if there are different
reproduction steps feel free to update and i will have a look.

**Closed by kovidgoyal** 2022-05-31 05:30 UTC
Labels: bug
