### ISSUE TITLE
Text selection doesn't account for unicode grapheme clusters 

### ISSUE THREAD

**Issue by hhirtz** [kovidgoyal/kitty#4200] opened 2021-11-06 22:54 UTC
**Describe the bug**
Selected text in kitty is shown with reverted colors. On grapheme clusters (e.g. emoji chains with ZWJ) the selection area seems to expand the width of codepoints taken individually, instead of using the width of the whole cluster.

**To Reproduce**
1. `echo -e '👨\u200d👩\u200d👧\u200d👧'`
2. Select output of echo with a double click for example

**Screenshots**
![screen-20211106234741](https://user-images.githubusercontent.com/51088794/140626002-c596da83-1e0e-4bb6-b841-5eb8fd2d9f7c.png)

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux vroom 5.14.14-arch1-1 #1 SMP PREEMPT Wed, 20 Oct 2021 21:35:18 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Running under:Wayland
Loaded config files:
  /home/hubert/.config/kitty/kitty.conf

Config options different from defaults:
font_family JetBrains Mono
font_size   13.0
Added shortcuts:
	shift+page_up KeyAction('scroll_page_up')
	shift+page_down KeyAction('scroll_page_down')
```

**Comment by kovidgoyal** [comment] 2021-11-07 01:25
dupe of #3810

**Closed by kovidgoyal** 2021-11-07 01:25 UTC
Labels: bug
