### ISSUE TITLE
Fedora Silverblue - Fatal Python error: Unknown value for option -X

### ISSUE THREAD

**Issue by morgaesis** [kovidgoyal/kitty#5238] opened 2022-06-27 17:37 UTC
**Describe the bug**
I recently rebased to Rawhide (rolling/nightly) branch of Fedora Silverblue (standard GNOME). Afterwards, I get an error whenever I start kitty;
```
$ kitty
Fatal Python error: Unknown value for option -X
Python runtime state: preinitialized

```
This means I can't start kitty, neither from GNOME terminal, nor application menu.

**To Reproduce**
1. Use Fedora Rawhide (maybe on Silverblue)
2. Open GNOME Terminal
3. Start kitty with`/usr/bin/kitty`
4. Get error

**Environment details**
```
$ kitty --debug-config
Fatal Python error: Unknown value for option -X
Python runtime state: preinitialized

```

**Additional context**
Same error using option `--config NONE` and `--version`
```
$ python -V
Python 3.11.0b3
```

**Comment by page-down** [comment] 2022-06-27 23:41
Looks like a duplicate of https://github.com/kovidgoyal/kitty/issues/5223

You can try the latest nightly release.

**Closed** 2022-06-28 01:16 UTC
Labels: bug
