### ISSUE TITLE
kitty remains open after closing

### ISSUE THREAD

**Issue by shoober420** [kovidgoyal/kitty#609] opened 2018-06-07 04:30 UTC
When closing kitty with a window manager keybind, the process continues running in the background. This is proven when using htop to verify. If you spawn a terminal several times, and close them all with your window manager keybind, there will be many kitty processes running in the background and chewing up the CPU to 100%.

Only if you close the terminal with the "exit" command, will it truly close the window and process. I have this same issue with the alacritty terminal emulator, but when using the st terminal, all st processes close as expected. I'm using the bspwm window manager.

**Comment by kovidgoyal** [comment] 2018-06-07 04:49
I cannot replicate. Closing kitty with a window manager key combination causes the process to exit. As a matter of fact, kitty cannot run with no open windows, since its main loop quits when all windows are closed.

**Closed by kovidgoyal** 2018-06-07 04:49 UTC

**Comment by shoober420** [comment] 2018-06-07 04:58
I opened multiple kitty windows, and then closed them with my window manager keybind. Oddly enough, my web browser remained open even though I closed the terminal window responsible for its process. I then open up htop and saw that although I closed all the terminal windows with my window manager, they remained opened and my CPU was at 100%.

It seems that the bspwm window manager doesn't truly close the kitty terminal emulator. This must be an issue with my window manager. All other processes close when using the keybind, except kitty and alacritty.

**Comment by kovidgoyal** [comment] 2018-06-07 05:06
I'm not familiar with bspwm, so I cannot comment on that, but if you wish to debug kitty, it is simple, follow the instructions in the INSTALL file to build from source and look at the file child-monitor.c look at the main_loop function see how the loop is conditioned on has_open_windows. Then look at process_pending_closes() which is what sets that variable. 

Then look at should_os_window_close() which is a thin wrapper around the windowing toolkit (glfw) which basically sets  flag on the window when a close event is received from the X server. Once you verify all these functions are working as designed, you can be confident that the problem is somewhere else in your system

**Comment by shoober420** [comment] 2018-06-07 08:48
I'll investigate this further. I find it odd that both kitty and alacritty both exhibit this same behavior. All other programs close as intended with bspwm. Only the "exit" command works to truly close the process. Maybe this is an issue related to glfw/glut.
