### ISSUE TITLE
Nearly 100% cpu usage

### ISSUE THREAD

**Issue by jonasc** [kovidgoyal/kitty#8008] opened 2024-10-31 18:00 UTC
**Describe the bug**
Nearly 100% CPU usage when in focus. Key presses are registered about a second after pressing the keys, sometimes single key presses are registered as two (as in typing "htop" results in e.g. "htoop"). Any interaction has a lag of about a second (e.g. also things like changing the cursor between in-focus and out-of-focus state).

Solutions found here in previous issues do not seem to have any effect.

**To Reproduce**
No steps really, problem appeared out of the blue, not even update related as I had not updated (kitty or my system) for some time. I tried to downgrade to 0.36.x but they also show the same behaviour.

**Environment details**
No fcitx installed.
```
kitty 0.37.0 created by Kovid Goyal
Linux melon 6.11.1-1-ck-generic-v3 #1 SMP PREEMPT_DYNAMIC Tue Oct  1 09:30:37 EDT 2024 x86_64
Arch Linux 6.11.1-1-ck-generic-v3 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland (sway version 1.10) missing: blur
OpenGL: '3.3 (Core Profile) Mesa 21.3.9-arch.6 Amber' Detected version: 3.3
Frozen: False
Fonts:
  medium: NotoSansMono-Regular: /usr/share/fonts/noto/NotoSansMono-Regular.ttf:0
          Features: ()
    bold: NotoSansMono-Bold: /usr/share/fonts/noto/NotoSansMono-Bold.ttf:0
          Features: ()
  italic: NotoSansMono-Regular: /usr/share/fonts/noto/NotoSansMono-Regular.ttf:0
          Features: ()
      bi: NotoSansMono-Bold: /usr/share/fonts/noto/NotoSansMono-Bold.ttf:0
          Features: ()
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/jonas/.local/etc/kitty/kitty.conf

Config options different from defaults:
wayland_enable_ime False

Important environment variables seen by the kitty process:
	PATH                                /home/jonas/.local/lib/wrappers:/home/jonas/.local/bin:/home/jonas/.local/lib/scripts:/home/jonas/.local/var/lib/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin
	LANG                                en_US.UTF-8
	EDITOR                              vim
	SHELL                               /bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-1
	USER                                jonas
	XCURSOR_SIZE                        24
	LC_TIME                             en_DK.UTF-8
	XDG_CACHE_HOME                      /home/jonas/.local/var/cache
	XDG_CONFIG_HOME                     /home/jonas/.local/etc
	XDG_CURRENT_DESKTOP                 sway
	XDG_DATA_HOME                       /home/jonas/.local/share
	XDG_LIB_HOME                        /home/jonas/.local/lib
	XDG_LOG_HOME                        /home/jonas/.local/var/log
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SEAT                            seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_ID                      1
	XDG_SESSION_TYPE                    wayland
	XDG_STATE_HOME                      /home/jonas/.local/var/lib
	XDG_VTNR                            1
```

**Additional context**
Even with `kitty --config NONE` the same problem appears. `wayland_enable_ime no` or `linux_display_backend x11` does not work neither together nor individually.

That's all probably not very helpful, so if I can provide any additional information (strace run, etc.) I'm happy to do so.

**Comment by jonasc** [comment] 2024-10-31 18:09
I also just tried to see if a fresh git build does any difference (using https://aur.archlinux.org/packages/kitty-git) and still the same.

**Comment by kovidgoyal** [comment] 2024-11-01 03:39
I highly doubt this has anything to do with kitty, most likely something
else on your system is broken. I cannot reproduce on my Arch system. If
you want to figure out what is causing it use the various debug flags
such as --debug-rendering and try building kitty with make
debug-event-loop that will show you if the kitty event loop is ticking
over continuously and possibly why.

Closing as cant reproduce and is likely system specific. But feel free
to update with more information.

**Closed by kovidgoyal** 2024-11-01 03:39 UTC
Labels: bug
