### ISSUE TITLE
Installer does not work

### ISSUE THREAD

**Issue by thenerdsuperuser** [kovidgoyal/kitty#1757] opened 2019-06-27 18:15 UTC
I am getting this output:

ImportError: /home/normalguy/.local/kitty.app/bin/../lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

Complete output: 

`Using python executable: /usr/local/bin/python3
Checking for latest release on GitHub...
Using previously downloaded kitty-0.14.2-x86_64.txz
Extracting tarball...
kitty successfully installed to /home/normalguy/.local/kitty.app
Use /home/normalguy/.local/kitty.app/bin/kitty to run kitty
Traceback (most recent call last):
  File "python3.7/runpy.py", line 280, in run_path
  File "python3.7/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 117, in <module>
  File "kitty/__main__.py", line 110, in main
  File "kitty/main.py", line 11, in <module>
    from .borders import load_borders_program
  File "kitty/borders.py", line 7, in <module>
    from .fast_data_types import (
ImportError: /home/normalguy/.local/kitty.app/bin/../lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates`

**Comment by Luflosi** [comment] 2019-06-27 19:20
Duplicate of #992. Also see #595.

**Closed** 2019-06-28 01:08 UTC

**Comment by catskul** [comment] 2019-08-30 20:35
Solution from #595 for convenience:
https://github.com/kovidgoyal/kitty/issues/595#issuecomment-504260295
> jberryman commented on Jun 20
> FWIW, on Debian stretch It looks like things are working after doing:
> 
>   * unpack the binary bundle from https://github.com/kovidgoyal/kitty/releases to ~/.local
>   * build harfbuzz from source (was very straightforward `./autogen.sh && ./configure && make`)
>   * copy the `libharfbuzz.so` you just built, overwriting `~/.local/lib/libharfbuzz.so.0`
