### ISSUE TITLE
In split layout mode, opening n splits in the same orientation (horizontal/vertical) should result in an n-way split, instead of a binary-split-tree-of-depth-n

### ISSUE THREAD

**Issue by andrey-mishchenko** [kovidgoyal/kitty#4212] opened 2021-11-08 22:31 UTC
**Is your feature request related to a problem? Please describe.**

If I am in split layout mode, and I split vertically 5 times, I get the following:

![image](https://user-images.githubusercontent.com/5308024/140828091-dc94bfad-638d-4e1f-8795-95f070885585.png)

**Describe the solution you'd like**

I think that it would be better if splitting vertically 5 times in a row resulted in an even 6-way split. (For example, this is the way Vim does it.) Similarly in the horizontal direction, and when splitting nested windows.

**Describe alternatives you've considered**

I can achieve an approximation of the layout I want manually with window-resize commands, which isn't a huge deal, although things generally won't end up exact:

![image](https://user-images.githubusercontent.com/5308024/140828447-bc198059-d029-4950-bdbd-add232965c26.png)

My bigger issue with this workaround is that I have a key bound to "reset layout" (similar to Vim's `<C-w>=` command) and it resets the layout back into the uneven-split configuration.

**Additional context**

Thanks for all the work you put into kitty!

**Comment by kovidgoyal** [comment] 2021-11-09 02:06
I dont see the point. If you want an even split use the horizontal/vertical layouts. If you want binary splitting use the splits. Having split behave like horizontal/vertical means you can no longer have splits like behavior. Also having splitting behavior depend on current layout state is "magic" behavior I am not very fond of. 

reset layout basically removes all resizing (which is implemented as biases in the layout), so that is behaving as designed.  What is your actual use case? i.e. what are you trying to implement?

**Comment by andrey-mishchenko** [comment] 2021-11-09 15:40
I use windows in a very dynamic way. I don't "set and forget" my layout and stick with it -- I am constantly spawning new windows, closing them, etc. So for me the splits layout was great, because it lets me spawn / delete / resize windows in a fine-grained and dynamic way.

Here are a couple of examples of layouts that I end up in a lot. Either of these could be implemented as its own kitty layout -- but again, I don't wind up in one of these and stick with it. I could easily find myself transitioning smoothly among these. And toggling layouts wouldn't really do the trick because it would be hard to control the destinations of the different processes running in the different windows.

In all of these cases, it would be great for a "reset" to give basically an even-ish split of screen real estate to the windows (at a given depth in the hierarchy, say) and then I am happy to do some adjustments manually (for example, the bottom windows occupying half the screen, and me having to make that bottom half node shorter).

![image](https://user-images.githubusercontent.com/5308024/140954897-96f12f24-a445-454c-91fc-4b84845c4adb.png)

![image](https://user-images.githubusercontent.com/5308024/140955551-98f53e52-2af7-4141-a931-8cb653dd0f88.png)

**Comment by kovidgoyal** [comment] 2021-11-09 15:45
You are welcome to submit a patch for a "re-balance" layout command that distributes space evenly. But reset is never going to do that, since reset means, restore the windows to the sizes they would have in the current layout without any individual resizing.

Or alternately add an option to the splits layout to behave as you would like, or write your own layout to do so.

If you need assistance with the coding feel free to ask and I will help. But given I have no use for this myself, its not something I want to spend time on.

**Comment by kovidgoyal** [comment] 2021-11-09 15:46
Closing as not something I think is particularly useful, but patches and/or more discussion are welcome.

**Closed by kovidgoyal** 2021-11-09 15:45 UTC
Labels: enhancement

**Comment by andrey-mishchenko** [comment] 2021-11-09 15:48
Fair enough -- I think a "rebalance" command would make sense. Maybe I'll find some time to look into coding it up.
