### ISSUE TITLE
on maximize/shrink the prompt adds extra prompt lines and loses position

### ISSUE THREAD

**Issue by bradlyatc** [kovidgoyal/kitty#283] opened 2018-01-12 15:24 UTC
seeing an issue where if I maximize the terminal and do some work then shrink, it will add an extra prompt line and the input position will change between different prompt lines that it outputs. I'll se if I can take some screen shots if need be. thanks

**Comment by kovidgoyal** [comment] 2018-01-12 15:28
duplicate of #242

**Closed by kovidgoyal** 2018-01-12 15:28 UTC
