### ISSUE TITLE
Ctrl/Alt+Numpad arrows does not work as expected

### ISSUE THREAD

**Issue by sergei-dyshel** [kovidgoyal/kitty#1213] opened 2018-12-08 13:15 UTC
When using numpad for arrow keys (num lock off) adding ctrl/alt modifiers does not change resulted key codes. I tried running with `--debug-keyboard` and it seems that the bug is inside `glfw`: when pressing `ctrl+left` (normal arrow) I see the following events:
```
Press scancode: 0x25 clean_sym: Control_L composed_sym: Control_L mods: none glfw_key: 341 (LEFT CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 341 native_code: 0xffe3 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Press scancode: 0x71 clean_sym: Left composed_sym: Left mods: ctrl glfw_key: 263 (LEFT) xkb_key: 65361 (Left)
on_key_input: glfw key: 263 native_code: 0xff51 action: PRESS mods: 0x2 text: '' state: 0 sent key to child
Release scancode: 0x71 clean_sym: Left mods: ctrl glfw_key: 263 (LEFT) xkb_key: 65361 (Left)
on_key_input: glfw key: 263 native_code: 0xff51 action: RELEASE mods: 0x2 text: '' state: 0 ignoring as keyboard mode does not allow release events
Release scancode: 0x25 clean_sym: Control_L mods: ctrl glfw_key: 341 (LEFT CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 341 native_code: 0xffe3 action: RELEASE mods: 0x2 text: '' state: 0 ignoring as keyboard mode does not allow release events
```

and when pressing `ctrl+kp_left` I see the following:
```
Press scancode: 0x25 clean_sym: Control_L composed_sym: Control_L mods: none glfw_key: 341 (LEFT CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 341 native_code: 0xffe3 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Press scancode: 0x53 clean_sym: KP_Left composed_sym: KP_Left mods: none glfw_key: 263 (LEFT) xkb_key: 65430 (KP_Left)
on_key_input: glfw key: 263 native_code: 0xff96 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Release scancode: 0x53 clean_sym: KP_Left mods: none glfw_key: 263 (LEFT) xkb_key: 65430 (KP_Left)
on_key_input: glfw key: 263 native_code: 0xff96 action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events
Release scancode: 0x25 clean_sym: Control_L mods: none glfw_key: 341 (LEFT CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 341 native_code: 0xffe3 action: RELEASE mods: 0x0 text: '' state: 0 ignoring as keyboard mode does not allow release events
```

Note `mods: 0x0` in second case. Does this mean `glfw` is not sending key event properly?

**Comment by sergei-dyshel** [comment] 2018-12-08 19:53
I've investigated this a little more and the problem seems to lie deeper than I thought: I'm observing this issue only when using a separate numpad but not when I'm using normal 104-key keyboard. So it could be than it my case X11 (or XKB) reports modifiers differently than expected by `glfw`. Generally I think this problem is solvable since many other applications I'm using handle numpad correctly (e.g. gnome-terminal).

**Comment by sergei-dyshel** [comment] 2018-12-08 21:14
Found the root cause of this behaviour: when I press a modifier key on main keyboard and then press a key on the numpad, there is `XkbMapNotify` event before numpad press which leads to nullifying `xkb->states.modifiers` in `glfw_xkb_compile_keymap`. Although I couldn't understand what the exact purpose of `MapNotify`, by the code alone it looks like GLFW does the right thing and it may be somehow related to X11 handling several keyboards.

So the question remains: what do other GUI programs (gnome-terminal, Chrome and virtually any GUI which uses Ctrl+Arrows to jump between words) do differently so that they handle it "right"?

**Comment by kovidgoyal** [comment] 2018-12-09 08:04
works for me on my X11 system, here is the output from --debug-keyboard

```
Press scancode: 0x25 clean_sym: Control_L composed_sym: Control_L mods: none glfw_key: 341 (LEFT CONTROL) xkb_key: 65507 (Control_L)
on_key_input: glfw key: 341 native_code: 0xffe3 action: PRESS mods: 0x0 text: '' state: 0 sent key to child
Press scancode: 0x55 clean_sym: KP_Right composed_sym: KP_Right mods: ctrl glfw_key: 262 (RIGHT) xkb_key: 65432 (KP_Right)
on_key_input: glfw key: 262 native_code: 0xff98 action: PRESS mods: 0x2 text: '' state: 0 sent key to child
```

Ctrl modifier is recognized when KP_Right is pressed. I'm guessing this is some artifact of your keyboard layout/any other programs you are using for re-mapping X11 keys. Given that I cannot reproduce, I'm going ot close this bug report. If you do figure out what is causing the issue, feel free to update and I will reconsider.

**Closed by kovidgoyal** 2018-12-09 08:04 UTC
