### ISSUE TITLE
Sincronize window inputs (same as tmux synchronize-panes)

### ISSUE THREAD

**Issue by rjcoelho** [kovidgoyal/kitty#2657] opened 2020-05-14 21:28 UTC
I use kitty windows to open a ssh for each server host need to input the same commands on multiple windows. Iterm2 also has same feature. But AFAIK kitty doesn't. I'm sure this was been asked before but a quick search on docs and here turned empty.

Thanks,
Rui

**Comment by ctrlcctrlv** [comment] 2020-05-15 00:10
This should be closed as a duplicate of #1569.

**Closed** 2020-05-15 01:44 UTC
