### ISSUE TITLE
Cannot read termcap database

### ISSUE THREAD

**Issue by sbeldekov** [kovidgoyal/kitty#310] opened 2018-02-05 18:39 UTC
I am not sure if this is an issue or not but I have the following output when 'brew upgrade'.
Other terminals are quiet.

$ brew upgrade
Cannot read termcap database;
using dumb terminal settings.

**Comment by MindTooth** [comment] 2018-02-05 22:27
Did just experience the same issue.

Believe it might be this commit: https://github.com/Homebrew/brew/commit/3a2e6b82fd008974c47b87a98c6c7bbf1dcdcea7#diff-aa6192b25b5254b9e0d4b95005b69a44

**Comment by kovidgoyal** [comment] 2018-02-06 02:30
Have you changed the value of TERM?

**Comment by kovidgoyal** [comment] 2018-02-06 02:39
And what does running the following two comamnd output:

```
env | grep TERM
infocmp
```

**Comment by sbeldekov** [comment] 2018-02-06 08:58
$ env | grep TERM                                                                                                                                                                                                                                                                                           
COLORTERM=truecolor
TERM=xterm-kitty
TERMINFO=/Applications/kitty.app/Contents/Frameworks/kitty/terminfo

$ infocmp
#   Reconstructed via infocmp from file: /Applications/kitty.app/Contents/Frameworks/kitty/terminfo/78/xterm-kitty
xterm-kitty|KovIdTTY,
    am, ccc, hs, km, mc5i, mir, msgr, npc, xenl,
    colors#256, cols#80, it#8, lines#24, pairs#32767,
    acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
    bel=^G, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
    clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
    csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
    cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
    cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
    cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
    dl=\E[%p1%dM, dl1=\E[M, dsl=\E]2;\007, ech=\E[%p1%dX,
    ed=\E[J, el=\E[K, el1=\E[1K, flash=\E[?5h$<100/>\E[?5l,
    fsl=^G, home=\E[H, hpa=\E[%i%p1%dG, ht=^I, hts=\EH,
    ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L, ind=^J,
    indn=\E[%p1%dS,
    initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
    kEND=\E[1;2F, kHOM=\E[1;2H, kLFT=\E[1;2D, kRIT=\E[1;2C,
    ka1=, ka3=, kbs=\177, kc1=, kc3=, kcbt=\E[Z, kcub1=\EOD,
    kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA, kdch1=\E[3~, kend=\EOF,
    kf1=\EOP, kf10=\E[21~, kf11=\E[23~, kf12=\E[24~, kf2=\EOQ,
    kf3=\EOR, kf4=\EOS, kf5=\E[15~, kf6=\E[17~, kf7=\E[18~,
    kf8=\E[19~, kf9=\E[20~, khlp=, khome=\EOH, kich1=\E[2~,
    kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
    kri=\E[1;2A, kund=, oc=\E]104\007, op=\E[39;49m, rc=\E8,
    rev=\E[7m, ri=\EM, rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B,
    rmam=\E[?7l, rmcup=\E[?1049l, rmir=\E[4l, rmkx=\E[?1l,
    rmso=\E[27m, rmul=\E[24m, rs1=\Ec, sc=\E7,
    setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
    setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
    sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
    sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
    smcup=\E[?1049h, smir=\E[4h, smkx=\E[?1h, smso=\E[7m,
    smul=\E[4m, tbc=\E[3g, tsl=\E]2;, vpa=\E[%i%p1%dd,

**Comment by kovidgoyal** [comment] 2018-02-06 09:02
According to that, terminfo is accessible, so I have no idea why brew is giving you that message. You'd have to ask it's maintainers, or more properly, the maintainers of whatever terminal UI library it uses.

**Comment by kovidgoyal** [comment] 2018-02-07 12:54
Closing, as far as I can see, this is not a bug in kitty.

**Closed by kovidgoyal** 2018-02-07 12:54 UTC

**Comment by MindTooth** [comment] 2018-02-07 14:20
Can this be of any use?  Sorry to post to a closed post.
[diff.txt](https://github.com/kovidgoyal/kitty/files/1703404/diff.txt)

**Comment by kovidgoyal** [comment] 2018-02-07 14:25
I dont see what use that would be. kitty is not xterm, it does not and must not have the same terminfo as xterm.

**Comment by neverfox** [comment] 2018-04-18 00:44
I just posted about this in #423. What seemed to solve it for me is `cp -r /Applications/kitty.app/Contents/Frameworks/kitty/terminfo .terminfo`. Perhaps it's worth reported this as an issue to homebrew.

**Comment by kovidgoyal** [comment] 2018-04-18 02:02
Yeah, as I said in https://github.com/kovidgoyal/kitty/issues/310#issuecomment-363355515 it should be reported to brew or more properly to the maintainers of whatever terminal UI library it uses.

**Comment by k010c1232** [comment] 2018-09-24 02:07
I got following error in the latest ver.

>>Cannot read termcap database;
>>using dumb terminal settings.

I think that it's because xterm-kitty doesn't exit on my PC.
I can't find xterm-kitty file on my Mac(/usr/share/terminfo/). Where can I get this file?

**Comment by kovidgoyal** [comment] 2018-09-24 02:09
env | grep TERMINFO

**Comment by k010c1232** [comment] 2018-09-24 10:59
Thank you so much. I confirmed, but the error was shown if TERM is xterm-kitty. Nothing error when I changed TERM to xterm-256color for run brew command.

**Comment by zoidbergwill** [comment] 2018-11-20 14:00
@k010c1232 have you tried `ln -s /Applications/kitty.app/Contents/Frameworks/kitty/terminfo ~/.terminfo`?

**Comment by k010c1232** [comment] 2018-11-20 16:04
> @k010c1232 have you tried `ln -s /Applications/kitty.app/Contents/Frameworks/kitty/terminfo ~/.terminfo`?

Thanks @zoidbergwill 
I tried, but I can't. Now I'm using Alacritty.

**Comment by jacwah** [comment] 2018-12-28 23:03
This was caused by Homebrew cleraing `$TERMINFO`. Fixed upstream: https://github.com/Homebrew/brew/pull/5445.

**Comment by k010c1232** [comment] 2019-01-05 13:03
> This was caused by Homebrew clearing `$TERMINFO`. Fixed upstream: [Homebrew/brew#5445](https://github.com/Homebrew/brew/pull/5445).

Cool! Do you know fixed ver when will release?

**Comment by lithammer** [comment] 2019-01-09 11:57
@k010c1232 Homebrew 1.9.0 has been released and includes the fix.

>The `TERMINFO` environment variable is passed through to Homebrew to enable support for some terminal emulators.

https://brew.sh/2019/01/09/homebrew-1.9.0/

**Comment by ipstone** [comment] 2019-11-01 21:39
as of 2019-11-01 , this issue sees still exist with my kitty on macosx ...

**Comment by ixzh** [comment] 2022-04-10 19:58
under /Application/kitty.app/Contents/Frameworks I don't have kitty/terminfo... only folder is Python.framework/.

**Comment by kovidgoyal** [comment] 2022-04-11 02:11
env | grep TERMINFO

**Comment by ixzh** [comment] 2022-04-12 02:23
> env | grep TERMINFO

Thanks. It worked!
