### ISSUE TITLE
Ncurses cannot read some legacy keys with keyboard protocol enabled

### ISSUE THREAD

**Issue by magiblot** [kovidgoyal/kitty#3465] opened 2021-04-09 23:08 UTC
**Describe the bug**
When enabling the "Disambiguate escape codes" mode of the keyboard protocol (#3248), some legacy functional keys can no longer be read by Ncurses applications.

**To Reproduce**
Build the following program: `c++ -o input_test input_test.cc -lncursesw`
<details>
<summary>Test program</summary>

```c++
#include <ncurses.h>
#include <stdio.h>
#include <locale.h>
#include <poll.h>

bool read_blocking(int &c)
{
    return (c = wgetch(stdscr)) != ERR;
}

bool read_nonblocking(int &c)
{
    nodelay(stdscr, TRUE);
    c = wgetch(stdscr);
    nodelay(stdscr, FALSE);
    return c != ERR;
}

int main()
{
    setlocale(LC_ALL, "");
    initscr();
    raw();
    meta(stdscr, TRUE);
    keypad(stdscr, TRUE);
    set_escdelay(10);
    nodelay(stdscr, FALSE);
    noecho();
    wrefresh(stdscr);
    fprintf(stderr, "Before \\x1B[>1u. Press a key:\r\n");
    int c;
    read_blocking(c);
    do {
        fprintf(stderr, "> %s%d <> (%s)\r\n", (c < 10 ? "00" : c < 100 ? "0" : ""), c, keyname(c));
    } while (read_nonblocking(c));
    fprintf(stderr, "\x1B[>1u");
    fprintf(stderr, "After \\x1B[>1u. Press a key:\r\n");
    read_blocking(c);
    do {
        fprintf(stderr, "> %s%d <> (%s)\r\n", (c < 10 ? "00" : c < 100 ? "0" : ""), c, keyname(c));
    } while (read_nonblocking(c));
    fprintf(stderr, "\x1B[<u");
    fprintf(stderr, "Press any key to exit...\r\n");
    read_blocking(c);
    endwin();
    return 0;
}
```
</details>

Then run it in latest Kitty (82d11b80ddf28a3a945ab689acaaa913dbd47f77 as of now) with `TERM=xterm-kitty`, and press the `Up` key twice:

```
Before \x1B[>1u. Press a key:
> 259 <> (KEY_UP)
After \x1B[>1u. Press a key:
> 027 <> (^[)
> 091 <> ([)
> 065 <> (A)
Press any key to exit...
```

**Expected behavior**
If I understand it right, the purpose of legacy encodings is to allow the user to do basic shell interaction if the application which enabled this mode exits without clearing it. But a simple Ncurses application like the one above is unable to read this escape sequence (`\E[A`).

`infocmp xterm-kitty` shows two escape sequences for the `Up` key: `cuu1=\E[A` and `kcuu1=\EOA`. It looks like Ncurses always looks for `kcuu1`, or at least is not interpreting `cuu1` as `KEY_UP`. So, is it Kitty's fault for not preserving the default encoding for these keys in the "Disambiguate escape codes" mode, or is it Ncurses's fault for not accepting `cuu1`? Or is it my fault for expecting this to work?

Thank you.

**Environment details**
```
kitty 0.19.3 (82d11b80dd) created by Kovid Goyal
Linux ArchLinux 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/magiblot/.config/kitty/kitty.conf
Running under: X11
```

**Comment by kovidgoyal** [comment] 2021-04-10 03:05
On Fri, Apr 09, 2021 at 04:08:58PM -0700, magiblot wrote:
> **Expected behavior**
> If I understand it right, the purpose of legacy encodings is to allow the user to do basic shell interaction if the application which enabled this mode exits without clearing it. But a simple Ncurses application like the one above is unable to read this escape sequence (`\E[A`).

Legacy encoding mode is without *any* progressive enhancement. As for
the application crash without restoring keys problem. The hope is that
the user will be able to type reset and enter at the shell prompt, which
does indeed work at the first level of progressive enhancement, but not
at every level of progressive enhancement.

Coming to your actual issue, the arrow keys will not work because
ncurses is using cursor key mode (smkx in terminfo parlance) instead of
normal mode (rmkx). In the keyboard protocol under progressive
enhancement, all keys are encoded in normal mode, to make encoding
consistent and easy to decode. And note I may have gotten smkx and rmkx
mixed up in the above, I can never remember which is which. 

The ideal solution to this is that ncurses recognize keys from both
modes, but the chances of ncurses ever doing something that sensible are
zero.

**Comment by kovidgoyal** [comment] 2021-04-10 05:36
CLosing but feel free to continue the discussion if something is not clear.

**Closed by kovidgoyal** 2021-04-10 05:36 UTC
Labels: bug

**Comment by dankamongmen** [comment] 2021-04-12 11:35
@magiblot, i cannot reproduce your output in `kitty` 0.19.3-1 as installed in Debian Unstable  with `TERM=xterm-kitty`:

```
Before \x1B[>1u. Press a key:
> 259 <> (KEY_UP)
After \x1B[>1u. Press a key:
> 259 <> (KEY_UP)
uPress any key to exit...
```

however, if i use the current tip, i get your same results:

```
Before \x1B[>1u. Press a key:
> 259 <> (KEY_UP)
After \x1B[>1u. Press a key:
> 027 <> (^[)
> 091 <> ([)
> 065 <> (A)
Press any key to exit...
```

so either (a) debian is patching kitty so that it works the way you expect, or (b) this change has been introduced since 0.19.3, or (c) some cosmic force is acting against us so that our experiments are adversarial =] i'm just reporting this in case this change in behavior is unexpected.

for whatever it's worth, `notcurses-input` (https://github.com/dankamongmen/notcurses/blob/master/src/input/input.cpp) shows up in both cases:

```
acs Special: [0x100002 (1048578)] 'up' 
I SHOVED SOME SHIT IN THE SHIT BOX  <------------- diagnostic added to confirm print                                             
acs Special: [0x100002 (1048578)] 'up' 
```

**Comment by kovidgoyal** [comment] 2021-04-12 11:45
0.19.3 doesnt have the new keboard protocol

**Comment by magiblot** [comment] 2021-04-12 13:08
> so either (a) debian is patching kitty so that it works the way you expect, or (b) this change has been introduced since 0.19.3, or (c) some cosmic force is acting against us so that our experiments are adversarial =] i'm just reporting this in case this change in behavior is unexpected.

I remember testing the new keyboard protocol a few weeks ago and not noticing this issue, so it may have been introduced not long ago. But Kitty actually has no obligation to respect the notion of keypad/normal mode when the new keyboard protocol is enabled, so I would not consider this issue a bug, although a terminfo-compatible behaviour could be useful.

> for whatever it's worth, `notcurses-input` (https://github.com/dankamongmen/notcurses/blob/master/src/input/input.cpp) shows up in both cases:

Yeah, in the end the most straightforward solution is for applications to use other libraries which overcome these issues or to parse escape sequences manually.

**Comment by dankamongmen** [comment] 2021-04-12 13:12
> I remember testing the new keyboard protocol a few weeks ago and not noticing this issue, so it may have been introduced not long ago. But Kitty actually has no obligation to respect the notion of keypad/normal mode when the new keyboard protocol is enabled, so I would not consider this issue a bug, although a terminfo-compatible behaviour could be useful.

of course; i just wanted to ensure the change was expected.

> Yeah, in the end the most straightforward solution is for applications to use other libraries which overcome these issues or to parse escape sequences manually.

i endorse this policy with both thumbs =].
