### ISSUE TITLE
Kitty eventually uses a lot of swap space

### ISSUE THREAD

**Issue by maksbotan** [kovidgoyal/kitty#159] opened 2017-10-27 10:38 UTC
Hi!

I've noticed this behavior several times. If I let kitty run for a long time (like several days with laptop goint to suspend every night) with 3-4 tabs permanently open, I see kitty using a lot of swap space. 

Direct impact of this is that I cannot go to hibernate, as there is not enough swap space to store the RAM state. If I close kitty, I can hibernate successfully.

You can check swap usage with this command:

```bash
for status in /proc/*/status; do awk '/(^Pid|Name|VmSwap)/ { stat[$1] = $2 } END { if (stat["VmSwap:"]) print stat["Pid:"], stat["Name:"], stat["VmSwap:"] }' ${status}; done | sort -k 3 -n
```

Values will be in kB, sorted by swap usage ascending.

When I will observe this once again, I'll attach my swap values.

Note that I did not change my scroll buffer length in `kitty.conf`. I've only set the font and colors in the config file.

**Comment by kovidgoyal** [comment] 2017-10-27 10:50
kitty does not use swap. swap is allocated by the kernel for processes when running out of RAM. Are you saying that kitty's memory usage climbs with time? If so, I cannot reproduce that, for example, currently on my system, in a kitty processes left open for several days with three child windows, total memory usage is under 120MB of RAM. Indeed, kitty is carefully designed to almost never allocate memory on the heap during normal usage. 

I do not use tabs in kitty however, so it is possible there is a memory leak there. Run kitty and keep an eye on the memory usage and see if it climbs continuously, which would indicate a memory leak.

**Comment by maksbotan** [comment] 2017-10-27 10:53
Yeah, I meant a memory leak, it's just manifested as high swap usage :)

Of course I'll monitor it this time.

**Comment by maksbotan** [comment] 2017-11-10 19:02
Hi again.
I've run into a situation where I can't go to hibernate because of insuffucient swap space again. Here's some info.

I'm running kitty built from master branch on this commit: aaf593d2df6e159e71aac393c29031ebe18ddc43
Running command to get most swap using PIDs gives this in the top (PID -- title -- swap usage in kB)

```
9683 copyq 21272
7826 chrome 21436
7853 chrome 28016
25133 bpython 32592
7555 chrome 42956
9126 Telegram 44548
9537 copyq 59924
9527 python 72188
```
```console
$ cat /proc/9527/status | grep Vm
VmPeak:   384100 kB
VmSize:   367816 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:     70224 kB
VmRSS:     18580 kB
VmData:   108820 kB
VmStk:       132 kB
VmExe:         4 kB
VmLib:     28252 kB
VmPTE:       568 kB
VmPMD:        12 kB
VmSwap:    70336 kB
```

Here's `pmap -x` report on Kitty:
http://bpaste.net/show/ceb0d943afb4

Right now kitty is running for three days already (with laptop being in suspend during the nights) and I have three tabs open, but sometimes I had more. One is constantly running `ncmpcpp`, others have bash sessions. I have only font and color settings in my `kitty.conf`.

I'm going to restart it now, so I won't be provide anything else this time, sorry.

By the way, I also noticed some strange behaviors with X selection clipboard (select and paste with mouse wheel). Sometimes I'm not able to paste in another program what I've selected in kitty and sometimes that other program just hangs for a while before pasting. Not sure if this is a kitty problem.

**Comment by kovidgoyal** [comment] 2017-11-10 23:56
Unless you are running glfw from master, copy/paste in kitty happens via the program xsel. As for your memory issues, you need to isolate some activity that causes a memory leak, otherwise given that I cannot reproduce it, there is not much I can do to help.

**Comment by kovidgoyal** [comment] 2017-11-29 03:13
Since I cannot reproduce this and no one else has reported it either, I am closing. Feel free to re-open if you have more information.

**Closed by kovidgoyal** 2017-11-29 03:13 UTC
