### ISSUE TITLE
Blank window on macOS 10.14

### ISSUE THREAD

**Issue by wizardfrag** [kovidgoyal/kitty#887] opened 2018-09-06 15:25 UTC
Hi,

I've installed kitty using the [bash script](https://sw.kovidgoyal.net/kitty/installer.sh), however once it started it presented me with a blank window as below:
![image 2018-09-06 16 22 20](https://user-images.githubusercontent.com/924911/45167410-0857b300-b1f1-11e8-8495-a77700eecb22.jpg)

Interacting with the terminal (such as by typing `say Hello world`) works, however nothing is output to the screen. I'm not sure if this is an issue with kitty or with macOS 10.14, but it would be nice to use this!

### Required info
kitty version: 0.12.0
macOS version: 10.14 Beta (18A384a)
kitty config: default as installed by bash script

**Comment by kovidgoyal** [comment] 2018-09-06 15:31
sorry, I dont have the resources to support beta OSes. I can tell you that kitty works fine with 10.13. 

Make sure that the text is not just invisible because the foreground color is the same as the background color. (You can drag witht he mouse to selelct which should test that).

**Comment by wizardfrag** [comment] 2018-09-06 15:42
That's fine, I understand that.

Is there any way I can try to debug this myself?

**Comment by kovidgoyal** [comment] 2018-09-06 15:43
As I said, the first step is to check if it si a color problem. Assuming it isn't run kitty from the command like with the --debug-gl flag and see if it reports any errors. Also check console.app for any error messages.

**Comment by wizardfrag** [comment] 2018-09-06 15:49
Ah I thought I'd mentioned that I tried selecting text... --debug-gl doesn't show anything, however moving/resizing the window around causes it to start rendering... I'll close this for now...

**Comment by kovidgoyal** [comment] 2018-09-13 01:54
See if the following patch helps:

```diff
diff --git a/kitty/child-monitor.c b/kitty/child-monitor.c
index 063baa0a..6a0b7bb1 100644
--- a/kitty/child-monitor.c
+++ b/kitty/child-monitor.c
@@ -769,6 +769,12 @@ static PyObject*
 main_loop(ChildMonitor *self, PyObject *a UNUSED) {
 #define main_loop_doc "The main thread loop"
     bool has_open_windows = true;
+#ifdef __APPLE__
+    if (global_state.has_pending_resizes) process_pending_resizes(now);
+    render(now);
+    wakeup_main_loop();
+    wait_for_events();
+#endif
 
     while (has_open_windows) {
         double now = monotonic();
```

**Comment by nthapaliya** [comment] 2018-09-13 04:39
I tried the patch. It doesn't compile.

**Comment by wizardfrag** [comment] 2018-09-13 14:14
I've gotten it to compile by adding `double now = monotonic()` after the `#ifdef` and compiling using `CFLAGS=-Wno-error make` however it still doesn't seem to render...

Without the CFLAGS it complains that a lot of the calls from glfw are deprecated... I can provide logs if necessary?

**Comment by kovidgoyal** [comment] 2018-09-13 14:20
Well that was just a shot in the dark. Apple has deprecated OpenGL so that's not a surprise.

**Comment by kovidgoyal** [comment] 2018-09-24 23:39
Well now that mojave has been released officially, I am re-opening. Sadly I wont have access o my mac for another day or two, so I dont know if the issue is still present.

**Comment by wy15** [comment] 2018-09-25 02:13
The issue is still present in the release.

**Comment by kovidgoyal** [comment] 2018-09-25 02:45
Well, I will look into figuring out what apple broke in a few days when I have access to my mac again

**Comment by kovidgoyal** [comment] 2018-09-25 05:37
In the meantime, for anybody that wants to experiment themselves, since we know that a resize causes rendering to start behaving normally, you just need to see what happens in the resize code path and do that once at startup. The relevant functions are framebuffer_size_callback and update_os_window_viewport

**Comment by erf** [comment] 2018-09-25 20:31
it seem to work as normal if `background_opacity` is set to less than 1.

**Comment by net** [comment] 2018-09-25 20:38
Possibly related: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=31904

**Comment by d53dave** [comment] 2018-09-26 10:20
> it seem to work as normal if `background_opacity` is set to less than 1.

I have just tried this but it didn't fix the issue for me.

Also possibly related: if I try to start it from the command line, I get the following error twice:

```
[269 12:19:21.314076] [PARSE ERROR] Unknown OSC code: 7
```

**Comment by kovidgoyal** [comment] 2018-09-26 13:39
An update. Either moving or resizing the window will cause it to draw. I looked into what happens on a move and basically commenting out the line:

```cocoa
[window->context.nsgl.object update]
```

in windowDidMove causes moving to not cause correct rendering. So obviously we now need to call update ont he context object. The problem is I am not sure where is a good place to do that. Doing it in the constructor or the call to showwindow does not work. So I suppose it will simply have to be called once per window on first render. Which will need a new native call api in glfw, sigh.

**Closed** 2018-09-26 14:13 UTC

**Comment by jameswritescode** [comment] 2018-09-28 19:15
Will there be a release with this fix soon / documented way to generate a new dmg from source?

**Comment by kovidgoyal** [comment] 2018-09-29 02:34
there already is a documented way to build the app from source https://sw.kovidgoyal.net/kitty/build.html

**Comment by kovidgoyal** [comment] 2018-09-29 02:35
https://sw.kovidgoyal.net/kitty/faq.html#how-do-i-build-kitty-app-on-macos

**Comment by elnormous** [comment] 2018-10-22 12:46
I spent some time debugging how NSOpenGLView works and why it has no problems with rendering immediately. I disassembled the NSOpenGLView and found out that it is creating a custom layer (class: _NSOpenGLViewBackingLayer). I tried to create the same layer and it worked. I start to investigate the code of the _NSOpenGLViewBackingLayer and found out that it does some stuff in the display method and it is a subclass of CALayer. I tried to copy the functionality of the _NSOpenGLViewBackingLayer, but with no success. Then I tried to simply create an instance of CALayer and it worked!
PS. One call to [NSOpenGLContext update] must be made (it is done in [NSOpenGLView openGLContext] method.

Here is the fix (for my engine), it should be easy to integrate the same code in Kitty:
https://github.com/elnormous/ouzel/commit/eaa566abbee8a2c6e2e07bf4ecfb51960ba5debb

PS. My workaround is more elegant than updating the NSOpenGLContext two times because mine starts rendering immediately (from the first frame) instead of two frames later.

**Comment by kovidgoyal** [comment] 2018-10-22 13:55
changing the NSView into a layer backed view is likely to have performance implications or other side-effects, seem safer to just call NSOpenGLContext update a couple of times at startup.

**Comment by elnormous** [comment] 2018-10-22 22:29
Yes, I agree. I did some more debugging and disassembling and came to a solution. I posted the results here: https://stackoverflow.com/questions/52938516/opengl-not-rendering-on-macos-mojave/52938517#52938517
Basically, you have to update the NSOpenGLContext in NSView's setLayer: method because OpenGL is rendered in a layer on Mojave even if you explicitly disable it by setting wantsLayer to NO.
Here is my commit to the Ouzel engine: https://github.com/elnormous/ouzel/commit/7e708636189d970bad6b013ecd5375cfe693f3f3

**Comment by kovidgoyal** [comment] 2018-10-23 03:41
yeah that works well

**Comment by Tagar** [comment] 2019-11-04 22:25
I have similar issue not only on macOS, but on Windows as well.
Blank screen first, and when window is resized, it renders fine again.

**Comment by Luflosi** [comment] 2019-11-04 22:39
kitty does not run on Windows. I think you're talking about a different project, possibly KiTTY.

**Comment by Tagar** [comment] 2019-11-04 22:42
@Luflosi you're right, created https://github.com/cyd01/KiTTY/issues/67 instead 
sorry for the confusion
