### ISSUE TITLE
Black bars on top and bottom of terminal

### ISSUE THREAD

**Issue by MrCappuccino** [kovidgoyal/kitty#1334] opened 2019-01-25 15:18 UTC
In the newest version of kitty (I checked, 13.2-1 doesn't have this issue) has black bars, or padding at the top and bottom of the terminal.
I have tested this on a laptop with an Nvidia Quadro and a desktop with an AMD r9 390
Update: was able to capture the issue: [left-new, right-old](https://i.imgur.com/9QnbogN.png)
I am using i3, the issue persists in full screen mode as well.

**Comment by kovidgoyal** [comment] 2019-01-25 17:14
That will happen if the number of cells per row/column in the window is not an exact
divisor of the window width/height respectively. If you dont want to see
the black bars, set the terminal background color to the same background color as
your color scheme for the text, and the bars will be invisible as they
will be the same color as the rest of the window.

**Closed by kovidgoyal** 2019-01-25 17:14 UTC

**Comment by Luflosi** [comment] 2019-01-25 17:18
But why is it happening only now and didn't happen before? Here is the diff between v0.13.2 and 0.13.3: https://github.com/kovidgoyal/kitty/compare/v0.13.2...v0.13.3. Could it be related to #1291?

**Comment by MrCappuccino** [comment] 2019-01-25 17:23
Yeah, why did it break only on the recent version?

**Comment by kovidgoyal** [comment] 2019-01-25 17:24
I dont think so since from the OP's screenshot, he isn't using
background_opacity, which means it is 1.0 so that commit should have no
effect. We will need more information about his setup to figure out why
it is happening, but certainly as far as I know, it has always been the
case that you will get bars in the kitty background color when the
window size is not an exact multiple of cell size, nothing new in that.

**Comment by MrCappuccino** [comment] 2019-01-25 17:25
Like I described in the issue report, it's only occuring on the latest version 13.3-1.

**Comment by MrCappuccino** [comment] 2019-01-25 17:26
Upon further testing, in the newer version it is the case that resizing affects this padding, not in the older 13.2-1 version.

**Comment by kovidgoyal** [comment] 2019-01-25 17:26
What does resizing affects this padding mean? How does it affect it?

**Comment by Luflosi** [comment] 2019-01-25 17:44
Just to be clear: you're having this issue with the latest version 0.13.3 but not with the prior version 0.13.2, right? I'm a little bit confused by the way you wrote the version numbers.

**Comment by MrCappuccino** [comment] 2019-01-25 17:52
I'm having the issues on kitty-0.13.3-1-x86_64.pkg.tar.xz, no issues on kitty-0.13.2-1-x86_64.pkg.tar.xz (Arch packages).

**Comment by MrCappuccino** [comment] 2019-01-25 17:58
This issue should not be closed, since the suggested solution doesn't work, my background color is that of my theme @kovidgoyal.

**Comment by maximbaz** [comment] 2019-01-25 18:33
@MrCappuccino can you provide your kitty.conf and check if you can reproduce with mine? I'm unable to repro with `kitty-0.13.3`, being also on Arch with i3wm.

https://github.com/maximbaz/dotfiles/blob/master/.config/kitty/kitty.conf

**Comment by Luflosi** [comment] 2019-01-25 18:34
Could you please try to build kitty from source? Then you could use git bisect to figure out exactly which commit caused the change, that would help us a lot.

**Comment by Luflosi** [comment] 2019-01-25 18:35
Try @maximbaz's suggestion first.

**Comment by kovidgoyal** [comment] 2019-01-26 05:42
> I have also set my background color to that of my scheme.
> [1st size](https://i.imgur.com/7ZBzopV.png)
> [2nd size](https://i.imgur.com/0K5juG4.png)

As I suspected, that is simply the leftover borders when window size is not a multiple of cell size. The question is why is it being rendered in a different color from the text background color.

**Comment by kovidgoyal** [comment] 2019-01-26 12:31
How would background_opacity even work on X11 without a compositor running? @MrCappuccino remove that from yout kitty.conf (it is useless anyway) and you should be fine.

If someone cant figure out how to reproduce it, I will be happy to take a look at fixing it.

**Comment by MrCappuccino** [comment] 2019-01-26 13:38
Okay, so I was just testing compton out and seeing what would happen, with compton, the issue dissapears, without it, it persists.

**Comment by kovidgoyal** [comment] 2019-01-26 17:52
So dont use backround_opacity unless you have working semi-transparent windows, otherwise, shit will break :)

**Comment by Luflosi** [comment] 2019-01-26 21:30
It's still weird, that the padding behaves differently than the rest of the window. They should look exactly the same. In this case they should both have a gray-ish background.

**Comment by kovidgoyal** [comment] 2019-01-27 02:47
It's not that weird they are drawn by different shaders, probably one shader is more affected by background_opacity being a no-op than the other.

**Comment by jaydu1995** [comment] 2020-07-02 20:06
I am having the same issue: https://i.imgur.com/z8BNbRC.png

**Comment by Luflosi** [comment] 2020-07-02 20:10
What you're seeing is padding or margin. Either [change the background color](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.foreground) or choose the [initial window size](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.remember_window_size) so that there are no paddings or margins by using the "c" suffix.

**Comment by jaydu1995** [comment] 2020-07-02 20:48
> What you're seeing is padding or margin. Either [change the background color](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.foreground) or choose the [initial window size](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.remember_window_size) so that there are no paddings or margins by using the "c" suffix.

Thank you for helping.. I'll just change my BG color then!
