### ISSUE TITLE
One-pixel gap between cells crossed by ligatures

### ISSUE THREAD

**Issue by jacobhenn** [kovidgoyal/kitty#2949] opened 2020-09-01 21:07 UTC
In most of my Fira Code ligatures (exceptions are `==`, `++`, and `===`, and probably some others), there is consistently (regardless of zoom level) a one-pixel gap between the first two characters of the ligature, but not between any of the others.
![2020-09-01-13:54:46_scrot](https://user-images.githubusercontent.com/60454550/91905755-dcdef600-ec5b-11ea-8750-3044bd9e0e83.png)

**Comment by Luflosi** [comment] 2020-09-01 21:44
Dup of #2910, see tonsky/FiraCode#1081.

**Comment by Luflosi** [comment] 2020-09-01 21:47
Also a duplicate of #2775 and #2695.

**Closed** 2020-09-02 02:27 UTC
