### ISSUE TITLE
Crash when dragging files over kitty on Linux (xorg)

### ISSUE THREAD

**Issue by wallace11** [kovidgoyal/kitty#2540] opened 2020-04-13 14:39 UTC
I'm using [dragon](https://github.com/mwh/dragon) for drag and drop operations from the terminal.
When hovering with a dragged file on a kitty window, kitty crashes with the following error:
```
X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  17 (X_GetAtomName)
  Atom id in failed request:  0x0
  Serial number of failed request:  704
  Current serial number in output stream:  705
```

I checked back and this bug was introduced with v0.17.0.

I'm using Arch Linux with xorg server v1.20.8.

Please let me know if there's any additional information you need me to provide in order to solve this.

**Comment by Luflosi** [comment] 2020-04-13 14:46
Duplicate of #2505. This is fixed in the latest master.

**Closed** 2020-04-13 14:52 UTC
