### ISSUE TITLE
Characters mirrored or missing - terminal unusable

### ISSUE THREAD

**Issue by Gobbel2000** [kovidgoyal/kitty#1568] opened 2019-04-25 16:50 UTC
System info:
OS: Manjaro + i3
kitty version 0.13.3, same behaviour when building from source.
default config, fresh install

[This](https://imgur.com/a/SozaALU) is how the terminal looks for me. Most characters are mirrored or completely missing. Which ones are affected changes slowly. Other OpenGL applications run fine. I am using Intel integrated graphics, this is the output of --debug-gl: 
```GL version string: '4.2 (Core Profile) Mesa 19.0.2' Detected version: 4.2```

**Comment by Luflosi** [comment] 2019-04-25 17:09
Duplicate of #1484. Downgrade mesa to 18.3.4 or wait for mesa 19.0.3.

**Closed** 2019-04-25 19:33 UTC
