### ISSUE TITLE
New OS window always launched in built-in retina display (macOS)

### ISSUE THREAD

**Issue by lazywei** [kovidgoyal/kitty#5820] opened 2022-12-26 08:15 UTC
**Describe the bug**
When I open `Kitty.app` from system launcher, or when I create a new OS window by `cmd+t` or by running `kitty` from command line, the new OS window is always opened at the built-in retina display on my MacBook.

I have two monitors and it seems regardless which monitor is active / primary, it always launch on the built-in retina display.

I saw on the menu bar there is an option to move the OS window to different monitor, I wonder if there is any config or mappings I might miss that can resolve this issue?

**To Reproduce**
1. Open `Kitty.app` via system launcher or from terminal

**Environment details**
```
kitty 0.26.5 () created by Kovid Goyal
Darwin cwc-mbp-ed 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
ProductName:            macOS ProductVersion:           13.1 BuildVersion:              22C65
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/zsh
Loaded config files:
  /Users/cwchang/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style (True, False)
editor                /opt/homebrew/bin/nvim
font_size             22.0
tab_bar_min_tabs      1
tab_fade              (0.25, 1.0)
tab_title_template    {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}
Added shortcuts:
        kitty_mod+d →  launch --hold --stdin-source=@screen_scrollback ~/.config/kitty/pager.sh
Changed shortcuts:
        cmd+t →  new_tab_with_cwd
Colors:
        background            #001e26   
        color0                #002731   
        color1                #d01b24   
        color10               #50ee84   
        color11               #b17e28   
        color12               #178dc7   
        color13               #e14d8e   
        color14               #00b29e   
        color15               #fcf4dc   
        color2                #6bbe6c   
        color3                #a57705   
        color4                #2075c7   
        color5                #c61b6e   
        color6                #259185   
        color7                #e9e2cb   
        color8                #006388   
        color9                #f4153b   
        cursor                #f34a00   
        foreground            #9bc1c2   
        selection_background  #003747   
        selection_foreground  #001e26   

Important environment variables seen by the kitty process:
        PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
        LANG                                en_US.UTF-8
        SHELL                               /opt/homebrew/bin/zsh
```

**Additional context**
This can be reproduced with `kitty --config NONE` on my laptop.

Thanks

**Comment by page-down** [comment] 2022-12-26 10:12
This issue has been on my list for a long time.

A question similar to this: "The kitty window is always created on the left side of the screen" is also frequently asked.

Currently after creating a window, kitty does not move the window coordinates, and macOS does not arrange the position for the window by default.
This results in the OS window will always be displayed in a fixed position (leftward) on a certain screen (main screen).

This requires calculating the screen coordinates and placing them in the right place each time a new OS window is created (e.g. cascading over the current window without covering the title bar).
There may be a way to leverage existing framework functionality without having to do the work that should be done by the window manager itself, but I'm not aware of that.

This should be fixed together with the other long-standing issue "restore window position on macOS".

**Comment by kovidgoyal** [comment] 2022-12-26 10:14
I'm afraid positioning of kitty windows is in the control of the OS not
kitty. I dont use macOS so I cant tell you how to control window
positioning there, but there should be plenty of resources on it online.
One thing to check is that you dont have secure keyboar dentry enabled
as that basically breaks tons of things.

**Closed by kovidgoyal** 2022-12-26 10:14 UTC
Labels: bug

**Comment by page-down** [comment] 2022-12-26 10:18
> ... positioning of kitty windows is in the control of the OS ...

I think in kitty it might be necessary to at least have to ask the system to do this, but I haven't found it yet.

Maybe that's why kitty can't open a new window in the currently active desktop space (monitor), while other applications don't have this problem.

**Comment by kovidgoyal** [comment] 2022-12-26 10:44
On Mon, Dec 26, 2022 at 02:18:13AM -0800, page-down wrote:
> > ... positioning of kitty windows is in the control of the OS ...
> 
> I think in kitty it might be necessary to at least have to ask the system to do this, but I haven't found it yet.

I know of no Cocoa API to do that, and if you open multiple kitty OS
windows, you see the OS placing subsequent ones based on a well defined
algorithm, so its not like Cocoa is just randomnly choosing window
positions.

**Comment by page-down** [comment] 2022-12-26 11:44
> ... the OS placing subsequent ones based on a well defined algorithm ...

This is explicitly asked to be done by the system framework in kitty (glfw that comes with, `glfw/cocoa_window.m`).

```objc
_glfw.ns.cascadePoint =
    NSPointToCGPoint([window->ns.object cascadeTopLeftFromPoint:
                      NSPointFromCGPoint(_glfw.ns.cascadePoint)]);
```

Regardless of the initial window coordinates, at least "create window on current screen" should be possible to be asked.

Maybe it's some API similar to the one below.
https://developer.apple.com/documentation/appkit/nswindow/1419755-initwithcontentrect

```text
- (instancetype)initWithContentRect:...
                             screen:(NSScreen *)screen;

screen
Specifies the screen on which the window is positioned.
The content rectangle is positioned relative to the bottom-left corner of screen.
When nil, the content rectangle is positioned relative to (0, 0), which is the origin of the primary screen.
```

**Comment by page-down** [comment] 2022-12-26 12:32
Oh, I think I have already tracked down the cause of the problem.
Each time a window is created the previous shifted position is used and the window position is explicitly requested to be changed.
So `initWithContentRect: ... screen:(NSScreen *)screen` will not work.

This also causes `[(NSWindow*) window->ns.object center]` not to work in the expected form:
The original intent of the code was to have the first window of the application in the center of the current active screen, and then move the position with each next new window.

(Although not yet implemented in the code to restore the last used kitty window position)

Then the next step is to fix and test accordingly.
