### ISSUE TITLE
Recognize local paths as urls

### ISSUE THREAD

**Issue by ilyakooo0** [kovidgoyal/kitty#2646] opened 2020-05-11 17:21 UTC
iTerm allows you to click on local paths to open files and folders. 

This can be very useful when compiling something -- you can go straight to the file and line where a compilation error occurred.

Example:

```
/Users/iko/Developer/project/File.hs:279:1
```

**Comment by Luflosi** [comment] 2020-05-11 17:24
Duplicate of #977. I recommend using the hints kitten for this, as mentioned in the issue.

**Closed** 2020-05-12 02:35 UTC
