### ISSUE TITLE
Kitty's Right Click to Add to Selection Doesn't Work if Current Selection Scrolls Off Screen

### ISSUE THREAD

**Issue by feoh** [kovidgoyal/kitty#1345] opened 2019-01-29 15:27 UTC
The workflow I use in my day job involves selecting massive blocks of output, copying them, and pasting them into another application (usually a web browser.)

I'd like to be able to start selecting text, scroll several screen's worth of text down, and use the right click to select the entire block of text.

Or something similar.

Steps to Reproduce:

Open a Kitty window and cat a very large file. Now scroll to the top, select a block of text, and then scroll all the way to the bottom. Right click to add to selection won't work unless you scroll back to your original selection and augment that selection one screen's worth at a time.

**Comment by martinetd** [comment] 2019-01-29 16:31
Hmm, was about to say it works for me, but it looks like it's something in my tree.

Please try #1007 and see if it works for you as well.


Someone else commented in another slightly related issue last week and I've -finally- resumed work on it yesterday, I have a few more off-by-one issues I need to fix and some code cleanup then will have something I'm happy with to finally offer this PR for closing, but meanwhile it should already be mostly useable (the PR itself shouldn't have off by ones but iirc there were some issues left which is why it was left open until I'm done with overhaul)

**Comment by feoh** [comment] 2019-01-29 16:37
Holy smoke the OSX build instructions even look achievable by mere humans! Will definitely try this sometime this week.  Thanks a bunch!

**Comment by maximbaz** [comment] 2019-01-29 18:23
Yes @martinetd, the issue doesn't reproduce in your branch 😉

**Comment by feoh** [comment] 2019-01-29 19:18
Just built this locally and it works beautifully! Thank you very much can't wait to see this get merged to mainline :)

**Comment by kovidgoyal** [comment] 2019-01-30 03:42
closing this in favor of #1007

**Closed by kovidgoyal** 2019-01-30 03:42 UTC
