### ISSUE TITLE
Faulty text rendering at the last line of the terminal in tmux

### ISSUE THREAD

**Issue by nochiel** [kovidgoyal/kitty#76] opened 2017-05-16 20:12 UTC
Steps:
1. `mkdir /tmp/tmp && cd /tmp/tmp`
2. `for i in {1..100}; do touch ${i}.txt; done`
3. `ls -C1; ls -C1; ls -C1`  # to completely fill the visible terminal with listed files.
4. Notice that the second last line of `ls` output contains the text from the previous prompt.
5. Resize the X window (e.g. by maximizing/restoring).
6. Notice that the listing is now rendered correctly.

![kitty-0 2 3 -tmux-2 4-text-render-bug](https://cloud.githubusercontent.com/assets/284914/26126071/f2a85ba4-3a8c-11e7-84b0-c5016a4b37b0.png)

**Comment by kovidgoyal** [comment] 2017-05-17 00:39
Can you attach a dump of the problem bytes. Run kitty with

kitty --dump-bytes dump.bin tmux

reproduce the problem, then post dump.bin

Note you can generate a screen full of out more easily with something like

yes | head -n 100

**Comment by kovidgoyal** [comment] 2017-05-17 05:11
Also update to version 0.2.4, which I just released with a couple of bug fixes that may be relevant.

**Comment by nochiel** [comment] 2017-05-17 12:33
> Also update to version 0.2.4

Done.

> Can you attach a dump of the problem bytes.

[kitty-0.2.4-dump.bin](https://drive.google.com/open?id=0By5XNHEDzGd5d2FCRkNfNWZxd00)

**Comment by kovidgoyal** [comment] 2017-05-17 16:00
That dump file includes the tmux clearscreen + exit so it's useless. Run tmux reproduce the problem, then, without doing anything else copy the dump file out. 

Also what version of tmux are you running? From eyeballing that dump file it looks like it is incorrectly echoing back the send device attributes response. tmux 2.4 on my system does not do that.

**Comment by nochiel** [comment] 2017-05-18 17:39
> Also what version of tmux are you running? From eyeballing that dump file it looks like it is incorrectly echoing back the send device attributes response. tmux 2.4 on my system does not do that.

- tmux: 2.4.
- Linux  4.10.13-1-ARCH 
- x86_64 GNU/Linux

> That dump file includes the tmux clearscreen + exit so it's useless. Run tmux reproduce the problem, then, without doing anything else copy the dump file out.

Okay. (I'll get it right eventually if this one is still faulty.)
[kitty-0.2.4-tmux-2.4-dump.bin](https://drive.google.com/open?id=0By5XNHEDzGd5WHNDOV9VNHVSWDA)

**Comment by kovidgoyal** [comment] 2017-05-19 00:55
That's much better, I'll take a look at it when I have a moment. It basically looks like a bug in handling some line erase command tmux uses.

**Comment by nochiel** [comment] 2017-05-19 10:52
> It basically looks like a bug in handling some line erase command tmux uses.

Thank you, @kovidgoyal.

**Closed** 2017-05-19 13:55 UTC
