### ISSUE TITLE
Custom character spacing?

### ISSUE THREAD

**Issue by wezzynl** [kovidgoyal/kitty#42] opened 2017-01-23 22:01 UTC
It would be a very nice readability enhancement if one could adjust the horizontal and vertical character spacing. Being able to configure the spacing between characters and lines to something a little bit tighter on horizontal axis and a little bit less tight on vertical axis would make text a lot more readable. I feel like there's some extra space between the characters the way they are rendered now?

**Comment by kovidgoyal** [comment] 2017-01-24 02:06
Assuming you are on OS X, the spacing comes from the metrics of the font, see set_font_family() in core_text.py and also cell_size() in core_text.m

While it is certainly possible to add a config option to customize the cell size by adding a delta to it, I'd rather not do that, since the delta would have to be font specific and so rather fragile. It would be better to just get the cell size calculation right, based on the font metrics. What font are you using? Unfortunately, since I cant get kitty to render  text on my ancient OS X machine, it is hard for me to debug this.

**Comment by kovidgoyal** [comment] 2017-01-24 02:21
At least for height, probably should do this: https://stackoverflow.com/questions/5511830/how-does-line-spacing-work-in-core-text-and-why-is-it-different-from-nslayoutm

**Comment by kovidgoyal** [comment] 2017-01-24 02:36
Quoting from the Apple docs https://developer.apple.com/library/content/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/TypoFeatures/TextSystemFeatures.html

```
By default, in horizontal text, typesetters place glyphs side-by-side using the advance width, resulting in a standard interglyph space. However, in some combinations, text is made more readable by kerning, which is shrinking or stretching the space between two glyphs.
```

So it looks like the horizontal size calculation is correct, unless there is some undocumented adjustment required for it, only way to find that out would be to go look in iTerm or iTerm2's source code, I suppose.

**Comment by wezzynl** [comment] 2017-01-24 19:53
Thanks for looking into this and I think you are correct. I just checked my iTerm settings and long ago I seem to have tweaked horizontal spacing. I do feel it's much more readable (for my font at least: Menlo Regular for Powerline at 12pt) that way. That I'm used to the font this way probably also comes into play.

Not sure if allowing to customize it would be fragile. Yes, it's a per font setting though it's a specific choice to tweak those values (even though I had actually forgot that I did that :) ) - seems like iTerm also keeps the settings when changing font. So I think they assume that a user knows that they changed it, it's also a GUI where the spacing is combined with picking a font so that might make it clearer that you changed it when you would go and pick a different font later on.

See the attached image for a comparison between rendering with the spacing tweaked (in iTerm, on the left) and how it renders with the defaults (in kitty, on the right).

<img width="1195" alt="screen shot 2017-01-24 at 20 51 07" src="https://cloud.githubusercontent.com/assets/5656741/22264082/15bef878-e277-11e6-8a25-5b3f7803e1df.png">

If I can find some time I might start fiddling around with cell sizes and rendering to see if I can get something going.

**Comment by wezzynl** [comment] 2017-01-24 20:15
Btw. Here's a screenshot from a small excerpt of the text copied into Font Book. This is how macOS Sierra renders the font. Seems like it is a lot tighter than kitty, also the underscores touch.

<img width="727" alt="screen shot 2017-01-24 at 21 12 37" src="https://cloud.githubusercontent.com/assets/5656741/22264901/185525dc-e27a-11e6-8413-2454d46bd594.png">

**Comment by kovidgoyal** [comment] 2017-01-25 02:09
One alternative width calculation would be to just use the width of the underscore rather than the width of the widest char in the 32-128 range. That would guarantee that underscores touch, however, it might mean that some chars are cut-off. I really should find the time to look into how other terminals do it.

**Comment by kovidgoyal** [comment] 2017-01-25 03:23
On default settings, for Menlo, underscores dont touch in iTerm. I think the best appraoch would be to have a config option

```
# Control how the width of character cells is calculated. The two possibile algorithms are advance, which uses the advance widths from the font, or underscore, which uses the width of the underscore from the font. The underscore option results in narrower cells for most fonts with consecutive underscores forming an unbroken line.

cell_width_algorithm advance
```

**Comment by kovidgoyal** [comment] 2017-01-25 04:58
I looked into implementing cell width adjustment, and it is pretty difficult to do in linux because of the way the freetext api works. Essentially, you dont provide it a cell size to render into, instead you just set a point size and freetype gives you a rendered bitmap that may or may not be larger than the cell size and may have actual content starting anywhere including the left edge. So trimming margins of it is prett hard to get right.

With CoreText one just provides both pt size and cell size and the engine presumably does whatever it feels is the "right" thinkg to do when the cell is too small for the glyph -- I assume it cuts off part of the glyph.

**Comment by wezzynl** [comment] 2017-01-25 20:16
Thanks again for looking into it. Seems like this needs some more thought. I would have expected a monospaced (also known as fixed-width) font to always render correctly inside a square. The whole idea is to have rows of characters align exactly with a different row, meaning width and height need to be a fixed value at a certain point size for all characters.

Seems like the problem is knowing the exact max width/height of a monospace font at a certain point size. Found this in the core text docs though:

```
func CTFontGetBoundingBox(_ font: CTFont) -> CGRect
Returns: The design bounding box of the font, which is the rectangle defined by xMin, yMin, xMax, and yMax values for the font. Returns null on error.
```
That should be the cell size I guess? I'll try and fiddle with it. 

I'm not sure if freetype has something similar but I'd say the same goes there, monospace is fixed-width so there must be a max width/height somewhere.

**Comment by wezzynl** [comment] 2017-01-25 22:25
Ah, Bounding Box for fonts is something different than what I thought Bounding Box was :) I think I first need to read up on fonts a bit more :)

**Comment by kovidgoyal** [comment] 2017-01-26 02:35
Monospace doesn't mean what one would think it means. Not to mention that with modern rendering there are all sorts of other issues. Monospacing usually only applies to a small subset of all characters. To render unicode characters one typically needs more than a single font, then there are italic/bold fonts which may or may not have the same metrics. The design metrics of a font are advisory, they do not actually guarantee that all glyphs will fit into the specified box. Then there are complications from antialiasing, which can cause bleed out over the edges. And finally, with unicode combinig characters multiple characters might be drawn intoa  single glyph. 

Finally, knowing the bounding box of a font is not very useful. Apart from the above issues, the problem is also that even if you know the bounding box, what do you do if the bounding box for a particular glyph is larger than your character call size. The options are 

1) Truncate part of the character
2) Resize the character
3) Bleed into neighboring cells

(3) is not possible because of the way kitty works. (2) looks bad because resizing the character changes its vertical height as well, so it looks out of place. (1) is probably least bad, but the question then becomes, what to cut out? And as I said FreeType does not have any API that I could find to help with answering that question. And CoreText makes that decision internally, you have no input into what it decides.

**Comment by kovidgoyal** [comment] 2017-04-22 06:04
Closing, for reasons outlined in previous post.

**Closed by kovidgoyal** 2017-04-22 06:04 UTC

**Comment by awalgarg** [comment] 2017-12-25 16:26
@kovidgoyal Is the above still valid? Looking for the kerning configuration which is available in the suckless terminal, https://git.suckless.org/st/tree/config.def.h#n27.

From what I understand (not a lot), this issue was opened to demand for the same but we can't do it on Linux because of how FreeType works, is that correct?

**Comment by kovidgoyal** [comment] 2017-12-26 11:59
Well, once can adjust cell width, current kitty code should handle it sseamlesly. But, there is not much point to doing it for the reasons outlined above. And, to be clear, reducing cell width is emphatically *not* the same as kerning. Reducing cell width reduces hspace between all characters. kerning, reduces hspace between pairs (or more generally for opentype GPOS tables, runs) of characters, based ontheir surrounding characters, opentype font features enabled, etc.

**Comment by awalgarg** [comment] 2017-12-26 12:03
@kovidgoyal So what `st` is doing here is not adjusting kerning, but something similar and kitty can offer a similar configuration without much hassle, right? If it is so, I can try having a look myself. Would you accept a patch to expose this option (akin to `adjust_line_height` I am assuming)?

**Comment by kovidgoyal** [comment] 2017-12-26 12:05
I have no idea what st is doing, but, as far as I know, very few terminals implement cell based rendering the way kitty does. I dont mind having an option to adjust cell width the way the option to adjust cell height already works.

**Comment by nighthawk469** [comment] 2024-04-11 17:45
I wanted to add to this and say I think kitty looks strange on macos because of the wider character spacing. Alacritty default seems just about perfect. This is with SF Mono font.

apple terminal
<img width="1458" alt="apple terminal" src="https://github.com/kovidgoyal/kitty/assets/2553980/4d759ca7-53df-49b8-a2fe-65ddfc83c402">

alacritty
<img width="1464" alt="alacritty" src="https://github.com/kovidgoyal/kitty/assets/2553980/127d7992-f457-4173-9c87-a1fac9668708">

kitty
<img width="1464" alt="kitty" src="https://github.com/kovidgoyal/kitty/assets/2553980/96527ade-ef75-4807-84eb-2a09692dbd5e">
