### ISSUE TITLE
Default Effect

### ISSUE THREAD

**Issue by kirkins** [kovidgoyal/kitty#1900] opened 2019-08-09 16:03 UTC
Hello, I installed Kitty and it is doing a matrix type effect on all my text?

Is this a bug or an effect? I'm not sure how to turn it off?

I mainly want to use Kitty so I can view images while using Ranger.

![Screenshot from 2019-08-09 12-00-22](https://user-images.githubusercontent.com/9503662/62794512-4bc23d80-baa2-11e9-9af5-4fbee697313c.png)

**Comment by Luflosi** [comment] 2019-08-09 16:06
This is probably a duplicate of #1484. Either downgrade mesa to 18.x or upgrade to >= 19.0.5.

**Comment by kovidgoyal** [comment] 2019-08-09 16:44
dup of #1484

**Closed by kovidgoyal** 2019-08-09 16:44 UTC
