### ISSUE TITLE
Crash if I hit Command-V

### ISSUE THREAD

**Issue by sbeldekov** [kovidgoyal/kitty#257] opened 2017-12-28 12:51 UTC
I have tried 0.6.1
Every time I press Command-V to paste the clipboard content the kitty crashes

[cmd-v.txt](https://github.com/kovidgoyal/kitty/files/1591216/cmd-v.txt)

**Comment by kovidgoyal** [comment] 2017-12-28 13:39
That's a crash inside Apple's CoreFoundation libraries. Not sure what Ic an do about it. Does it happen if you use the default shortcut for paste, ctrl+shift+v?

**Comment by sbeldekov** [comment] 2017-12-28 14:04
ctrl+shift+v works perfect
but sometimes I use cmd-v by force of habit

**Comment by kovidgoyal** [comment] 2017-12-29 01:46
Have you actually mapped cmd-v to paste in kitty.conf or are you just pressing it by accident?

**Comment by sbeldekov** [comment] 2017-12-29 08:13
I have not mapped anything in kitty.conf

**Comment by kovidgoyal** [comment] 2017-12-29 11:55
Hmm well I cant reproduce the segfault with or without mapping cmd-v. And given that it is happening inside CoreFoundation, I hae no way of debugging it either, so I'm afraid this is a wontfix.

**Closed by kovidgoyal** 2017-12-29 11:55 UTC
