### ISSUE TITLE
Colors set in config file are displayed pale

### ISSUE THREAD

**Issue by GscheadaHamme** [kovidgoyal/kitty#4322] opened 2021-12-06 17:19 UTC
I'm afraid the solution to this issue could be rather simple but after researching for quite a while I still have no Idea what's going on.

I'm using the OneDark color scheme for Vim and set the kitty colors according to the [One Dark.kitty](https://github.com/joshdick/onedark.vim/blob/main/term/One%20Dark.kitty) file included in the package.
This is my [kitty.conf](https://github.com/kovidgoyal/kitty/files/7662362/kitty.conf.txt).

However, the displayed colors are pale compared to the [color reference](https://raw.githubusercontent.com/joshdick/onedark.vim/main/img/color_reference.png). This extends to Vim after setting OneDark to use terminal emulator colors:
![OneDark-terminal_colors](https://user-images.githubusercontent.com/64575726/144888088-7bc1c31e-8b6c-4b00-881b-900af918f9bb.png)

The expected colors can be shown by setting OneDark to use the colors defined in the package: 
![OneDark-original](https://user-images.githubusercontent.com/64575726/144888504-8628a11b-6f00-44eb-9854-db50e0323734.png)

Is there a way to get kitty to use those true colors?

Many thanks in advance.

**Comment by page-down** [comment] 2021-12-07 01:15
I tried the following configuration and it worked fine.
vim 8.2

~/.vim/autoload/onedark.vim
~/.vim/colors/onedark.vim

~/.vimrc
```vim
syntax on                                                                            
colorscheme onedark                                                                  
                                                                                     
if $TERM == "xterm-kitty"                                                            
    set termguicolors                                                                
    let &t_ut=''                                                                     
endif
```

```shell
kitty --config=NONE -o include=onedark.kitty.conf
```

**Comment by kovidgoyal** [comment] 2021-12-07 01:44
I dont see how this can be a kitty bug, there has been extensive checking of kitty's color rendering including measuring of the output colors with colorimeter. And it has been found to be correct (a bit of searching in the closed issues will find the relevant ones). This must be some kind of misconfiguration and since its not reproducible with a minimal vim config, I am closing.

**Closed by kovidgoyal** 2021-12-07 01:44 UTC
Labels: bug

**Comment by GscheadaHamme** [comment] 2021-12-07 09:04
Turns out my .vimrc is broken and got the wrong impression of how One Dark colors look.

Thanks for your effort and sorry for posing insufficiently researched questions.
