### ISSUE TITLE
Relatively high CPU use

### ISSUE THREAD

**Issue by matthewjwoodruff** [kovidgoyal/kitty#115] opened 2017-08-25 14:38 UTC
I mentioned this in yesterday's HN thread, and was encouraged to submit it as a bug. (https://news.ycombinator.com/item?id=15091358)  I see cpu utilization spike to 15% when scrolling around a big file in a text editor.  On the same system, examining the same file in the same text editor I see:

konsole: 20%
terminology: 15%
kitty: 15%
terminator (vte-based): 6%
gnome-terminal (vte-based): 4%
lxterminal (vte-based): 3%
urxvt: 1%

(The variance in vte-based terminal emulator performance is interesting to me, which is why I tried three of them.)  I can supply more system information if interested -- kitty's performance is solidly in the middle of the pack, but I'm often trying to conserve battery on an old netbook so I'm on the lookout for CPU efficiency.  Regardless, I'm glad to see this project pushing the state of the art forwards in terminal emulators!

**Comment by matthewjwoodruff** [comment] 2017-08-25 14:46
While I'm at it, I just noticed another thing: mouse tracking.

Here's the same system, with nothing but bash running in each terminal emulator, as the mouse cursor passes over it:

kitty: 25%
terminology: 14%
terminator: 2%
gnome-terminal: 2%
lxterminal: 2%
konsole: 1.3%
urxvt: 0.0%

Thanks!

**Comment by kovidgoyal** [comment] 2017-08-25 15:40
Interesting, I'll take a look at it when I have a moment. I certainly have not spent any effort on optimising mouse handling, since I almost never use a mouse. However, the last time I benchmarked scrolling performance it was pretty good comapred to most terminals. I did, however, only look at throughput, not CPU utilisation, since that is the metric I care more about. But certainly, reducing CPU utilisation is a worthy goal. And there may have been some regression since then.

**Comment by kovidgoyal** [comment] 2017-08-25 15:47
Also, on the scrolling CPU utilisation, what editor were you using? And did you have syntax highlighting turned on? Does the result change when you scroll around in a simple pager such as less?

**Comment by matthewjwoodruff** [comment] 2017-08-25 16:09
I'm using kakoune as my text editor.  Syntax highlighting certainly is a big hit on the text editor's cpu use.  I suppose the terminal emulator has to work harder to show the colors?  

It's a good question about less.  In the interest of science, here are my observations:

terminology: 15%
kitty: 6%
terminator: 5%
konsole: 3%
lxterminal: 2.6%
gnome-terminal: 2.6%
urxvt: 0.7%

Thanks!

**Comment by kovidgoyal** [comment] 2017-08-25 16:20
Hmm scrolling around in a big file in less on my system shows:

konsole: 12-14%
kitty: 6-7%
termite: 6-7%
urxvt: 4-6%

And while I might be biased the scrolling felt subjectively "smoother" in kitty to me. This is probably because kitty renders in a separate thread. I dont think most other terminals do, but I could be wrong.

I suspect the results are highly dependent on GPU and OpenGL driver quality. Not to mention other variables, such as font size (as this will affect how much text is visible per line), actual font used (since the complexity of rendering glyphs varies from font to font), etc. 

The file I used to test scrolling around in is: https://github.com/kovidgoyal/rapydscript-ng/blob/master/README.md

**Comment by kovidgoyal** [comment] 2017-08-25 16:26
And here are some more results. This time running

```
time yes | head -n 1000000
```

kitty:
head -n 1000000  0.00s user 0.48s system 43% cpu 1.122 total

konsole:
head -n 1000000  0.01s user 0.41s system 23% cpu 1.789 total

urxvt:
head -n 1000000  0.00s user 0.19s system 87% cpu 0.222 total

termite:
head -n 1000000  0.01s user 0.20s system 38% cpu 0.543 total


I dont really see a clear pattern.

**Comment by koekeishiya** [comment] 2017-08-25 19:12
Running `time yes | head -n 1000000` on my mbp makes the cpu usage peak at roughly 70% just as it finishes.

I noticed that when I'm running inside tmux (almost always), the cpu usage peaks at roughly 20% running the same command, same settings, window size, font size and all that.

> And while I might be biased, the scrolling felt subjectively "smoother" in kitty to me. This is probably because kitty renders in a separate thread. I dont think most other terminals do, but I could be wrong.

This is the best part about Kitty in my experience, at least on macOS. The rendering is 100x smoother than any terminal application I've found, when doing text-heavy stuff (and editing large files)

I didn't notice the above before this issue was brought up as it has not actually had an impact for me.

**Comment by matthewjwoodruff** [comment] 2017-08-25 19:32
> I suspect the results are highly dependent on GPU and OpenGL driver quality.

Definitely.  I tend to run systems that don't have particularly beefy GPUs, and I'm sure that skews the results.  I had a similar experience with alacritty, which also uses OpenGL for rendering.   Kitty is definitely up there with vte and urxvt in terms of throughput and perceived latencey, so those CPU cycles certainly aren't going to waste.  I'd agree that it's one of the smoothest terminal emulators I've used.

**Comment by kovidgoyal** [comment] 2017-08-26 02:06
Still it would be interesting to track down where exactly CPU time is being spent when scrolling and see if the code path cannot be optimised. I'll add it to my TODO list to add better tooling to kitty for performance tracking. Currently you can use the --perf option to see what high level functions are taking the most CPU time, but this only works at the python level, not at the C level so is not partcularly useful for this task.

**Comment by kovidgoyal** [comment] 2017-08-26 04:55
I committed some instrumentation for analysing kitty performance. https://github.com/kovidgoyal/kitty/commit/a922b4c789c0d4fd21d43d1b2ae6f6f098b2b8d6

**Comment by kovidgoyal** [comment] 2017-08-26 08:16
I optimized a couple of code paths, thanks to the instrumentation, but fundamentally, I dont think CPU utilisation can be significantly reduced without compromising on other design goals. The reasons are:

1) kitty renders in a separate thread, this means that screen updates are processed at 100 FPS continuously. This involves serializing data to send to the GPU at 100FPS. This greatly enhances perceived latency, at the cost of higher CPU utilisation. If you use the instrumentation, you will see that the main cost centre in kitty's code for CPU utilisation is update_cell_range_data() which is serializing the spirte positions for the GPU render.  For instance, on my machine, I could reduce CPU utilization by about 30% by changin repaint_delay from 10 to 100ms in kitty.conf at the cost of much jankier scrolling.

2) There is a significant amount of python code involved in handling events. This is because the UI layer is in python for easy hackability/maintainability. If you look at the call graph you will see CPU utilisation from lots of python methods. This can in principle be reduced, but at the cost of rewriting most of the UI layer. Given that the actual user visible performance is pretty good, I dont think this is worth the tradeoff.

Below are the top few entries from the call graph:

```
Total: 244 samples
      21   8.6%   8.6%       21   8.6% _PyEval_EvalFrameDefault
      15   6.1%  14.8%       15   6.1% __pthread_cond_wait
      11   4.5%  19.3%       11   4.5% __driDriverGetExtensions_virtio_gpu
      10   4.1%  23.4%       10   4.1% _PyType_Lookup
      10   4.1%  27.5%       10   4.1% nouveau_drm_screen_create
       9   3.7%  31.1%        9   3.7% __select_nocancel
       8   3.3%  34.4%        8   3.3% _PyDict_GetItem_KnownHash
       8   3.3%  37.7%       13   5.3% update_cell_range_data
       7   2.9%  40.6%        7   2.9% __memcpy_sse2_unaligned_erms
       5   2.0%  42.6%        5   2.0% PyEval_CallObjectWithKeywords
       5   2.0%  44.7%        5   2.0% __ioctl
       5   2.0%  46.7%        5   2.0% __libc_recvmsg
       4   1.6%  48.4%        4   1.6% PyObject_GetAttr
       4   1.6%  50.0%        4   1.6% _PyObject_GenericGetAttrWithDict
       4   1.6%  51.6%        4   1.6% __GI___pthread_mutex_lock
       4   1.6%  53.3%        4   1.6% _init@5c0f8
       4   1.6%  54.9%        4   1.6% sprite_position_for (inline)
       3   1.2%  56.1%        3   1.2% PyDict_Contains
       3   1.2%  57.4%        3   1.2% PyDict_GetItem
       3   1.2%  58.6%        3   1.2% PyFrame_New
       3   1.2%  59.8%        3   1.2% PyObject_Malloc
       3   1.2%  61.1%        3   1.2% PyTuple_New
       3   1.2%  62.3%        3   1.2% _PyUnicode_FromId
       3   1.2%  63.5%        3   1.2% __pthread_cond_timedwait
```

**Closed by kovidgoyal** 2017-08-26 08:16 UTC

**Comment by matthewjwoodruff** [comment] 2017-08-29 18:56
This is an interesting analysis.  I'd say your only opportunity for improvement that doesn't give up performance would be calming down the mouse movement handler.  But at any rate I'll be turning to kitty when I want performance more than I want to conserve battery.  Thanks for looking into CPU use!

**Comment by kovidgoyal** [comment] 2017-08-30 00:36
I'm actually trying to see if I can eliminate update_cell_range_data() entirely (replacing it by memcpy), at the cost of a little more memory usage (~ 150 KB for a terminal window with 200 columns and 100 rows). It remains to be seen how much impact it will have on CPU usage. See the fast branch which is where I am working on this (and many other optimisations). I dont expect the total improvement to be more than 10% or so, at least as per the profiling numbers I posted earlier. But I decided to do it anyway, as it is a good opportunity to clean up some of kitty's internals.

**Comment by kovidgoyal** [comment] 2017-09-08 15:26
Oh and I just realized you are measuring CPU usage incorrectly. At least on Linux, if you want to measure the actual CPU usage you have to measure both the CPU usage of the terminal process and the X server process. This is because X based terminals such as urxvt delegate lots of work to the X server, while kitty mostly bypasses the X server. On my system, scrolling in less, I get CPU usage:

kitty + X: 9 - 12%
urxvt + X: 16 - 18%
konsole + X: 28 - 31%
termite + X: 10 -12%


And if you are actually interested in power consumption, rather than CPU usage, it becomes even more complicated, as you have to take into account GPU usage as well. I dont know of an easy way to do that, since both the X server and kitty itself use OpenGL as a backend.

And the CPU numbers above (apart from konsole) are all similar enough that I dont think it will matter which terminal you use at all. Other processes on your computer will use far more CPU.

**Comment by matthewjwoodruff** [comment] 2017-09-08 17:14
Good point -- I wasn't accounting for X.  I see similar results on my system.

**Comment by kovidgoyal** [comment] 2017-09-15 16:32
Just FYI, in the fast branch where I have implemented various optimizations in addition to those discussed above, CPU usage of kitty + X on my system has gone down from 9 - 12% to 8 - 10%, inline with the 10% improvement I expected. This makes kitty the clear leader of the pack :) Although to be fair, the difference is not that great.

This is despite the fast branch gaining a couple of features: more intelligent mouse selection and underlining of hyperlinks when mousing over them.

I also took the time to optimize the mouse handler. 

Note that the fast branch is still in development, so you may get breakage if you use it.

**Comment by kovidgoyal** [comment] 2017-09-16 02:55
Thanks to this commit https://github.com/kovidgoyal/kitty/commit/728f33700ad361093cbefeceb246d274bce1cb1d

CPU usage is halved while scrolling in less. It is now 4-6%. Hopefully it wont cause any other problems. 

```
Fine tune the artificial delays in the render loop
There are now two numbers, repaint_delay and input_delay
that control how often the screen is repainted and how frequently
input received from the child process is processed.

This halves the CPU usage in intensive cases such as scrolling
a file in less. The CPU usage of kitty + X when scrolling is now
significantly lower than all the other terminals on my system.

MROAWR!
```
