### ISSUE TITLE
Crash on wl_pointer after switching gnome login session

### ISSUE THREAD

**Issue by special** [kovidgoyal/kitty#5145] opened 2022-05-28 17:55 UTC
**Describe the bug**
After switching to a different login session (e.g. with Ctrl+Alt+F1), Gnome (42.1) clears the `wl_seat.capabilities`. This causes glfw to destroy the wl_pointer and wl_keyboard ([as it should](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_seat-event-capabilities)): https://github.com/kovidgoyal/kitty/blob/e9340dfaaf0831d5a9c644bee5e6ebc9e85d7e16/glfw/wl_init.c#L572-L576
But most functions assume that the pointer and keyboard always exist. If kitty was focused, it usually crashes immediately:
```gdb
#0  wl_proxy_get_version (proxy=proxy@entry=0x0) at ../src/wayland-client.c:2200
#1  0x00007fffe8d6c19e in wl_pointer_set_cursor (wl_pointer=0x0, serial=576231, surface=surface@entry=0x600ee0, hotspot_x=10, hotspot_y=11) at /usr/include/wayland-client-protocol.h:4796
#2  0x00007fffe8d6ec05 in setCursorImage (window=<optimized out>, on_theme_change=on_theme_change@entry=false) at glfw/wl_window.c:151
#3  0x00007fffe8d6ecfc in incrementCursorImage (window=<optimized out>) at glfw/wl_window.c:647
#4  0x00007fffe8d6ed3c in animateCursorImage (timer_id=<optimized out>, data=<optimized out>) at glfw/wl_window.c:657
#5  0x00007fffe8d79b9a in dispatchTimers (eld=eld@entry=0x7fffe8dc9ba8 <_glfw+132488>) at glfw/backend_utils.c:209
```

**To Reproduce**
1. Run kitty under Gnome (42.1+) wayland
2. With kitty focused, press `Ctrl+Alt+F1` to switch login sessions
3. Return to the gnome session

**Environment details**
- Fedora 36, default configuration
- Gnome 42.1
- kitty 0.25.1 (cb55878efd)
- `--config NONE`

This didn't happen on Fedora 35 (Gnome 41).

**Additional context**
Screen lock doesn't detach the seat. Switching users through the menu does, but often won't crash because kitty isn't trying to do anything.

**Comment by kovidgoyal** [comment] 2022-05-29 02:36
Does not reproduce for me, steps I tried:

0) start gnome 42.1 wayland under VT 2
1) start kitty under gnome wayland
2) press ctrl+alt+f1 to switch to a different x11 session
3) press ctrl+alt+f2 to switch back to the gnome session
4) Ensure kitty is focused and type something in it
5) No crashes

And if GNOME really is closing the seat the it needs to re-open it
before sending any other events. So this looks like a bug in GNOME.

**Comment by kovidgoyal** [comment] 2022-05-29 09:17
Actually I think the issue is using animated cursors the timer for those needs to be canceled when closing the seat.

**Closed** 2022-05-29 09:21 UTC
Labels: bug
