### ISSUE TITLE
Kitty window freezes when on secondary display on MacOS

### ISSUE THREAD

**Issue by BLucky-gh** [kovidgoyal/kitty#5104] opened 2022-05-16 15:13 UTC
**Describe the bug**
When I move kitty to my second display it freezes (the display itself is fine, and I can move and resize the window, but it doesn't respond to inputs and the cursor doesn't blink.
Note: the secondary display is a usb display using DisplayLink software. 

**To Reproduce**
1. open kitty
2. move it to second display
3. try typing

**Environment details**
```
kitty 0.25.0 created by Kovid Goyal
Darwin bluckymac.lan 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.3.1 BuildVersion:	21E258
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/blucky/.config/kitty/kitty.conf

Config options different from defaults:
background_image                   /Users/blucky/backgrounds/grim.png
background_image_layout            scaled
background_opacity                 0.8
background_tint                    0.85
close_on_child_death               True
copy_on_select                     selection
font_family                        RobotoMono Nerd Font Mono
font_size                          10.0
inactive_text_alpha                0.8
macos_option_as_alt                3
macos_quit_when_last_window_closed True
mouse_hide_wait                    -1.0
pointer_shape_when_grabbed         hand
resize_draw_strategy               3
resize_in_steps                    True
scrollback_fill_enlarged_window    True
scrollback_lines                   4096
scrollback_pager_history_size      8388608
shell_integration                  frozenset({'no-rc'})
strip_trailing_spaces              smart
tab_activity_symbol                碌
tab_bar_edge                       1
tab_bar_margin_height              TabBarMarginHeight(outer=0, inner=0.1)
tab_bar_style                      slant
tab_title_template                 {index}:{fmt.fg.tab}{title.split()[0]} {fmt.fg.red}{bell_symbol}{activity_symbol}
visual_bell_duration               0.1
window_logo_alpha                  0.4
Changed mouse actions:
	middle release ungrabbed → paste_from_buffer selection
Colors:
	active_border_color                #c9cbff   
	active_tab_background              #575268   
	active_tab_foreground              #f5c2e7   
	background                         #1e1e2e   
	bell_border_color                  #fae3b0   
	color0                             #6e6c7e   
	color1                             #f28fad   
	color10                            #abe9b3   
	color11                            #fae3b0   
	color12                            #96cdfb   
	color13                            #f5c2e7   
	color14                            #89dceb   
	color15                            #d9e0ee   
	color2                             #abe9b3   
	color3                             #fae3b0   
	color4                             #96cdfb   
	color5                             #f5c2e7   
	color6                             #89dceb   
	color7                             #d9e0ee   
	color8                             #988ba2   
	color9                             #f28fad   
	cursor                             #f5e0dc   
	cursor_text_color                  #1e1e2e   
	foreground                         #d9e0ee   
	inactive_border_color              #575268   
	inactive_tab_background            #1e1e2e   
	inactive_tab_foreground            #d9e0ee   
	mark1_background                   #96cdfb   
	mark1_foreground                   #1e1e2e   
	mark2_background                   #f5c2e7   
	mark2_foreground                   #1e1e2e   
	mark3_background                   #b5e8e0   
	mark3_foreground                   #1e1e2e   
	selection_background               #575268   
	selection_foreground               #d9e0ee   
	tab_bar_background                 #161320   
	url_color                          #f5e0dc   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.1.0/Contents/Home/bin:/usr/local/opt/python@3.7/bin:/usr/local/sbin:/usr/local/opt/sqlite/bin:/Users/blucky/.zinit/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Users/blucky/.cargo/bin:/usr/local/opt/openssl@3/bin:/Users/blucky/.local/bin
	LANG                                en_US.UTF-8
	EDITOR                              nvim
	SHELL                               /bin/zsh
	DISPLAY                             /private/tmp/com.apple.launchd.NaBl143moy/org.xquartz:0
	USER                                blucky

```

**Additional context**
As I mentioned earlier, DisplayLink

**Comment by kovidgoyal** [comment] 2022-05-16 15:40
this will be a bug in apple's CVDisplayLinkTimer see #2016

There's sadly nothing I can do about it.

**Comment by BLucky-gh** [comment] 2022-05-16 15:49
Actually I checked that issue and when running `kitty --debug-rendering` I'm getting a different error from what is described in #2016

that issue has a `render frame not received` or somthing, while mine (while it does have a render frame not received line) also has this:
```
❯ kitty --debug-rendering
Polling for monitors: 2 found
Cell height calculation:
	line height from line origins: 24.000000
	line bounds: origin-y: -4.882812 height: 23.437500
	line bounds-no-leading: origin-y: -4.882812 height: 23.437500
	bounds metrics: ascent: 18.554688
	line metrics: ascent: 18.554688 descent: 4.882812 leading: 0.000000
	font metrics: ascent: 18.554688 descent: 4.882812 leading: 0.000000 underline_position: -1.464844
	cell_height: 24 baseline: 19 underline_position: 20 strikethrough_position: 12
GL version string: '4.1 ATI-4.8.15' Detected version: 4.1
prompt_marking: x=0 y=0 op='A'
prompt_marking: x=2 y=1 op='B'
[136 19:45:47.264941] No render frame received in 0.25 seconds, re-requesting at: 0.749225
[136 19:45:47.713535] No render frame received in 0.25 seconds, re-requesting at: 1.197089
prompt_marking: x=0 y=0 op='A'
prompt_marking: x=2 y=1 op='B'
[136 19:45:47.716736] No render frame received in 0.25 seconds, re-requesting at: 1.200900
[136 19:45:48.148711] OpenGL error: The framebuffer object is not complete (GL_INVALID_FRAMEBUFFER_OPERATION) (calling function: glClear)

<MY TERMINAL PROMPT HERE>

 Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>                                                                                                 
BrokenPipeError: [Errno 32] Broken pipe
```
I removed the terminal prompt in there because it made the log harder to read but the point is that the last 2 lines are after the prompt

Also when running with `--debug-rendering` kitty crashes immediately as soon as it is on the second monitor. This doesn't happen when running without `--debug-rendering`

Also the other issue mentions that kitty still works and reacts to input even if frozen, while mine doesn't react to inputs at all.


This might still be the same issue but I'm mentioning it in case it isn't

**Comment by kovidgoyal** [comment] 2022-05-16 15:56
See https://sw.kovidgoyal.net/kitty/build/ for how to build from source.

**Comment by BLucky-gh** [comment] 2022-05-16 16:15
I am a little busy at the moment but I will try to build from source when I'm free (which may be tomorrow), are there any patches I have to apply before buidling it?

**Comment by kovidgoyal** [comment] 2022-05-17 00:40
THere are only two calls to glClear in the entire kitty codebase, both
in shaders.c just add some printfs before them to identify which one is
failing.

**Comment by BLucky-gh** [comment] 2022-05-17 08:25
I found only one call to glClear on line 827 in shaders.c (and a call to glClear*Color* 2 lines up), but grep also found a call in `glfw/context.c`

Do I need to add printfs around the glClearColor?

**Comment by BLucky-gh** [comment] 2022-05-17 08:36
This time when the window freezes on the secondary window it does react to keystrokes since it closed when I pressed ^D

as for the crashing with `--debug-rendering`: here's the line:

```
reached glClear on line 827 of shaders.c
[137 12:34:42.938626] OpenGL error: The framebuffer object is not complete (GL_INVALID_FRAMEBUFFER_OPERATION) (calling function: glClear)
```
(the opengl error is when it crashed)

I have a printf before and after each call so that one definitely didn't exit

**Comment by kovidgoyal** [comment] 2022-05-17 09:39
That looks like the framebuffer is not supported by the opengl driver
used for that device. Try putting a

printf("framebuffer status: %d\n", glCheckFramebufferStatus(GL_FRAMEBUFFER));

before the glClear()

that should hopefully tell us more about what the problem is.

**Comment by BLucky-gh** [comment] 2022-05-17 09:42
```
framebuffer status: 36053
came out of glClear on line 827 of shaders.c alive
reached glClearColor on line 825 of shaders.c
came out of glClearColor on line 825 of shaders.c alive
reached glClear on line 827 of shaders.c
framebuffer status: 36053
came out of glClear on line 827 of shaders.c alive
reached glClearColor on line 825 of shaders.c
came out of glClearColor on line 825 of shaders.c alive
reached glClear on line 827 of shaders.c
framebuffer status: 33305
[137 13:41:26.016785] OpenGL error: The framebuffer object is not complete (GL_INVALID_FRAMEBUFFER_OPERATION) (calling function: glClear)
```

**Comment by kovidgoyal** [comment] 2022-05-17 10:51
framebuffer status: 33305
is GL_FRAMEBUFFER_UNDEFINED

which is supposed to indicate the framebuffer doesnt exist. I dont know
enough about Apple's OpenGL stack to know for sure how that's possible. My only
guess is that the driver for this device doesnt support the surface
kitty requests. I dont see how that can be fixed in kitty, sorry.

**Comment by BLucky-gh** [comment] 2022-05-17 10:53
That could also be an issue with DisplayLink, not Apple (though it could also be both). But thanks for at least debugging it. I guess I'll just use kitty exclusively on my main screen for now. 

Though what's surprising that it worked fine until the day before yesterday, and I don't remember updating neither homebrew nor the OS itself before that

**Closed** 2022-05-17 11:05 UTC
Labels: bug
