### ISSUE TITLE
Weird vertical lines sometimes appear on the right side of a kitty window on macOS

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1104] opened 2018-10-28 14:30 UTC
As you can see the lines can have different colours.
With my normal `kitty.conf`, my kitty fork, five blue lines, two different blue tones:
![screenshot](https://user-images.githubusercontent.com/15217907/47616598-892f7e80-dabf-11e8-96a8-63219ac79bc7.png)
The following screenshots are with `macos_hide_titlebar yes` in `kitty.conf` as the macOS window decorations can get in the way of seeing the lines a bit.
My kitty fork, the same five blue lines with the same two blue tones:
![no borders](https://user-images.githubusercontent.com/15217907/47616784-ad8c5a80-dac1-11e8-9268-a7dfdee89078.png)
Your kitty version, one huge line of black pixels on the, it's a bit difficult to see:
![black lines](https://user-images.githubusercontent.com/15217907/47616793-bbda7680-dac1-11e8-9fdf-0794af58a015.png)
My kitty fork, a different window height, red line:
![different lines](https://user-images.githubusercontent.com/15217907/47616925-07415480-dac3-11e8-979d-4c7de80cdd5d.png)
Your kitty version produces the same red line with this height.
They can disappear or reappear on very minor events like the mouse cursor entering, scrolling, typing text, switching kitty OS windows, etc.. Minor details of the code seem to also influence something. When testing this issue today, I could reliably get the five blue lines in my fork with `initial_window_width   80c` and `initial_window_height  28c` and the long black line in your version of kitty with the same dimensions. Some dimensions don't show the lines. Resizing the window by grabbing the window border with the mouse cursor usually makes it impossible to reproduce. They look a bit like uninitialised memory. Any idea on how to debug this?

**Comment by kovidgoyal** [comment] 2018-10-28 23:45
Probably similar to the issue fixed in 6e34a7559b3493bf9ed2640ef20fcba54f3a5696

**Comment by Luflosi** [comment] 2018-10-29 22:46
Maybe, but I don't have background opacity enabled.

**Comment by Luflosi** [comment] 2018-10-29 23:03
Just to clarify: I also don't have dynamic_background_opacity enabled.

**Comment by kovidgoyal** [comment] 2018-10-30 05:18
that doesn't matter the fix there applies to all drawing regardless of opacity. Most likely you just need to adjust the scissor limits on the right.

**Comment by Luflosi** [comment] 2018-10-30 20:32
Could you tell me a bit more please? How do I adjust the scissor limits on the right? I haven't achieved anything by playing around with the ceilf/floorf functions and adding/subtracting numbers. And I have no idea how rendering works in kitty :/.

**Comment by kovidgoyal** [comment] 2018-10-31 02:37
you simply increase the width numbers, if doing that does not help then the problem is not with the scissor, but likely instead with the drawing of borders/padding, which you can check by changing those values in kitty.conf

**Comment by Luflosi** [comment] 2018-11-05 15:16
```diff
diff --git a/kitty/shaders.c b/kitty/shaders.c
index 1f3f1c1c..af720dad 100644
--- a/kitty/shaders.c
+++ b/kitty/shaders.c
@@ -466,9 +466,9 @@ draw_cells(ssize_t vao_idx, ssize_t gvao_idx, GLfloat xstart, GLfloat ystart, GL
     // for a test case (the scissor is also used by draw_cells_interleaved_premult to blit the framebuffer)
 #define SCALE(w, x) ((GLfloat)(os_window->viewport_##w) * (GLfloat)(x))
     glScissor(
-            (GLint)(ceilf(SCALE(width, (xstart + 1.0f) / 2.0f))),
+            (GLint)(ceilf(SCALE(width + 1, (xstart + 1.0f) / 2.0f))),
             (GLint)(ceilf(SCALE(height, ((ystart - h) + 1.0f) / 2.0f))),
-            (GLsizei)(floorf(SCALE(width, w / 2.0f))-1),
+            (GLsizei)(floorf(SCALE(width + 1, w / 2.0f))-1),
             (GLsizei)(floorf(SCALE(height, h / 2.0f))-1)
     );
 #undef SCALE
```
did not help, I also tried 10 and 100.
Changing the `window_padding_width` config option to 1 does seem to fix it.

**Comment by kovidgoyal** [comment] 2018-11-06 05:56
OK if you can post a minimal conf file and anything else needed to reproduce, I will take a look.

**Comment by Luflosi** [comment] 2018-11-06 11:11
This is the minimal config that shows the behaviour on your latest master branch for me:
```
initial_window_width   80c
initial_window_height  28c
```

**Comment by Luflosi** [comment] 2018-11-07 14:38
Here is my current theory: When an OS window is rendered some buffers are swapped with `swap_window_buffers()`. One of these buffers has the correct contents but one line of pixels in the other buffer wasn't initialised correctly. Whenever the window is rendered again, the buffers are swapped. That would explain, why the line disappears and reappears.
Could this be what's happening?

**Comment by kovidgoyal** [comment] 2018-11-07 15:08
yes, that is what is happening, the queestion is why. Both buffers are
drawn to with the exactr same code and also fully cleeared to background
color.

**Closed** 2018-11-13 15:29 UTC

**Comment by Luflosi** [comment] 2018-11-13 18:51
I can no longer reproduce the issue, your commit seems to have fixed it 🎉. Thank you!

**Comment by Luflosi** [comment] 2019-01-17 01:05
I just wanted to let you know, that it's still possible for the lines to appear but I'm not sure how to reproduce it and it only happened twice since your commit, at least one of those times was after resizing the window. It's definitely a ton better than it was before your commit, at least for me. How it currently is doesn't bother me since it's so rare for this to occur.
![bildschirmfoto 2019-01-09 um 19 25 59](https://user-images.githubusercontent.com/15217907/51028588-1dc05d80-1594-11e9-98c3-ad14f1fb070d.png)

**Comment by kovidgoyal** [comment] 2019-01-17 02:53
If you can figure out how to reproduce it, I will be happy to take another look.
