### ISSUE TITLE
Japanese input bug?

### ISSUE THREAD

**Issue by ghsable** [kovidgoyal/kitty#3330] opened 2021-02-20 09:57 UTC
**To Reproduce**

OK :  `あいうえお。`
1. input `あいうえお。`
2. \<Enter\>

NG :  `。あいうえお`
1. input `あいうえお` 
2. \<Space\>
3. input `。` 
4. \<Enter\>

**Environment details**
* Arch Linux 5.10.16
* kitty 0.19.3
* Fictx5 5.0.5/Mozc 2.26.4220.102
  * `export GLFW_IM_MODULE=ibus` : [#469](https://github.com/kovidgoyal/kitty/issues/469#issuecomment-778814173)

  or

* IBus 1.5.24/IBus-Anthy 1.5.12
  ```
  export GTK_IM_MODULE='ibus'
  export QT_IM_MODULE='ibus'
  export XMODIFIERS=@im='ibus'
  ```

**Screenshots**
![simplescreenrecorder-2021-02-20_18 48 59](https://user-images.githubusercontent.com/23327416/108591673-3c1cf800-73ad-11eb-9e4a-1e9f92b2984b.gif)

**Comment by kovidgoyal** [comment] 2021-02-28 17:01
Sorry I dont have the time/interest to debug this, however if someone else does, let me know and I will provide any needed guidance.

**Comment by kovidgoyal** [comment] 2021-03-27 15:28
Set force_ltr = yes in kitty.conf and you will be fine.

**Comment by rouge8** [comment] 2021-03-30 01:37
I don't think `force_ltr = yes` fixes this. Kitty still draws `。あいうえお` instead of `あいうえお。`, at least on macOS.

Config:  

```
❯ kitty --debug-config
kitty 0.19.3 created by Kovid Goyal
Darwin apollo 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.7 BuildVersion:	19H524
Loaded config files: /Users/andy/.config/kitty/kitty.conf

Config options different from defaults:
background              Color(red=39, green=39, blue=39)
color0                  Color(red=39, green=39, blue=39)
color1                  Color(red=204, green=35, blue=28)
color10                 Color(red=184, green=186, blue=37)
color11                 Color(red=250, green=188, blue=46)
color12                 Color(red=131, green=165, blue=151)
color13                 Color(red=211, green=133, blue=154)
color14                 Color(red=142, green=192, blue=123)
color15                 Color(red=235, green=219, blue=178)
color2                  Color(red=152, green=151, blue=25)
color3                  Color(red=215, green=153, blue=32)
color4                  Color(red=68, green=132, blue=136)
color5                  Color(red=177, green=97, blue=133)
color6                  Color(red=104, green=157, blue=105)
color7                  Color(red=168, green=153, blue=131)
color8                  Color(red=146, green=131, blue=115)
color9                  Color(red=251, green=72, blue=51)
confirm_os_window_close 1
font_size               16.0
force_ltr               True
foreground              Color(red=235, green=219, blue=178)
scrollback_lines        10000
selection_background    Color(red=235, green=219, blue=178)
selection_foreground    Color(red=101, green=91, blue=83)
tab_bar_edge            1
url_color               Color(red=214, green=92, blue=13)
Added shortcuts:
	control+m KeyAction(func='scroll_to_mark', args=[True, 0])
	shift+control+m KeyAction(func='scroll_to_mark', args=[False, 0])
	super+d KeyAction(func='detach_tab', args=('ask',))
	super+f KeyAction(func='kitten', args=['create_iregex_marker.py'])
	shift+super+f KeyAction(func='remove_marker', args=())
Changed shortcuts:
	shift+control+t KeyAction(func='new_tab_with_cwd', args=())
	super+n KeyAction(func='new_os_window_with_cwd', args=())
	super+t KeyAction(func='new_tab_with_cwd', args=())
```

**Comment by kovidgoyal** [comment] 2021-03-30 02:33
Works for me with:

```
kitty -o force_ltr=y --config NONE sh -c "echo あいうえお。; read"
```

**Comment by rouge8** [comment] 2021-03-30 02:39
That works for me too, but typing the characters at a prompt or in vim, hitting space (to switch to katakana `アイウエオ` on macOS, select hiragana in the original post) still reproduces the issue.

**Comment by real-esekyl** [comment] 2021-04-05 15:33
Unfortunately this solution does not work for German umlaut characters AÖÜaöü.

**Comment by Cassin01** [comment] 2021-07-17 11:52
If you encounter this bug in vim, you can fix it by reloading vim.
This is a temporary solution. 

```init.vim
" reload init.vim
 command! ReloadInitVim :so $MYVIMRC
```

**Comment by pjm0616** [comment] 2021-11-16 13:46
I believe this is the same issue as https://github.com/kovidgoyal/kitty/pull/3852#issuecomment-884738697 - race between CommitText and UpdatePreeditText.
I've just checked that this bug has recently been fixed by series of overlay changes in c8f26dd968ce5ce2145779b09545f53c8e089fd3...75afe7cd3374a71a6bf8a9a98bd84f88f896112c, so I think this issue can be closed as resolved. Now CJK inputs works mostly well with some minor glitches.

**Closed** 2021-11-16 14:21 UTC
Labels: bug, help wanted

**Comment by page-down** [comment] 2021-11-16 14:27
In my previous tests, many of the shortcut key combinations mentioned here did not respond properly.

https://support.apple.com/guide/japanese-input-method/keyboard-shortcuts-jpim10263/mac

For example, Ctrl+J, Ctrl+K, Ctrl+L, etc.

I'm mentioning it here.
Maybe it's not an easy fix.

**Comment by kovidgoyal** [comment] 2021-11-16 14:38
On Tue, Nov 16, 2021 at 06:32:50AM -0800, page-down wrote:
> > ... I've just checked that this bug has recently been fixed by series of overlay changes ...  so I think this issue can be closed as resolved. Now CJK inputs works mostly well with some minor glitches.
> 
> I've been noticing this issue as a related IME issue under Linux, and I was under the impression that the Korean input method also had a series of unresolved issues.
> 
> And the changes you mentioned are for macOS only. Can you confirm that there is no problem under Linux as well? (ibus, fcitx)

The overlay changes apply to all platforms.

**Comment by pjm0616** [comment] 2021-11-16 15:07
For record, I've tested the exact sequence(`あいうえお<space>。`) on 
1) Ubuntu Linux 20.04 + ibus + mozc, and
2) macOS Monterey Japanese IM

...with kitty git HEAD(d936ede790), and it worked well on both platforms.

The reason I've mentioned that this is the same issue can be checked from the logs:
```
Press xkb_keycode: 0x3c clean_sym: period composed_sym: period text: . mods: none glfw_key: 46 (.��) xkb_key: 46 (period)
↳ to IBUS: keycode: 0x34 keysym: 0x2e (period) mods: none 
IBUS: CommitText: 'アイウエオ'
key_callback 1, アイウエオ, state=2
on_key_input: glfw key: 0x0 native_code: 0x0 action: PRESS mods: none text: 'アイウエオ' state: 2 committed pre-edit text: アイウエオ
IBUS: UpdatePreeditText: '。'
key_callback 1, 。, state=1
on_key_input: glfw key: 0x0 native_code: 0x0 action: PRESS mods: none text: '。' state: 1 draw codepoint line 1, col 53->55(width 2) linecols 239 char 12290
Previous text: 
updated pre-edit text: '。'
IBUS processed native_key: 0x2e release: 0 handled: 1
From IBUS: native_key: 0x2e name: period is_release: 0
↳ discarded
```
You can see that the two events "CommitText" and "UpdatePreeditText" have been occurred by a single keystroke(.). There have been race issues between two events and it has been fixed by the overlay changes.
