### ISSUE TITLE
Tabs semi-hidden when tabs are opened after the window is maximized

### ISSUE THREAD

**Issue by tiberiuichim** [kovidgoyal/kitty#48] opened 2017-02-09 08:27 UTC
Steps to reproduce:

* opened kitty. Maximized it
* opened a new tab (ctrl+shift+t)
* switch to first tab

The second tab is now rendered ok, but switching to the first tabs shows a problem, shown in screenshot.

This is on Arch Linux with kitty-git package.

![kitty-tabs](https://cloud.githubusercontent.com/assets/141568/22774977/450f8010-eeb2-11e6-8bfd-ed632ee190a4.png)

**Comment by kovidgoyal** [comment] 2017-02-09 09:57
Yeah the tab bar rendering is a bit screwed up at the moment, I need to get around to fixing it.

**Comment by kovidgoyal** [comment] 2017-02-09 11:36
I could not reproduce your exact problem, but I committed a fix for a bug that was preventing the tab bar from being laid out properly initially. That should also fix your issue, if not feel free to re-open.

**Closed by kovidgoyal** 2017-02-09 11:36 UTC

**Comment by tiberiuichim** [comment] 2017-02-09 11:39
Indeed, now it is fixed, the problem no longer exists.
