### ISSUE TITLE
Mousewheel scrolling not working

### ISSUE THREAD

**Issue by LostKobrakai** [kovidgoyal/kitty#4828] opened 2022-03-14 09:30 UTC
**Describe the bug**
I cannot scroll with my mouse wheel, but at the same time scrolling with the touchpad of the macbook works just fine.

**To Reproduce**
1. Open new OS window
2. `cat` long file
3. Try to scroll with mouse - nothing happens
4. Try to scroll with touchpad - scrolls

The mousewheel works just fine in any other context besides kitty.

**Environment details**
```
kitty 0.24.4 created by Kovid Goyal
Darwin Lillith.fritz.box 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	12.1 BuildVersion:	21C52
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/benni/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity            0.7
font_family                   Input Mono
scrollback_lines              10000
scrollback_pager_history_size 134217728
startup_session               /Users/benni/.config/kitty/startup.conf
Colors:
	background                    #010101   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                de_DE.UTF-8
	SHELL                               /bin/zsh
	USER                                benni

```

**Additional context**
Has been reproduced with `kitty --config NONE`.

**Comment by page-down** [comment] 2022-03-14 09:44
https://sw.kovidgoyal.net/kitty/faq/#i-catted-a-binary-file-and-now-kitty-is-hung

Does the mouse wheel work when you are not executing the `cat` command?

```shell
kitty +kitten mouse_demo
```

**Comment by LostKobrakai** [comment] 2022-03-14 09:52
Doing this in a fresh window results in the same behaviour. Scrollwheel doesn't work, touchpad does.

**Comment by page-down** [comment] 2022-03-14 10:02
After running mouse_demo kitten and scrolling the wheel on the window, it doesn't show WHEEL_UP or WHEEL_DOWN, right?

What kind of mouse hardware is used?
I have not personally encountered this unless it is special hardware that is not recognized as a standard device.

@kovidgoyal 
I see that `kitty --debug-input` does not contain mouse wheel events.

**Comment by kovidgoyal** [comment] 2022-03-14 10:04
ASIDE: Dont ever cat things into a terminal. Use cat -v

@page-down Yeah never saw a need for it, since scroll events are very simple.But feel free to add some if you like.

**Comment by LostKobrakai** [comment] 2022-03-14 10:10
> After running mouse_demo kitten and scrolling the wheel on the window, it doesn't show WHEEL_UP or WHEEL_DOWN, right?
Exactly. This is a logitech MX master 3, so probably not a rare choice. 

> ASIDE: Dont ever cat things into a terminal. Use cat -v
Just for completeness. Using `cat -v` doesn't result in a difference in behaviour. So this is not the source of the problem.

**Comment by kovidgoyal** [comment] 2022-03-14 10:20
My macbook doesnt even have usb1 ports so I cant investigate, somebody with the requisite hardware needs to do it. I can say wheel events work fine with logitech mice on linux.

**Comment by kovidgoyal** [comment] 2022-03-14 10:24
Closing this as it requires special hardware to reproduce. If someone with that hardware wishes to work on this feel free to ping and I will provide any code navigation assistance.
kitty can be built from source as described here: https://sw.kovidgoyal.net/kitty/build/

**Closed by kovidgoyal** 2022-03-14 10:24 UTC
Labels: bug

**Comment by LostKobrakai** [comment] 2022-03-14 11:04
Disabling the driver deamon in the mac settings let the mouse wheel work correctly, so I guess the issue is in the logitech driver.

**Comment by DomizianoScarcelli** [comment] 2024-05-02 11:41
I had the same problem with my Mx Master and I noticed that the problem was solved by disabling the `Secure Keyboard Entry` in the top bar kitty settings
