### ISSUE TITLE
Text fails to render (linux)

### ISSUE THREAD

**Issue by nomelif** [kovidgoyal/kitty#1755] opened 2019-06-27 17:50 UTC
Installed Kitty via apt on a Ubuntu 19.04. Text appears garbled: individual letters are reversed and the command prompt isn't rendered until enter gets pressed.

![Kuvakaappaus 2019-06-27 20-48-03](https://user-images.githubusercontent.com/6322311/60288476-ec0e3980-991c-11e9-87f0-d1c62fbb92fe.png)

I don't know the kind of info that would be useful in debuging this.

**Comment by Luflosi** [comment] 2019-06-27 19:06
Duplicate of #1484. Downgrade mesa to 18.3.4 or upgrade it to 19.0.3.

**Comment by nomelif** [comment] 2019-06-27 20:18
Thank you, this did it. Sorry to bother on something that was a resolved issue, I should have looked more myself.

**Comment by Luflosi** [comment] 2019-06-27 20:53
No problem, glad I could help 😊.

**Closed** 2019-06-28 01:08 UTC
