### ISSUE TITLE
No response error when resizing window

### ISSUE THREAD

**Issue by sirex** [kovidgoyal/kitty#925] opened 2018-09-07 18:20 UTC
When I press `ctrl+shft+r` and select a resize letter I get this error:

```
'no_response'
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 229, in _handle_remote_command
    response = handle_cmd(self, window, cmd)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 22, in handle_cmd
    no_response = cmd['no_response']
KeyError: 'no_response'
```

Versions:

```
> pacman -Q python kitty
python 3.7.0-3
kitty 0.12.0-1
```

**Comment by SolitudeSF** [comment] 2018-09-07 19:51
its fixed in master https://github.com/kovidgoyal/kitty/commit/bbe8bcb28d1c363f484ebc44a56d5427d8d575b1

**Closed** 2018-09-07 21:08 UTC

**Comment by spl** [comment] 2018-09-11 11:17
Also note that this issue is a duplicate of #860 (which is helpful for cross-referencing).
