### ISSUE TITLE
Kitty freezes since update

### ISSUE THREAD

**Issue by heyoni** [kovidgoyal/kitty#1656] opened 2019-05-28 16:23 UTC
Hello,

I'm using spectacle to move windows around and I wanted to let you know I found this bug that causes the terminal to become completely unresponsive.

I'm using macos 10.14.5, kitty 0.14 with a default config as well [spectacle](https://www.spectacleapp.com/). I use my laptop monitor with 2 externals, one at a 90 degree rotation.

What happens is if I move kitty to another terminal in succession, too rapidly, it becomes unresponsive. Any process running inside continues to do so, and it actually responds to keyboard input (like ctrl-C) but doesn't update visually.

When switching to another screen, for a brief moment you'll see the terminal font/sizes look a bit weird before rendering correctly. I believe the bug is triggered by moving kitty to yet another screen before it has time to correct itself and I use spectacle's ctrl-option-cmd <- or -> shortcut.

Fix: Revert to 0.13.3

Let me know if want any more information. I'll be happy to oblige.

**Comment by Luflosi** [comment] 2019-05-28 17:16
The first half of your bug report is most likely a duplicate of #1641. @kovidgoyal fixed it already. You will either have to wait for the next release or build kitty from source (which is pretty easy to do IMHO).

**Comment by heyoni** [comment] 2019-05-28 17:38
I’ll give it a shot. There was really only one part, so I’ll close this.

**Closed** 2019-05-28 17:42 UTC

**Comment by heyoni** [comment] 2019-05-28 17:44
@Luflosi it worked, I just tested it. Sorry I missed the other issue because I only searched open ones :x
