### ISSUE TITLE
kitty hangs on exit if a disowned process has been run from it

### ISSUE THREAD

**Issue by josswright** [kovidgoyal/kitty#378] opened 2018-03-11 21:27 UTC
If I run a command in kitty and detach, such as "gvim &!"; or if I run a command directly and subsequently disown it, kitty doesn't close until the child process has also exited.

I found issue #229 relating to this from the specific pass command, and saw the discussion there. This does seem odd behaviour, though, as a general policy. I frequently run commands from the terminal that need to be detached, and keeping the parent terminal around forever doesn't seem desirable. It's certainly unexpected based on every other terminal I've used.

I saw in @kovidgoyal argue in #229 that because STDIN/STDOUT/STDERR are still directed to the terminal then it should remain open, but that does seem both non-standard and awkward for a range of everyday uses.

Could this at least be optional behaviour, if it's seen as desirable for the terminal to hang until all disowned child processes have closed? At the moment I'm having to forcibly quit terminal windows all over the place!

(Thanks for kitty, by the way. It's amazing!)

**Comment by kovidgoyal** [comment] 2018-03-12 01:46
kitty does not hang, you can close it by pressing ctrl+shift+w

And if you want to use the terminal to launch GUI programs that dont detach properly, create a launch alias and use it as described in #307

**Closed by kovidgoyal** 2018-03-12 01:46 UTC

**Comment by josswright** [comment] 2018-03-12 08:07
I see the alternatives, but needing the interactive Ctrl+Shift+W is awkward for various situations.

The other alternatives, suggested in #307, all require you to have planned ahead. Quite often it's not unusual to end up in a situation where you want to Ctrl+Z a process, then bg and disown it.

I completely understand why your preferred behaviour here is to keep the terminal open for STDIN/STDOUT, but given the expected behaviour of other terminal emulators to close in this situation, please would you consider an option? Is there a good reason not to do it?

**Comment by josswright** [comment] 2018-03-12 08:53
Just as an additional argument here, I think it does make more logical sense for the terminal to close even when disowned processes are still outputting to it. The logic is that the controlling factor should be the shell's jobs list. The entire purpose of `disown` is to remove a job from the shell's jobs list. What's the purpose of `disown` existing if the terminal doesn't let go of the process after that?

I really hope you'll consider adding this option! Given that this is the normal behaviour for terminal emulators, there are a lot of old scripts and bits of code floating around out there that will rely on this behaviour, which isn't necessarily 'right' or 'wrong'. That's going to cause a lot of problems for people running those scripts in kitty.

I can see from your other threads on this that you don't see the point of this. I think I've given a few examples here:
- Handling processes that you've already started, then have later ctrl+z and disowned. (Could be handled by a Shift+Ctrl+W, but that is taking the logical 'end this shell' and replacing it with 'close this window'. It seems problematic to train people to close terminal windows that might contain jobs. Using `exit`, or Ctrl+d, is more consistent with job control rather than window operations.)
- Maintaining the logic of the `disown` command and the shell's jobs list. `disown` is specifically written to remove the process from the shell's list of jobs; it seems inconsistent for the terminal to override this.
- Practically: there are plenty of old scripts and programs that, rightly or wrongly, rely on this behaviour. It's not practical for end users to fix these. I suspect that this will cause more bug reports in the future along the lines of bug #229. Importantly, these programs weren't doing anything harmful or broken or dangerous -- they worked fine in other terminal emulators.

I hope you'll consider at least making closing when the jobs list is empty an option. Is there a strong reason why the terminal should definitely *not* support this? Given that it's normal in other terminal emulators -- every one that I've used -- is there a common harmful behaviour that it causes?

Thanks again for kitty!

**Comment by kovidgoyal** [comment] 2018-03-12 12:01
Sure there is a harmful behavior. It means that if the disowned process writes to stdout/stderr or reads from stdin, it will fail, and it will do so in a way that is impossible to diagnose. Now many badly written/old programs just ignore errors writing to stdout/stderr, but many do not. For instance, any program written in python will raise an exception when writing to stdout/stderr if it has been disowned. You (and by that I mean the generic you) really should not be using disown as a way to run programs even after their owning terminal is closed.

It's unfortunate that many people dont understand this, but, I think it is worth educating them.

**Comment by josswright** [comment] 2018-03-12 13:08
The thing is, this isn't going to educate users who have no control over this; all that's happening is that kitty starts behaving oddly for a large class of people. (By 'oddly', I mean that it sits there on screen largely blank when any other terminal would correctly exit.) It was enough, when I first saw it, that I assumed it was a genuine hang. I only found this issue because I took the time to track it down.

Is it really worth that inconvenience for people who want to use kitty just on a point of principle? Isn't the fact that every other terminal emulator (barring possible exceptions I've never heard of) handles things this way a reasonable argument that it's useful? This seems to be focusing on the very few who are developers, or who might be able to escalate this issue to other software projects, rather than the vast majority of 'normal' users who just want to use the terminal in a normal way.

I still don't see a good reason why this couldn't be an optional behaviour -- default off if necessary -- that allows people to override this. Disowning a process is a well-established behaviour. I really don't see why you'd want to break that without an option of allowing it? The 'harmful' behaviour you've quoted above is just an abstract -- have you ever seen a program failing badly and harmfully due to this?

Given your argument above, should you not also intercept ctrl+shift+w and refuse to close the window if there are programs running? Why is that behaviour allowed, but not disowning processes?

Again, I'd agree if you wanted to make the current behaviour the default, but I really don't understand why you'd want to prevent anyone from having the option.

If you're absolutely, finally, unwilling to consider this even as an option for users that want it, would you be willing to point me to the right part of the code so that I can maintain a local patch for my own benefit? I came across kitty a few weeks ago and it had absolutely everything I wanted in a terminal, until I discovered this odd behaviour. I'd love to stay using kitty, even if that means maintaining my own tweak to the code.

**Comment by kovidgoyal** [comment] 2018-03-12 14:37
How would an option help things? Your proverbial grandma user would still need to find the option somehow. And many terminals do this because it is the easy thing to do, not because it is the right thing to do. I have spent my life doing things differently from the way "most people" do them, if I feel most people are wrong, you aren't going to convince me with that argument.

And yes, I have seen many programs break badly because of this. I have even written such programs and had to waste my time explaining to people why launching programs with disown is a broken paradigm that needs to die in a fire.

The option would help only people that are determined to do the wrong thing, regardless of the consequences. And those people impose large negative externalities on all maintainers of software. They now have to waste time making sure their programs are robust against frequently broken stdout/stderr/stdin. 

You are welcome to patch your copy of kitty. Look for the SIGCHLD signal handler, add code to track dead processes in some signal safe memory structure, and then add code to child-monitor.c to check that structure on every tick and close windows that have dead child processes.

**Comment by kovidgoyal** [comment] 2018-03-12 16:26
Since this issue caused me to lookup the signal handling code anyway, I cleaned it up, it is now a one line patch. Just changes reap_children(self, false) to reap_children(self, true)

**Comment by josswright** [comment] 2018-03-12 20:11
Thanks! Really appreciated.

**Comment by barraponto** [comment] 2019-06-17 15:10
In the spirit of "doing the right thing", is there a way to figure out what processes are holding kitty up? I'd love to see them listed if the terminal window stays alive after closing the shell process.

**Comment by kovidgoyal** [comment] 2019-06-17 15:26
Well, in theory you could use fuser to track it down given the numbers
of the fd, which you can have kitty print out on child death.

**Comment by nocturn9x** [comment] 2021-07-12 19:43
I honestly don't really like the attitude of the developer of this project towards the community. It's a "you either behave like I intend you to or go fuck yourself". Good thing this is FOSS, might fork it to make it actually behave how it makes sense rather than how it should in theory. The owner of this project fails to understand the importance of what he created and still holds on his matters of principle like a rock, such a childish behavior indeed

**Comment by nocturn9x** [comment] 2021-07-12 19:48
> How would an option help things? Your proverbial grandma user would still need to find the option somehow. And many terminals do this because it is the easy thing to do, not because it is the right thing to do. I have spent my life doing things differently from the way "most people" do them, if I feel most people are wrong, you aren't going to convince me with that argument.
> 
> And yes, I have seen many programs break badly because of this. I have even written such programs and had to waste my time explaining to people why launching programs with disown is a broken paradigm that needs to die in a fire.
> 
> The option would help only people that are determined to do the wrong thing, regardless of the consequences. And those people impose large negative externalities on all maintainers of software. They now have to waste time making sure their programs are robust against frequently broken stdout/stderr/stdin.
> 
> You are welcome to patch your copy of kitty. Look for the SIGCHLD signal handler, add code to track dead processes in some signal safe memory structure, and then add code to child-monitor.c to check that structure on every tick and close windows that have dead child processes.

Your argument doesn't even make sense. Why do you think `disown` even exists? Also, another rant: with other terminal emulators I usually start processes in the background using `command-here &>/dev/null &` and expect that even if I close the terminal, that process will keep running in the background. For some reason, kitty kills the process before exiting and that's so annoying I can't even phrase it. I'm sorry this is one of the few terminals supporting a wide variety of colored outputs because this is the only reason I'm sticking to it. Is there any religious reason for this nonsense as well? just wondering

**Comment by Luflosi** [comment] 2021-07-12 19:52
Nobody is stopping you from forking kitty. If you prefer some behaviour that is not implemented then by all means go ahead and fork it.
Ranting about these things and attacking the maintainer is not productive. Go ahead and implement it in your fork. That's more productive.

**Comment by nocturn9x** [comment] 2021-07-12 20:05
> Nobody is stopping you from forking kitty. If you prefer some behaviour that is not implemented then by all means go ahead and fork it.
> Ranting about these things and attacking the maintainer is not productive. Go ahead and implement it in your fork. That's more productive.

That's probably what I'm gonna do, yes, but since the maintainer of the repository seems to enjoy ranting so much at every issue on his repo like we're trying to personally attack him I figured I'd join the party. Also, this is not how a proper FOSS project should be managed. Adding an option is nothing hard, fragmenting the ecosystem with thousands of forks all implementing minor features that the maintainer couldn't be arsed to add because of some sort of religious belief apparently sounds better to you and anyone here so oh well

**Comment by trygveaa** [comment] 2021-07-12 20:59
> Also, another rant: with other terminal emulators I usually start processes in the background using command-here &>/dev/null & and expect that even if I close the terminal, that process will keep running in the background. For some reason, kitty kills the process before exiting and that's so annoying I can't even phrase it.

I can't reproduce. kitty doesn't kill any application started that way for me. Though, note that if you use zsh, zsh will kill it unless you use `&!`.

**Comment by nocturn9x** [comment] 2021-07-12 21:37
> > Also, another rant: with other terminal emulators I usually start processes in the background using command-here &>/dev/null & and expect that even if I close the terminal, that process will keep running in the background. For some reason, kitty kills the process before exiting and that's so annoying I can't even phrase it.
> 
> I can't reproduce. kitty doesn't kill any application started that way for me. Though, note that if you use zsh, zsh will kill it unless you use `&!`.

Whoops, my bad. Just recently switched from bash to zsh and I didn't know this was a thing, I apologize!

**Comment by kovidgoyal** [comment] 2021-07-13 01:48
> I honestly don't really like the attitude of the developer of this project towards the community. It's a "you either behave like I intend you to or go fuck yourself". Good thing this is FOSS, might fork it to make it actually behave how it makes sense rather than how it should in theory. The owner of this project fails to understand the importance of what he created and still holds on his matters of principle like a rock, such a childish behavior indeed

Hey moron, there is already an option for this, https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.close_on_child_death  

And I honestly dont really like the attitude of entitled leeches like you. You have been banned.
