### ISSUE TITLE
kitty Support for Raspberry Pi 4

### ISSUE THREAD

**Issue by terrywang** [kovidgoyal/kitty#3015] opened 2020-10-07 08:39 UTC
**kitty support for Raspberry Pi 4**

First, let me take the opportunity to show my gratitude for your work on moving the terminal emulator ecosystem forward.

Really appreciate it. Just love kitty (the cat). I've been a one off supporter already (will do more later). Than you, Kovid.

### TL;DR

Recently I started using the Raspberry Pi 4 8GB as my sidecar workstation (less heat and noise), to replace the old `MacBook3,1` (with SSD but many minor issues running Linux).

Pi 4 is officially OpenGL ES 3.1 conformant (was 2.0), however, based on my research (searched for previous ARM / AArch64 issues) `kitty` requires OpenGL ES 3.3.

Pi 4 8GB is powerful enough to run KDE Plasma (Manjaro ARM) with all `KWin` eye-candies (like the old days using GNOME 2 + Compiz) on, compositor rendering backend set to OpenGL 3.1, it's smooth (better than my MacBook3,1 running Manjaro x86_64). So I guess hardware spec (Broadcom VideoCore IV) is powerful enough, however, the AArch64 driver

The ask (for all other Pi 4 users running Linux as workstations): Is it possible to add backward compatibility before the Pi 4 is OpenGL 3.3 comformant?

As Vulkan driver for Pi 4 is coming, should we wait for that to land (easier if kitty already supports vulkan)? Vulkan is the way forward anyway. TIA.

**To Reproduce**
1. build kitty from source 0.19.1 (to rule out packaging issues, turned out to be the same)
2. launch it from another console (tty) or terminal emulator
3. boom

**Expected behavior**
kitty starts normally like it does on Arch Linux / Manjaro x86_64.

**Screenshots**
NA

**Environment details**
OS: Manjaro ARM `Aarch64`

debug info

```bash
terry@manjaro:~$ kitty --debug-config
kitty 0.19.1 created by Kovid Goyal
Linux manjaro 5.8.9-1-MANJARO-ARM #1 SMP PREEMPT Wed Sep 16 10:28:12 CDT 2020 aarch64
Manjaro Linux \r (\l)
DISTRIB_ID=Manjaro-ARM
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=
DISTRIB_DESCRIPTION="Manjaro ARM Linux"
Loaded config files: /home/terry/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background           Color(red=44, green=44, blue=44)
color1               Color(red=241, green=119, blue=121)
color10              Color(red=153, green=204, blue=153)
color11              Color(red=255, green=204, blue=102)
color12              Color(red=102, green=153, blue=204)
color13              Color(red=204, green=153, blue=204)
color14              Color(red=102, green=204, blue=204)
color15              Color(red=255, green=254, blue=254)
color2               Color(red=153, green=204, blue=153)
color3               Color(red=255, green=204, blue=102)
color4               Color(red=102, green=153, blue=204)
color5               Color(red=204, green=153, blue=204)
color6               Color(red=102, green=204, blue=204)
color7               Color(red=255, green=254, blue=254)
color8               Color(red=0, green=0, blue=0)
color9               Color(red=241, green=119, blue=121)
font_family          Iosevka Term
font_size            12.0
foreground           Color(red=204, green=204, blue=204)
selection_background Color(red=80, green=80, blue=80)
selection_foreground Color(red=44, green=44, blue=44)


terry@manjaro:~$ kitty --debug-gl
[281 19:17:12.375817] [glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig
[281 19:17:12.375979] Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.
```

`glxinfo` output
```bash
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_no_error, 
    GLX_ARB_create_context_profile, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_libglvnd, GLX_EXT_no_config_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, GLX_OML_swap_method, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
    GLX_EXT_create_context_es_profile, GLX_EXT_fbconfig_packed_float, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_no_error, 
    GLX_ARB_create_context_profile, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
    GLX_EXT_create_context_es_profile, GLX_EXT_fbconfig_packed_float, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
```

**Comment by Luflosi** [comment] 2020-10-07 08:42
Duplicate of #2790.

**Comment by kovidgoyal** [comment] 2020-10-07 08:44
Yes, kitty requires OpenGL 3.3. I'm not interested in complexifying the
code for OpenGL 3.1 as there are various niceties from 3.3 (which is a
decade old) that kitty uses.

Your best bet is indeed Vulkan. It is on my TODO list to port kitty to
run on Vulkan. If you wish to move that effort forward patches are most
welcome. If so please open a separate issue to track Vulkan progress.

**Closed by kovidgoyal** 2020-10-07 08:44 UTC
Labels: bug

**Comment by terrywang** [comment] 2020-10-07 08:46
Thank you @kovidgoyal for the input. Really glad to see Vulkan suport is on the ToDo list ;-)
