### ISSUE TITLE
Unable to switch tabs or select text with the mouse cursor after switching apps without moving the cursor

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1103] opened 2018-10-28 13:22 UTC
I only tested this on macOS.

Steps to reproduce the issue:
1. Open kitty
2. Create a new tab
3. Make sure that the kitty window is completely visible, not obscured by other windows
4. Make sure kitty does not have focus by clicking on the desktop for example
5. Hover over the kitty tab that is not active
6. Click once to focus the window
7. Do NOT move the cursor!
8. Another click should switch to the tab under the cursor but it doesn't
9. Move the mouse cursor at least one pixel
10. The tab can now be properly clicked on again

The same problem also occurs when trying to select text with a double or triple click (three or four clicks when also counting the initial click to focus the window) when kitty is not focused at first and the mouse isn't moved after kitty gets focus. It is not enough to just switch to a different kitty OS window to reproduce the issue, the kitty app has to loose focus entirely (no "kitty" text next to the apple logo in the top left corner). kitty seems to have an incorrect mouse cursor position when getting focus again as long as the cursor hasn't moved. The fix might be as simple as doing whatever happens when the mouse cursor is moved every time kitty gets focus again.

**Comment by martinetd** [comment] 2018-10-28 21:47
I don't use tabs so I'm not 1005 sure but I think it's a cousin of what I fixed with [a recent commit](https://github.com/kovidgoyal/kitty/commit/ec51a219a7a14e757dfcddc6c8e7c80202ca2187) - you probably need to copy over the os window x/y on tab change, there should be a point where you have access to both windows?
Ah it's slightly different, the problem is `mouse_cell_x/y` only gets update in `handle_move_event()` (the os window is unique so its x/y are fine, but the Window that is per tab doesn't have the right mouse cell values... Although we do have access to both old and new tab in `set_active_tab` so the idea is the same... Probably need to add a fixup function to call, `window_for_event` has code to figure how to get window from os window's `tabs` + `active_tab`
Actually if you use a split os window it probably has the same issue if you switch with key bindings and not move mouse at all?

**Comment by Luflosi** [comment] 2018-10-29 22:43
Yeah, this seems to be very similar to your commit.
Did anyone test this on wayland?
Maybe the proper place to update the position when the window gets focus again is in `focus_in_event()` or `enter_event()` in `mouse.c`, that way it would be updated for macOS, X11 and Wayland. How would you get the cursor position there? Also, what happens when kitty starts? When is the mouse position updated then? It seems to get updated at some point, even when the cursor hasn't moved since kitty started.

**Comment by martinetd** [comment] 2018-10-29 23:22
>  Did anyone test this on wayland?

wayland didn't have the problem I fixed earlier, I didn't check the code but I checked on sway.

> [...] `focus_in_event()` [...] How would you get the cursor position there?

I think that's only called for os window, so wouldn't help for tab switch.

> Also, what happens when kitty starts? When is the mouse position updated then? It seems to get updated at some point, even when the cursor hasn't moved since kitty started.

When kitty starts, you get an event from the OS window (the one I added for X11, actually; wayland handled this before, not sure about X11) -- it doesn't need anything special, it just calls the move event.

We could also call the move event in `set_active_tab` or just copy the values as I suggested, I think that's the most logical place really. If you want to call move event, you "just" need to pick the `Window` from `os_window` and active tab number, then the window from it (`tab = os_window->tabs + os_window->active_tab; w = tab->windows + tab->active_windows`, if `tab->num_windows > 0`); I just don't really like that because it needs exposing the `handle_move_event` function out of mouse.c, but it's probably better than copying the values and forgetting something else...

**Comment by kovidgoyal** [comment] 2018-10-30 10:16
basically this problem will happen anytime the window layout changes, which can happen when changing tabs or changing layouts.

**Comment by Luflosi** [comment] 2018-10-30 10:48
Just to make sure we understand each other: I only had problems when moving the mouse while kitty does not have focus. The cursor position does not seem to get updated after kitty gains focus again as long as the mouse cursor didn't move yet.

**Comment by martinetd** [comment] 2018-10-30 11:43
Ah, my bad, that's not what I had understood. We're talking about something else then (that also is a problem if you change tab/layout through keybindings without moving the cursor for example).

For your case I guess it's missing an update on enter event like it did on X11, so I understand what you were saying better now. I think it has to come from the lowest level though (e.g. can't have this in the common code as you suggested, because you wouldn't have access to the event's x/y there)
I'm not familiar with what's available in the event in e.g. `mouseEntered` from `cocoa_window.m` and I don't speak objective C but maybe you can add something similar to `mouseMoved` in there...

**Comment by kovidgoyal** [comment] 2018-10-30 15:19
I dont currently have access to test this, but assuming that mouseEntered is fired by AppKit when a window gets focus withthe mouse already over it, then this should do the trick


```diff
diff --git a/glfw/cocoa_window.m b/glfw/cocoa_window.m
index cc5b068f..42135c59 100644
--- a/glfw/cocoa_window.m
+++ b/glfw/cocoa_window.m
@@ -713,6 +713,9 @@ static GLFWapplicationshouldhandlereopenfun handle_reopen_callback = NULL;
         hideCursor(window);
 
     _glfwInputCursorEnter(window, GLFW_TRUE);
+    const NSPoint pos = [event locationInWindow];
+    const NSRect contentRect = [window->ns.view frame];
+    _glfwInputCursorPos(window, pos.x, contentRect.size.height - pos.y);
 }
 
 - (void)viewDidChangeBackingProperties
```

**Comment by Luflosi** [comment] 2018-10-30 20:09
mouseEntered is fired whenever the mouse cursor enters the region of the screen where the kitty window is not obstructed by another window. The window title bar thingy (the section of the window with the window title and the three buttons) does not seem to count as part of the window for this event. Your patch only works in certain edge cases because your assumption was not correct.
Here is my patch that seems to work:
```diff
diff --git a/glfw/cocoa_window.m b/glfw/cocoa_window.m
index d5e5de1e..dad37ccc 100644
--- a/glfw/cocoa_window.m
+++ b/glfw/cocoa_window.m
@@ -454,6 +454,13 @@ static const NSRange kEmptyRange = { NSNotFound, 0 };
         centerCursor(window);
 
     _glfwInputWindowFocus(window, GLFW_TRUE);
+
+    double x = 0.0;
+    double y = 0.0;
+    _glfwPlatformGetCursorPos(window, &x, &y);
+    _glfwInputCursorPos(window, x, y);
+    printf("windowDidBecomeKey %f %f\n", x, y);
+
     updateCursorMode(window);
 }
```
`_glfwPlatformGetCursorPos()` can return coordinates outside the window. Is that correctly handled or does it cause issues? And should the lines I added be after `updateCursorMode()` or before `_glfwInputWindowFocus()`? Or could it be better to do it _in_ `_glfwInputWindowFocus()`? If this looks good, I can make a pull request (ofc without the `printf()`).

**Closed** 2018-10-31 03:08 UTC
