### ISSUE TITLE
kitty sometimes can not handle continue press the same key event from version 0.25.2

### ISSUE THREAD

**Issue by ttys3** [kovidgoyal/kitty#5408] opened 2022-08-24 05:27 UTC
**Describe the bug**

this is a bit difficult to description.

when in kitty, continue press any key (do not release it), it should continue accept the key event.
but from version 0.25.2, I have problems on this. the problem does not occur every time.
I do not know how to re-produce, but this happend to me every day.

**To Reproduce**
1. install kitty 0.25.2
2. run a long time
3. continue press any key (do not release it) can only got one key event handled.
4. exit kitty and start kitty again the problem is gone
5. fallback to kitty old versoin before 0.25.2, no such problem

**Screenshots**

**Environment details**
```
kitty 0.25.2 created by Kovid Goyal
Linux work 5.19.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 21 Aug 2022 18:55:22 +0000 x86_64
Arch Linux 5.19.3-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/ttys3/.config/kitty/kitty.conf

Config options different from defaults:
allow_remote_control       y
dynamic_background_opacity True
enabled_layouts            ['splits', 'stack', 'fat', 'tall', 'grid']
font_family                Iosevka Term
scrollback_lines           8000
startup_session            /home/ttys3/.config/kitty/session.conf
tab_bar_style              powerline
tab_title_template         {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}:{'🇿' if layout_name == 'stack' and num_windows > 1 else ''}{title}
term                       xterm-256color
Added mouse actions:
	ctrl+left click ungrabbed → mouse_handle_click selection link prompt
	ctrl+left press ungrabbed → mouse_selection normal
Removed mouse actions:
	left click ungrabbed → mouse_handle_click selection link prompt
Changed mouse actions:
	right press ungrabbed → copy_to_clipboard
Added shortcuts:
	f3 → kitten hints --program '*'
	f4 → launch --location=split
	f7 → layout_action rotate
	f11 → toggle_fullscreen
	shift+left → move_window left
	shift+right → move_window right
	shift+up → move_window up
	shift+down → move_window down
	alt+left → resize_window narrower
	alt+right → resize_window wider
	alt+up → resize_window taller
	alt+down → resize_window shorter 3
	ctrl++ → change_font_size all +2.0
	ctrl+- → change_font_size all -2.0
	ctrl+0 → change_font_size all 0
	ctrl+= → change_font_size all +2.0
	ctrl+a > space → kitten hints --alphabet asdfqwerzxcvjklmiuopghtybn1234567890 --customize-processing custom-hints.py
	ctrl+a > , → set_tab_title
	ctrl+a > - → launch --location=hsplit --cwd=last_reported
	ctrl+a > . → move_window_forward
	ctrl+a > 0 → goto_tab 10
	ctrl+a > 1 → goto_tab 1
	ctrl+a > 2 → goto_tab 2
	ctrl+a > 3 → goto_tab 3
	ctrl+a > 4 → goto_tab 4
	ctrl+a > 5 → goto_tab 5
	ctrl+a > 6 → goto_tab 6
	ctrl+a > 7 → goto_tab 7
	ctrl+a > 8 → goto_tab 8
	ctrl+a > 9 → goto_tab 9
	ctrl+a > [ → previous_window
	ctrl+a > \ → launch --location=vsplit --cwd=last_reported
	ctrl+a > ] → next_window
	ctrl+a > c → launch --cwd=last_reported --type=tab
	ctrl+a > d → debug_config
	ctrl+a > e → launch --type=tab nvim ~/.config/kitty/kitty.conf
	ctrl+a > h → neighboring_window left
	ctrl+a > j → neighboring_window down
	ctrl+a > k → neighboring_window up
	ctrl+a > l → neighboring_window right
	ctrl+a > q → focus_visible_window
	ctrl+a > r → combine : load_config_file : launch --type=overlay --hold --allow-remote-control kitty @ send-text "kitty config reloaded"
	ctrl+a > s → launch --type=overlay --hold --allow-remote-control ~/.config/kitty/dump-sesison.sh
	ctrl+a > t → kitten themes
	ctrl+a > x → close_window
	ctrl+a > z → kitten zoom_toggle.py
	ctrl+a > ctrl+a → send_text all \x01
	ctrl+q → close_os_window
	ctrl+left → neighboring_window left
	ctrl+right → neighboring_window right
	ctrl+up → neighboring_window up
	ctrl+down → neighboring_window down
	ctrl+home → resize_window reset
	ctrl+kp_subtract → change_font_size all -2.0
	ctrl+kp_add → change_font_size all +2.0
Removed shortcuts:
	ctrl+shift+enter → new_window
Changed shortcuts:
	ctrl+shift+t → new_tab_with_cwd
Colors:
	background                 #323232   
	color0                     #252525   
	color1                     #be7472   
	color10                    #97bb98   
	color11                    #fefdbc   
	color12                    #9fbdde   
	color13                    #989abc   
	color14                    #6fbbbc   
	color15                    #feffff   
	color2                     #709772   
	color3                     #989772   
	color4                     #7199bc   
	color5                     #727399   
	color6                     #719899   
	color7                     #7f7f7f   
	color8                     #555555   
	color9                     #ff9900   
	cursor                     #c7c7c7   
	cursor_text_color          #feffff   
	foreground                 #c8c8c8   
	selection_background       #c1ddff   
	selection_foreground       #3e3e3e   

Important environment variables seen by the kitty process:
	PATH                                /usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/ttys3/.local/share/JetBrains/Toolbox/scripts:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin
	LANG                                en_US.UTF-8
	VISUAL                              nvim
	EDITOR                              nvim
	SHELL                               /usr/bin/zsh
	GLFW_IM_MODULE                      ibus
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                ttys3
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
	XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/ttys3
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_DATA_DIRS                       /home/ttys3/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

```

**Additional context**

os: ArchLinux
dual screen user Resolution: 3840x2160 
Shell: zsh 5.9
DE: GNOME 42.4
WM: Mutter
WM Theme: Adwaita
GPU: NVIDIA GeForce GTX 1650

**Comment by kovidgoyal** [comment] 2022-08-24 05:30
duplicate of #5188

**Closed by kovidgoyal** 2022-08-24 05:30 UTC
Labels: bug
