### ISSUE TITLE
Gnome Shell Window Manager Issues

### ISSUE THREAD

**Issue by t-gerhard** [kovidgoyal/kitty#1680] opened 2019-06-04 09:30 UTC
Until recently, kitty integrated well into my gnome shell: Just a plain window with regular window title bar and borders. However, since the release 0.14.0, there seem to be problems.

I don't know

**System**: Arch Linux (package from community repository)

**Expected (reverted to 0.13.3 to confirm that kitty is the issue):**
![image](https://user-images.githubusercontent.com/986924/58867507-df4e4b00-86ba-11e9-8741-90e5376f4fee.png)
Kitty in a default gnome-shell window with right-click menu as well as custom mouse button shortcuts working.

**Actual behavior (0.14.1)**
![image](https://user-images.githubusercontent.com/986924/58867681-2c322180-86bb-11e9-88ef-55399be69d46.png)
You can see that the window title bar as well as borders are messed up. There is a system right-click menu available, but my middle-mouse-button minimize shortcut isn't working.
There is also an issue with **resizing**: The window grows about a title bar height whenever it loses focus or gets focus. Resizing also has a strange behavior.

**Additional findings**
Resetting my config (i.e., deleting the user config file) repaired the resizing behavior, but the strange window layout and non-working middle-mouse-button are still present.

**Comment by Luflosi** [comment] 2019-06-04 09:50
Duplicate of #1645. Try the workaround in https://github.com/kovidgoyal/kitty/issues/1645#issuecomment-496221126.
The issue is caused by kitty enabling Wayland support by default in 0.14.0.
I had the same weird resizing behaviour using Wayland, hopefully @kovidgoyal finds a fix soon.

**Comment by kovidgoyal** [comment] 2019-06-04 09:54
There is no fix to be had -- GNOME have created this problem, they need
to fix it. I am afraid I have no interest in re-implementing the window
manager's functionality in kitty just because GNOME developers are too
stubborn to add support for server side window decorations to mutter,
despite the fact that they *already have to have it* to support
XWayland.

In the meantime, simply set KITTY_DISABLE_WAYLAND=1 and use it under
XWayland.

**Closed by kovidgoyal** 2019-06-04 09:54 UTC
