### ISSUE TITLE
Weird bug when resizing the window

### ISSUE THREAD

**Issue by dmerejkowsky** [kovidgoyal/kitty#2762] opened 2020-06-13 12:46 UTC
***Describe the bug**
Sometimes when resizing the window I see some strange output

**To Reproduce**
* Build kitty from source
* Run kitty 
* Resize the window like crazy a bunch of time

**Screenshots**

![kitty-bug](https://user-images.githubusercontent.com/606755/84569060-0470a180-ad84-11ea-8499-d66bdf41ed10.png)

**Enviroment details**
OS: Arch Linux

```
kitty 0.17.4 created by Kovid Goyal
Linux bermudes 5.7.2-arch1-1 #1 SMP PREEMPT Wed, 10 Jun 2020 20:36:24 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/dmerej/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background_opacity   0.8
color1               Color(red=240, green=76, blue=65)
enable_audio_bell    False
font_size            9.0
remember_window_size False
Changed shortcuts:
	shift+control+t KeyAction(func='kitten', args=['hints'])
```

**Additional context**
Happened after a big update - so it' s hard to pinpoint the package responsible for the bug, if ay.

I have no clue about how to debug this, nor how to look for similar bugs (what search keywords should I use?) so I appreciate any help ..

**Comment by kovidgoyal** [comment] 2020-06-13 13:47
dupe of #2747

**Closed** 2020-06-13 13:51 UTC
Labels: bug

**Comment by dmerejkowsky** [comment] 2020-06-13 14:05
Cool, nice to know this is a known bug :)

**Comment by travankor** [comment] 2020-06-15 20:58
I wonder if this is caused by the new mesa update (20.1.1).

**Comment by Luflosi** [comment] 2020-06-15 21:01
Most likely not. This should be fixed in the latest master. You can try to build from source: https://sw.kovidgoyal.net/kitty/build.html.
