### ISSUE TITLE
CTRL-C does not work anymore

### ISSUE THREAD

**Issue by gorillamoe** [kovidgoyal/kitty#1812] opened 2019-07-19 16:05 UTC
I'm on 

```
marco@arcade:~$ kitty -v
kitty 0.14.2 created by Kovid Goyal
```

and I noticed that CTRL-C stopped working. It worked before, but after I updated it somehow stopped working.

I checked if other terminals are affected (because I thought it might be some OS Level keybinding), but Gnome Terminal and URXVT still work fine.

Any help appreciated.

**Comment by Luflosi** [comment] 2019-07-19 22:09
There is a very similar issue: #1806 (which is already fixed in the latest master). That issue was however caused by commit 547132131a90318867196a125a3d9b5ab2225b0a, which is not in the 0.14.2 release.
Did you install kitty from source? If not, how did you install kitty?

**Comment by gorillamoe** [comment] 2019-07-22 06:52
I'm using this [Arch User repo one](https://aur.archlinux.org/packages/kitty-git/).

Last update was 2019-07-04 22:36 and the commit you referenced is from 2019-07-05, so it might be already fixed. I will build master from scratch and see if it's fixed.

Thanks a lot! :)

**Closed** 2019-07-22 08:01 UTC

**Comment by walialu** [comment] 2019-07-31 11:50
Indeed, building from source fixed the issue. Thanks a lot!
