### ISSUE TITLE
Off-by-one error when selecting text

### ISSUE THREAD

**Issue by hakonrk** [kovidgoyal/kitty#1616] opened 2019-05-16 08:53 UTC
After double-clicking a word to start a selection, and growing the selection by moving the mouse cursor beyond the end of the initially selected word, the selection grows to one character beyond the mouse cursor. Example:

```
foo[bar]=1
```

Let's say you want to select only `foo[bar]`. You start by double-clicking on `foo`, thereby highlighting only that word (using the default `select_by_word_characters` setting). Then you drag the mouse to the closing bracket to also include `[bar]` in the selection. The result is that the selection also includes the following `=` character. I don't see any way to select only `foo[bar]`.

**Comment by hakonrk** [comment] 2019-05-16 08:58
Just noticed that this could be a duplicate of #945.

**Comment by hakonrk** [comment] 2019-05-16 09:13
Tried cherry-picking the four patches in martinetd's selection branch (#1007) onto the master branch. They had no effect on the issue I describe in this ticket.

**Comment by martinetd** [comment] 2019-05-16 09:17
What's your `select_by_word_characters` ? By default it includes `=`, so the equal sign is just part of the word for kitty.

**Comment by hakonrk** [comment] 2019-05-16 09:21
It makes no difference. I tried removing the `=` from `select_by_word_characters` and the same thing happens. There are many ways to reproduce this bug. The easiest is using spaces:
```
foo   bar
```
Double-click `foo`, then drag the selection towards `bar. Observe that, while moving over the spaces, the selection is always one character too wide when you hover the mouse over the spaces (or any other non-word character for that matter).

**Comment by trygveaa** [comment] 2019-05-16 09:39
I'm also seeing this. I don't think it's a duplicate of #945 because it's not just that it selects the next word too early, but you can also get a selection which doesn't include whole words.

E.g. with the text `some words`, if you double-click on `some` and drag the mouse to the right, the selections will be `some`, then `some w` and at last `some words`. The selection `some w` should never have been active, it should go directly from `some` to `some words`.

**Comment by hakonrk** [comment] 2019-05-16 12:50
Just wanted to clarify my answer to martinetd's question, quoted below:

> What's your `select_by_word_characters` ? By default it includes `=`, so the equal sign is just part of the word for kitty.

When I said it did not matter what I put in `select_by_word_characters`, I was talking about how kitty behaved on the master branch. With the four patches on your selection branch cherry-picked to master, removing the `=` character from `select_by_word_characters` makes it possible to select `foo[bar]` without including the `=` character immediately following the closing bracket.

**Closed** 2019-05-16 13:02 UTC

**Comment by hakonrk** [comment] 2019-05-16 13:22
kovidgoyal, thanks for the patch. It changes the way selection works for this issue, but sadly it still doesn't make it possible to include an arbitrary number of non-word characters in the selection. Here's another example:

```
matrix[x][y]
```

Double-click on `matrix`, then try to grow the selection to `matrix[x]`. With patch 5f33d90, non-word characters never affect the selection, it does not grow until the mouse cursor reaches the next word character.

**Comment by kovidgoyal** [comment] 2019-05-16 13:54
Well, yeah. Why would word selection allow you to select non-word
characters? If you want to select them, either use non-word selection
mode or add the characters you are interested in to the list of
characters consisting of word characters.

**Comment by hakonrk** [comment] 2019-05-16 14:13
That's the way it works in xterm, gnome-terminal and konsole (maybe more, didn't bother to check others). It makes sense in my opinion, because I typically want to copy whole words and one or more non-word characters following the word, as shown in my matrix example.  Word selection doesn't mean the selection should be delimited by words, and why change the behavior compared to all(?) other terminal emulators?

**Comment by kovidgoyal** [comment] 2019-05-16 14:50
OK, I dont see an issue with doing that.

**Comment by hakonrk** [comment] 2019-05-16 15:59
I have played around with it a little bit, and here's a patch that I've applied on top of 5f33d907aaf42e88d45ab421e66b62db2052a1b6. It seems to make kitty do word selection the same as other terminal emulators, but it's barely been tested, and I don't claim to fully understand the code I'm modifying, so it might have some unintended side effects.
```diff
diff --git a/kitty/screen.c b/kitty/screen.c
index f5f68570..970c61f0 100644
--- a/kitty/screen.c
+++ b/kitty/screen.c
@@ -2013,7 +2013,10 @@ screen_selection_range_for_word(Screen *self, index_type x, index_type *y1, inde
     Line *line = visual_line_(self, *y1);
     *y2 = *y1;
 #define is_ok(x) (is_word_char((line->cpu_cells[x].ch)) || is_opt_word_char(line->cpu_cells[x].ch))
-    if (!is_ok(x)) return false;
+    if (!is_ok(x)) {
+        *e = x;
+        return true;
+    }
     start = x; end = x;
     while(true) {
         while(start > 0 && is_ok(start - 1)) start--;
```

**Comment by hakonrk** [comment] 2019-05-16 16:30
Should probably also set the start value, `*s = x`, before returning.

**Comment by kovidgoyal** [comment] 2019-05-17 01:24
Umm this is already implemented in master. https://github.com/kovidgoyal/kitty/commit/9849a69afddc33f33a002182704ea20a12928ee3

**Comment by hakonrk** [comment] 2019-05-17 04:30
Yes, I noticed that after I had posted it. :) Thanks again for fixing this! :+1:
