### ISSUE TITLE
Glitches and artifacts when resizing kitty window on i3-gaps

### ISSUE THREAD

**Issue by amalcew** [kovidgoyal/kitty#2769] opened 2020-06-16 20:21 UTC
**Description**
Strange behavior of kitty when resizing windows or entering full-screen mode, random glitches 'floating' above the terminal's output

**To Reproduce**
1. Open two or more kitty windows on i3-gaps
2. Resize one of windows
3. See error

**Screenshots**
![2020-06-16-21-42-18](https://user-images.githubusercontent.com/37713672/84823362-7c59f880-b01e-11ea-8f32-4077f7b10e39.png)
![2020-06-16-22-11-00](https://user-images.githubusercontent.com/37713672/84823365-7e23bc00-b01e-11ea-94a8-759b50d97664.png)
![2020-06-16-22-14-29](https://user-images.githubusercontent.com/37713672/84823530-c93dcf00-b01e-11ea-9280-2138240f863a.png)
![2020-06-16-22-17-35](https://user-images.githubusercontent.com/37713672/84823827-449f8080-b01f-11ea-9cf6-792be1738baa.png)

**Enviroment details**
OS: Arch Linux x86_64 
Kernel: 5.7.2-arch1-1
WM: i3-gaps
Compositor: picom vgit-e553e

```
Output of kitty --debug-config
kitty 0.17.4 created by Kovid Goyal
Linux t440s 5.7.2-arch1-1 #1 SMP PREEMPT Wed, 10 Jun 2020 20:36:24 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/caribou/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background                 Color(red=12, green=0, blue=1)
background_opacity         0.85
bell_on_tab                False
color0                     Color(red=12, green=0, blue=1)
color1                     Color(red=194, green=12, blue=55)
color10                    Color(red=186, green=22, blue=65)
color11                    Color(red=152, green=48, blue=70)
color12                    Color(red=168, green=55, blue=78)
color13                    Color(red=197, green=24, blue=69)
color14                    Color(red=198, green=48, blue=79)
color15                    Color(red=201, green=152, blue=162)
color2                     Color(red=186, green=22, blue=65)
color3                     Color(red=152, green=48, blue=70)
color4                     Color(red=168, green=55, blue=78)
color5                     Color(red=197, green=24, blue=69)
color6                     Color(red=198, green=48, blue=79)
color7                     Color(red=201, green=152, blue=162)
color8                     Color(red=140, green=106, blue=113)
color9                     Color(red=194, green=12, blue=55)
cursor                     Color(red=201, green=152, blue=162)
enable_audio_bell          False
font_family                Iosevka Hack
foreground                 Color(red=201, green=152, blue=162)
select_by_word_characters  :@-./_~?&=%+#
single_window_margin_width FloatEdges(left=-1000.0, top=-1000.0, right=-1000.0, bottom=-1000.0)
tab_separator               ÃÂÃÂ¢ÃÂÃÂÃÂÃÂ
update_check_interval      24.0
window_alert_on_bell       False
window_padding_width       FloatEdges(left=8.0, top=8.0, right=8.0, bottom=8.0)
```

**Additional context**
Reproducing the problem with `kitty --config NONE` returned the same issue. (glitch visible on the last screenshot)

**Comment by trygveaa** [comment] 2020-06-16 20:42
Seems like a duplicate of #2747, try compiling kitty from master.

**Closed** 2020-06-17 02:30 UTC
Labels: bug
