### ISSUE TITLE
Font not rendering in second monitor Mac OS

### ISSUE THREAD

**Issue by metaskopia** [kovidgoyal/kitty#2725] opened 2020-06-03 22:58 UTC
When I move the kitty window from my MacBook screen to an attached external screen the font disappears.

Below kitty terminal window in MacBook's screen:

<img width="1680" alt="Screen Shot 2020-06-03 at 16 57 38" src="https://user-images.githubusercontent.com/12637787/83696422-130bcb80-a5c2-11ea-83bc-65ca7eea1ca1.png">

And here is the same terminal window in the external screen:

![Screen Shot 2020-06-03 at 16 57 57 (2)](https://user-images.githubusercontent.com/12637787/83696530-4c443b80-a5c2-11ea-9467-c089a927af1d.png)

**Steps to reproduce the behavior**
1. Open a new terminal window on the main screen and write some text.
2. Move the terminal window to the screen of the attached external monitor.
3. See that font is not rendering.

Expected behavior: The font renders as expected.

**Enviroment details**
MacBook Pro
External monitor Dell
Mac OS v.10.14.6 (Mojave)
Kitty v.0.17.2 (installed via Homebrew)
Font: Anonymous Pro (free)

Kitty Conf
```
# This file is called from ~/.config/kitty/kitty.conf where the main config lives.
------

font_family      Anonymous Pro Regular
bold_font        Anonymous Pro Bold
italic_font      Anonymous Pro Italic
bold_italic_font Anonymous Pro Italic Bold

font_size 16
adjust_line_height -7
adjust_column_width -1

------

foreground      #d6deeb
background      #011627
cursor          #93a1a1
#: black
color0          #011627
color8          #637777
#: red
color1          #ff5874
color           #addb67
#: green
color2          #addb67
color10         #addb67
#: yellow
color3          #f78c6c
color11         #f78c6c
#: blue
color4          #82aaff
color12         #82aaff
#: magenta
color5          #c792ea
color13         #c792ea
#: cyan
color6          #7fdbca
color14         #7fdbca
#: white
color7          #aaaaaa
color15         #eeeeee

------

map super+j previous_window
map super+k next_window
map super+d move_window_backward
map super+f move_window_forward
map super+i move_window_to_top
map super+l next_layout
map super+o last_used_layout
```

**Comment by kovidgoyal** [comment] 2020-06-04 01:44
I cannot reproduce on my mac, though I dont have a macbook pro. If I had to guess this will likely be because the two monitors are running of different GPUs. Start kitty on your enternal monitor and it should work, for instance. Also run kitty in another terminal with --debug-rendering and see if anythingis printed to stderr.

**Comment by kovidgoyal** [comment] 2020-06-04 16:25
First off use the official kitty dmg which is at version 0.17.4 and see if you can reproduce with that, rather than using homebrew.

**Comment by metaskopia** [comment] 2020-06-04 16:51
Uninstalled kitty from Hombrew and installed the current dmg file but the problem persists. Now I'm not able to launch it from another terminal.

```
> kitty --version
zsh: command not found: kitty
```

**Comment by kovidgoyal** [comment] 2020-06-04 16:53
Yes, you need to use /Applications/kitty.app/Contents/MacOS/kitty

**Comment by kovidgoyal** [comment] 2020-06-04 16:55
I'm going to need some way to reproduce this, or some indication of what
the underlying issue is. Since --debug-rendering doesn't show any OpenGL
errors, I'm afraid I am at a loss. If you can find more information,
feel free to update this bug report, but closing it for now, as far as I
can tell it's something specific to your system.

**Closed by kovidgoyal** 2020-06-04 16:55 UTC
Labels: bug

**Comment by metaskopia** [comment] 2020-06-04 17:36
I did some test and maybe this info can be useful. Please take a look at it.

The main reason why this happens is because of the `adjust_line_height -7` option in my config file (I did this because Anonymous Pro has a higher line-height compared to other fonts). At first, I thought I could only be related to the Anonymous font I'm using but this also happens with the default font. The default font starts disappearing in the external monitor at -6 with and at -7 with Anonymous Pro. See below screenshots with the default font:

At `adjust_line_height -5` in MacBook's screen, the font renders tight.
<img width="519" alt="Screen Shot 2020-06-04 at 12 15 26" src="https://user-images.githubusercontent.com/12637787/83790528-f8873000-a65d-11ea-9317-4a95309802a0.png">

At `adjust_line_height -5` in the external monitor the font renders tighter.
![Screen Shot 2020-06-04 at 12 15 07](https://user-images.githubusercontent.com/12637787/83790526-f7560300-a65d-11ea-9aac-47c40b3f9b45.png)

At `adjust_line_height -6` in the external monitor, the font disappears but on the MacBook screen it is still visible.
![Screen Shot 2020-06-04 at 12 29 05](https://user-images.githubusercontent.com/12637787/83791197-02f5f980-a65f-11ea-8d55-6e75a6eac546.png)

Seems that each monitor is treating the font dimensions rendering in different ways and it is not a problem of the font.

Hope this helps.

**Comment by kovidgoyal** [comment] 2020-06-04 17:37
Well yes, different monitors have different DPI and so will require
different values in adjust_line_height. In any case setting it to
negative values is largely unsupported, as is noted in the docs for that
option, you can get various rendering artifacts with negative values.

**Comment by metaskopia** [comment] 2020-06-04 17:41
Fair enough. Thanks!
