### ISSUE TITLE
URLs are opened incorrectly when ending with a closing parenthesis 

### ISSUE THREAD

**Issue by sd-trailhead-james** [kovidgoyal/kitty#3688] opened 2021-06-03 16:44 UTC
**Describe the bug**
If a URL ends with a closing parenthesis (`)`), Kitty seems to drop the closing parenthesis when opening the URL

**To Reproduce**
1. Place a URL ending with a closing parenthesis (`)`) somewhere within Kitty
2. Attempt to open the URL in the registered browser/handler
3. Notice that the closing parenthesis (`)`) is left off of the URL when opened

Example URL: `https://www.google.com/search?q=(example)`

**Screenshots**
n/a

**Environment details**
OS: macOS 11.4 (Big Sur)

Output of kitty --debug-config:
```
kitty 0.20.3 created by Kovid Goyal
Darwin <REDACTED>.com 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.4 BuildVersion:	20F71
Loaded config files: ~/.config/kitty/kitty.conf

Config options different from defaults:
active_border_color                Color(red=150, green=152, blue=150)
active_tab_background              Color(red=29, green=31, blue=33)
active_tab_foreground              Color(red=197, green=200, blue=198)
allow_remote_control               y
background                         Color(red=29, green=31, blue=33)
color0                             Color(red=29, green=31, blue=33)
color1                             Color(red=204, green=102, blue=102)
color10                            Color(red=40, green=42, blue=46)
color11                            Color(red=55, green=59, blue=65)
color12                            Color(red=180, green=183, blue=180)
color13                            Color(red=224, green=224, blue=224)
color14                            Color(red=163, green=104, blue=90)
color2                             Color(red=181, green=189, blue=104)
color3                             Color(red=240, green=198, blue=116)
color4                             Color(red=129, green=162, blue=190)
color5                             Color(red=178, green=148, blue=187)
color6                             Color(red=138, green=190, blue=183)
color7                             Color(red=197, green=200, blue=198)
color8                             Color(red=150, green=152, blue=150)
color9                             Color(red=222, green=147, blue=95)
cursor                             Color(red=197, green=200, blue=198)
enable_audio_bell                  False
font_family                        mononoki
font_size                          16.0
foreground                         Color(red=197, green=200, blue=198)
inactive_border_color              Color(red=40, green=42, blue=46)
inactive_tab_background            Color(red=40, green=42, blue=46)
inactive_tab_foreground            Color(red=180, green=183, blue=180)
macos_custom_beam_cursor           True
macos_quit_when_last_window_closed True
scrollback_lines                   200000
selection_background               Color(red=197, green=200, blue=198)
selection_foreground               Color(red=29, green=31, blue=33)
tab_bar_background                 Color(red=40, green=42, blue=46)
url_color                          Color(red=180, green=183, blue=180)
Added shortcuts:
	 alt+b KeyAction(func='send_text', args=['all', b'\x1bb'])
	 alt+d KeyAction(func='send_text', args=['all', b'\x1bd'])
	 alt+f KeyAction(func='send_text', args=['all', b'\x1bf'])
	 alt+h KeyAction(func='send_text', args=['all', b'\x1bh'])
	 alt+j KeyAction(func='send_text', args=['all', b'\x1bj'])
	 alt+k KeyAction(func='send_text', args=['all', b'\x1bk'])
	 alt+l KeyAction(func='send_text', args=['all', b'\x1bl'])
	 cmd+. KeyAction(func='send_text', args=['all', b'\x03'])
```

**Additional context**
> Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

Confirmed that the behavior is identical with `kitty --config NONE`

**Comment by kovidgoyal** [comment] 2021-06-03 16:56
This is by design as URLs are often enclosed in parentheses, for example
in markdown like markup languages, therefore closing )}> and other
punctuation is ignored.

One could conceivably make the URL detection look for a matching start
parenthesis, but this is rather too much effort, for me, patches
welcome. Relevant code is in line.c line_url_end_at 

Note that you can use the hints kitten
https://sw.kovidgoyal.net/kitty/kittens/hints.html to do much more
sophisticated url matching.

**Comment by sd-trailhead-james** [comment] 2021-06-03 17:00
That makes sense, thank you @kovidgoyal!

**Closed** 2021-06-04 12:44 UTC
Labels: bug

**Comment by kovidgoyal** [comment] 2021-06-17 00:36
IIRC > is perfectly valid in a URL. So you definitely can't exclude it
in general. You have two ways to proceed:

1) Use the hints kitten, this allows arbitrarily powerful customization
for matching

2) Add a config option with a list of characters to be excluded from URLs
that would serve as an additional filter applied after is_url_char()

On Wed, Jun 16, 2021 at 01:46:00PM -0700, Radu Butoi wrote:
> Some of the URLs in my terminal are of the form `<...noturl... http://url.com>`, so this URL sentinel handling wouldn't match it. I currently work around this with a [hacky patch](https://github.com/kovidgoyal/kitty/files/6665764/0001-don-t-let-be-in-a-URL.patch.txt) which just excludes `'>'` from the URL characters. Any other thoughts on how to fix this? Perhaps the list of URL characters could be configurable? I could prepare a PR for making it a config option if that's a good idea.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/3688#issuecomment-862711148

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by rbutoi** [comment] 2021-06-17 01:55
Thanks for the suggestions - replies inline.

On Wed, 16 Jun 2021 at 17:36, Kovid Goyal ***@***.***> wrote:
> IIRC > is perfectly valid in a URL. So you definitely can't exclude it
> in general. You have two ways to proceed:
>
> 1) Use the hints kitten, this allows arbitrarily powerful customization
> for matching

I prefer the passive linkfication compared with the hints kitten, although it is much more powerful.

>
> 2) Add a config option with a list of characters to be excluded from URLs
> that would serve as an additional filter applied after is_url_char()

I'm leaning towards this since as you say it can't be done in general - do you have any examples of how to add a new config option? Grepping around for some common options, I see multiple references in C++ and python, and there's this recent refactor (https://github.com/kovidgoyal/kitty/commit/6d7df1c5e8515e64e700a17f3deacfcb00eca43f) I don't quite get.

**Comment by kovidgoyal** [comment] 2021-06-17 01:58
Add the option in options/definition.py and code to parse it in options/utils.py and code to convert it from python to c in to-c.h, then run ./gen-config.py. See select_by_word_characters as an example.
