### ISSUE TITLE
Request: Improve squiggly underline rendering

### ISSUE THREAD

**Issue by jordwalke** [kovidgoyal/kitty#853] opened 2018-09-02 23:07 UTC
I think it would be great if Kitty made the wavy underline rendering a little smoother and maybe more prominent. Here's how MacVim/Mac render it on the right compared to Kitty on the left:

<img width="549" alt="screen shot 2018-09-02 at 4 06 01 pm" src="https://user-images.githubusercontent.com/977348/44961696-1beddb80-aeca-11e8-9d75-4d8406696251.png">

It looks less like a line and more like a wave, and less "aliased"

**Comment by kovidgoyal** [comment] 2018-09-03 01:41
This is not worth the effort to me -- but it should be any easy thing for someone else to implement. The relevant code is simply one function of ~ 25 lines: add_curl() in kitty/fonts/render.py

The problem in your case is likely that kitty simply needs to use more space for the underline rendering.You can test that by increasing font size, which should make the rendering look similar to that of MacVim. I assume MacVim is using some algorithm to modify the underline size/position metrics that come from the font at small font sizes, kitty could presumably do the same.

Feel free to ask if any details need clarification.

**Comment by kovidgoyal** [comment] 2018-09-03 01:43
![screenshot_20180903_071306](https://user-images.githubusercontent.com/1308621/44963522-d4f2fb00-af48-11e8-8ea7-eeb8e6a177b6.png)

Screenshot of kitty underline rendering at larger font sizes

**Comment by kovidgoyal** [comment] 2018-09-03 04:46
I took a quick look at improving that function for small font sizes and made a fix but you'd still need to improve the antialiasing logic in that function at small sizes for perfect rendering.

**Comment by jordwalke** [comment] 2018-09-04 07:38
Thanks. A small improvement will probably go a long ways.

**Comment by kristijanhusak** [comment] 2018-11-26 12:55
Are you sure this can't be any better? Here's a screenshot to compare:

![screenshot](https://i.imgur.com/j9gHy60.png)

On the left is gnome-terminal and on right is kitty. Gnome terminal font size is 10, kitty is 9.5. They look similar in size like this, but undercurl is much better in gnome-terminal.

**Comment by kovidgoyal** [comment] 2018-11-26 14:21
I dont get rendering remotely like that at that font size. Hard for me to fix something I cannot reproduce. But feel free to submit a patch. Relevant code is in the add_curl() function in fonts/render.py

That function is basically responsible for rendering the underline in a buffer the size of a single cell.

**Comment by kristijanhusak** [comment] 2018-11-26 23:52
Returning max thickness to 1 works for me:
```diff
diff --git a/kitty/fonts/render.py b/kitty/fonts/render.py
index d5e33a8b..bfb98ea2 100644
--- a/kitty/fonts/render.py
+++ b/kitty/fonts/render.py
@@ -116,7 +116,7 @@ def add_dline(buf, cell_width, position, thickness, cell_height):
 
 def add_curl(buf, cell_width, position, thickness, cell_height):
     xfactor = 2.0 * pi / cell_width
-    yfactor = max(thickness, 2)
+    yfactor = max(thickness, 1)
 
     def clamp_y(y):
         return max(0, min(int(y), cell_height - 1))
@@ -131,7 +131,7 @@ def add_curl(buf, cell_width, position, thickness, cell_height):
         )
 
     for x_exact in range(cell_width):
-        y_exact = yfactor * cos(x_exact * xfactor) + position
+        y_exact = yfactor * cos(x_exact * xfactor) + position + 1
         y = clamp_y(ceil(y_exact))
         x_before, x_after = map(clamp_x, (x_exact - 1, x_exact + 1))
         for x in {x_before, x_exact, x_after}:
```
I also increased y by 1 because undercurl overlaps text a bit, so this moves it down.

Here's before:
![before](https://i.imgur.com/MiIGpFN.png)
And after:
![after](https://i.imgur.com/YG9OaiA.png)

**Comment by kovidgoyal** [comment] 2018-11-27 01:32
position comes from the font, making arbitrary changes to it doesn't seem like a good idea. It might look better for some fonts and worse for others.

As for changing minimum thickness from 2 to 1, that seems reasonable, though I need to test it with a few more fonts/font sizes to see if it has bad effects in other cases.

**Comment by kovidgoyal** [comment] 2018-11-27 01:50
On second thoughts, there is a robust way to change position. I have committed it. Hwever, reducing minimum thickness to 1 gives me much worse rendering at small font sizes. The problem is that at thickness 1 the underline has to be rendered in basically a 2 pixel height which means the wave does not look well defined.

**Comment by kristijanhusak** [comment] 2018-11-27 08:01
Do you have idea how could i improve rendering without messing around with the source code?
Can this thickness maybe be configurable?I'm using Input Mono Condensed font (http://input.fontbureau.com), maybe that will help you reproduce the issue.

**Comment by kovidgoyal** [comment] 2018-11-27 10:10
you basically need to improve the antialiasing and drawing logic to prevent the central blank line in your case. As for reproducing it should be purely deterministic, so if you provide the cell_height, cell_width position and tihickness values for your font, it should be trivial to reproduce.

**Comment by kristijanhusak** [comment] 2018-11-27 10:33
These are the values:
```
cell_height - 24
cell_height - 7
position - 16
thickness - 1
```
Hope it helps.

**Comment by kovidgoyal** [comment] 2018-12-04 07:32
are you sure about those values? position should never be larger than cell_height. Have you interchanged some numbers?

**Closed** 2018-12-05 08:32 UTC

**Comment by kristijanhusak** [comment] 2018-12-05 09:39
I'm using `adjust_line_height 8`, so i assume that's why numbers are a bit different.
I tried the update, it's much better, thanks!
