### ISSUE TITLE
Infinite wayland recursion between compositor and text-input-v3

### ISSUE THREAD

**Issue by wengxt** [kovidgoyal/kitty#5360] opened 2022-08-08 14:56 UTC
**Describe the bug**
Trying to type something in kitty, but sees infinite message.
WAYLAND_DEBUG=1 kitty
Trying to type something with fcitx5

[3940771.262] zwp_text_input_v3@19.done(89081)
[3940771.265]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.268]  -> zwp_text_input_v3@19.commit()
[3940771.294] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.298] zwp_text_input_v3@19.done(89082)
[3940771.301]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.304]  -> zwp_text_input_v3@19.commit()
[3940771.330] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.334] zwp_text_input_v3@19.done(89083)
[3940771.337]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.341]  -> zwp_text_input_v3@19.commit()
[3940771.367] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.371] zwp_text_input_v3@19.done(89084)
[3940771.374]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.378]  -> zwp_text_input_v3@19.commit()
[3940771.405] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.409] zwp_text_input_v3@19.done(89085)
[3940771.412]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.415]  -> zwp_text_input_v3@19.commit()
[3940771.442] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.446] zwp_text_input_v3@19.done(89086)
[3940771.449]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.452]  -> zwp_text_input_v3@19.commit()
[3940771.479] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.483] zwp_text_input_v3@19.done(89087)
[3940771.486]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.489]  -> zwp_text_input_v3@19.commit()
[3940771.515] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.520] zwp_text_input_v3@19.done(89088)
[3940771.522]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.526]  -> zwp_text_input_v3@19.commit()
[3940771.552] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.556] zwp_text_input_v3@19.done(89089)
[3940771.559]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.562]  -> zwp_text_input_v3@19.commit()
[3940771.588] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.593] zwp_text_input_v3@19.done(89090)
[3940771.596]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.599]  -> zwp_text_input_v3@19.commit()
[3940771.626] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.630] zwp_text_input_v3@19.done(89091)
[3940771.634]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.637]  -> zwp_text_input_v3@19.commit()
[3940771.664] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.668] zwp_text_input_v3@19.done(89092)
[3940771.671]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.674]  -> zwp_text_input_v3@19.commit()
[3940771.701] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.705] zwp_text_input_v3@19.done(89093)
[3940771.708]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.711]  -> zwp_text_input_v3@19.commit()
[3940771.737] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.741] zwp_text_input_v3@19.done(89094)
[3940771.744]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.747]  -> zwp_text_input_v3@19.commit()
[3940771.774] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.778] zwp_text_input_v3@19.done(89095)
[3940771.781]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.784]  -> zwp_text_input_v3@19.commit()
[3940771.810] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.814] zwp_text_input_v3@19.done(89096)
[3940771.817]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.820]  -> zwp_text_input_v3@19.commit()
[3940771.846] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.850] zwp_text_input_v3@19.done(89097)
[3940771.853]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.856]  -> zwp_text_input_v3@19.commit()
[3940771.882] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.886] zwp_text_input_v3@19.done(89098)
[3940771.889]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.892]  -> zwp_text_input_v3@19.commit()
[3940771.918] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.922] zwp_text_input_v3@19.done(89099)
[3940771.925]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.928]  -> zwp_text_input_v3@19.commit()
[3940771.954] zwp_text_input_v3@19.preedit_string("ni", 0, 2)
[3940771.958] zwp_text_input_v3@19.done(89100)
[3940771.962]  -> zwp_text_input_v3@19.set_cursor_rectangle(181, 26, 14, 21)
[3940771.965]  -> zwp_text_input_v3@19.commit()
[3940771.991] zwp_text_input_v3@19.preedit_string("ni", 0, 2)

**To Reproduce**
1. kwin + fcitx5
2. try type something that will trigger preedit.
3. kitty sending infinite wayland events

To explain this better:
https://invent.kde.org/plasma/kwin/-/merge_requests/2508 -> always reply done for commit
If there's preedit already, existing preedit will be sent again before the done, otherwise a plain "done" means clear the preedit.
kitty received preedit, even if it's the same preedit, still send the cursor rect update and commit, which make compositor reply a done.

Thus it create a infinite loop between kitty and compositor.

Suggested fix: don't send cursor rect if the value doesn't change, or don't trigger any update if preedit itself does not change comparing to the last update.

**Comment by kovidgoyal** [comment] 2022-08-08 16:06
This looks like a bug in kwin to me. They need to revert https://invent.kde.org/plasma/kwin/-/merge_requests/2508
or explain where in the protocol definition it says what kwin is doing
is correct. There exists a protocol spec for a reason. "Do what Gtk3
expects" is not a sufficient justification for anything.

Glancing over the protocol spec, which is extremely unclear, I can see
no mention of whether a compositor should send a done when nothing has
changed. Or any mention that an application should not send a commit
when the cursor position has not changed. So somebody needs to clarify
the protocol. 

Since kwin made this change and broke things, it's up to it to justify
the change, not to expect every application to adapt to it. 

Let me suggest a fix for kwin instead. Dont send repeated pre-edit events
when nothing has changed. Simply increment the done serial counter but
dont send an actual done. Your merge request to kwin mentions that
mutter behaves like this, but it doesn't, since this behavior doesn't show up
under mutter.

And let me be clear, I am opening to changing kitty behavior to
workaround this kwin breakage, but only if actually needed by the spec
or for some other good reason.

**Comment by kovidgoyal** [comment] 2022-08-08 16:59
Also isnt this a duplicate of #5105? Which is already fixed and released.

**Closed by kovidgoyal** 2022-08-08 16:59 UTC
Labels: bug
