### ISSUE TITLE
Freeze after moving to another window

### ISSUE THREAD

**Issue by amnk** [kovidgoyal/kitty#1641] opened 2019-05-24 14:29 UTC
First of all, thank you for the awesome project!

I'm using [hammerspoon](https://www.hammerspoon.org/) for automating some of my flows on MacOS, and noticed an interesting issue: with recent 0.14 release Kitty started freezing once moved to another window. I mean I can move the window around, but after the first move I can no longer type.

If I can provide any additional info to help debug this - let me know.

**Comment by Luflosi** [comment] 2019-05-24 14:32
See if <kbd>⌘</kbd>+<kbd>n</kbd> temporarily fixes your issue. If so, I am also experiencing the same issue and will investigate and try to fix it when I have some time.

**Comment by amnk** [comment] 2019-05-24 14:35
@Luflosi yeah, I'm able spin additional windows, and even open preferences. But not able to use windows once they were moved :D 

Will wait for updates, thanks for a very quick response.

**Comment by kovidgoyal** [comment] 2019-05-24 14:35
Am not sure I understand, it freezes after you move a window around, butonly if you move it with hammerspoon?

**Comment by amnk** [comment] 2019-05-24 14:40
@kovidgoyal So I'm using Kitty with `hide_window_decorations yes`, and normally only move it with Hammerspoon. I've tried enabling decorations back and moving it with a mouse - no freezes :)

**Comment by kovidgoyal** [comment] 2019-05-24 14:43
Does it happen only if window decorations are hidden. i.e. if you move
the window with visible window decoration using hammerspoon does it
still happen?

**Comment by Luflosi** [comment] 2019-05-24 14:43
If you press <kbd>ctrl</kbd>+<kbd>d</kbd> or type `exit` in your shell, the window should close. Does the window still close when you do that while the window appears frozen?

**Comment by amnk** [comment] 2019-05-24 14:55
@kovidgoyal it freezes when moved by Hammerspoon anyway.

@Luflosi yes, if I type `exit` - it closes. Although I don't see what I type - the cursor does not move.

**Comment by Luflosi** [comment] 2019-05-24 15:06
Can you clone the git repository, then `git revert f3974671f6a1eaf91d2b00b34f481d49b295002d` and build from source: https://sw.kovidgoyal.net/kitty/build.html please?

**Comment by RichardWLaub** [comment] 2019-05-24 17:31
I am seeing the same behavior when moving my kitty window with chunkwm.

**Comment by tammersaleh** [comment] 2019-05-25 00:14
Same behavior here when moving the window with sizeup.  In my situation it only happens when I move it to the larger of my two external monitors.  I open a new window, type some stuff, move it to my smaller external monitor, type some more stuff, move it to the larger external monitor, and it freezes.

**Comment by tammersaleh** [comment] 2019-05-25 02:40
I _believe_ that setting `sync_to_monitor no` fixed this for me.  I'll test further and comment here if not.

**Comment by kovidgoyal** [comment] 2019-05-25 02:46
And does it happen only when moving with sizeup not with the mouse?

**Comment by kovidgoyal** [comment] 2019-05-25 03:05
I installed hammerspoon and used the default example for window
movement:

```lua
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "H", function()
  local win = hs.window.focusedWindow()
  local f = win:frame()

  f.x = f.x - 10
  win:setFrame(f)
end)
```

focusing the kitty window and then pressing the key to move it 10 pixels
to the left, does not cause it to freeze for me. So I need something to
reproduce the issue with, short of installing a whole new window
manager.

**Comment by tammersaleh** [comment] 2019-05-25 14:39
> And does it happen only when moving with sizeup not with the mouse?

That's correct.

I've also verified that turning `sync_to_monitor no` definitely fixes this for me.

> focusing the kitty window and then pressing the key to move it 10 pixels
to the left, does not cause it to freeze for me. 

For me, this doesn't trigger when just moving the window - I have to move the window to another monitor.  In particular, I have to move the window to my larger monitor, highlighted below:
 
<img width="676" alt="MacBook Pro 2019-05-25 07-37-52" src="https://user-images.githubusercontent.com/2016/58370842-14d78500-7ec0-11e9-9018-22c4121faf60.png">

**Comment by kovidgoyal** [comment] 2019-05-26 01:24
Can the other people experiencing this bug please confirm that it is moving to another monitor that triggers it?

**Comment by MindTooth** [comment] 2019-05-26 11:01
I don't have moving to another monitor as a trigger.

It occurs when the laptop is locked, I log back in, and then switch to kitty.  kitty is set as a fullscreen application.  Only solution is to press `CMD + n`.  I've not noticed, nor payed to much attention if this happens when I'm logged in.  But I bet I would if it indeed occurred.

**Comment by Luflosi** [comment] 2019-05-26 13:25
Can anyone experiencing the issue try what I suggested in https://github.com/kovidgoyal/kitty/issues/1641#issuecomment-495669587, please? I have a feeling that this issue is somehow caused by f3974671f6a1eaf91d2b00b34f481d49b295002d but I can't reliably reproduce the issue.

**Comment by tammersaleh** [comment] 2019-05-26 15:46
> Can anyone experiencing the issue try what I suggested in #1641 (comment), please? I have a feeling that this issue is somehow caused by f397467 but I can't reliably reproduce the issue.

I followed those instructions and the issue persists (again, only if I set `sync_to_monitor yes`)

**Comment by Luflosi** [comment] 2019-05-26 17:10
Ok, thank you. That means, that my theory is almost certainly not correct.

**Comment by MindTooth** [comment] 2019-05-26 17:48
I've installed a reverted (the command above) version, but too soon to say.  However, the bug did not occur just now when I logged back in after an hour away.  I'll report back after some more logout/logins.

**Comment by kovidgoyal** [comment] 2019-05-27 01:11
I am guessing this has something to do with CVDisplayLink (the mechanism
used to implement sync_to_monitor).

**Comment by MindTooth** [comment] 2019-05-27 09:42
Running the commit reverted did not solve anything.  I've not touched the `sync_to_monitor` option.  My [config](https://github.com/MindTooth/dots/blob/master/config/kitty/kitty.conf).

**Comment by kovidgoyal** [comment] 2019-05-28 12:25
Note that I have not actually tested the fix since I cant reproduce the issue, so I would appreciate it if some of you could test it.

**Closed** 2019-05-28 12:24 UTC

**Comment by RichardWLaub** [comment] 2019-05-28 16:17
I just tested the fix and it worked for me. Thank you!

**Comment by gibfahn** [comment] 2019-05-29 17:47
Thanks for the quick fix! This fixes the issue for me too.

PR to update brew here: https://github.com/Homebrew/homebrew-cask/pull/64090

**Comment by MindTooth** [comment] 2019-05-30 13:38
Sad to say I still had a lock up.  Too soon to say why, but I'll be sure to reporting back.

**Comment by dylan-chong** [comment] 2019-07-14 07:50
Has anyone else had any issues with 0.14.2? The freezing still happens for me every now and again

**Comment by kovidgoyal** [comment] 2019-07-14 07:55
#1779
