### ISSUE TITLE
When moving mouse over inactive Kitty windows, text is selected as if the mouse button is pressed

### ISSUE THREAD

**Issue by juztin** [kovidgoyal/kitty#7381] opened 2024-04-23 16:57 UTC
While having multiple Kitty sessions/windows open _(some with single sessions, some with multiple tabs—doesn't seem to matter)_ when moving the mouse across the screen, over inactive Kitty windows, it begins to select all text in relation to the mouse _(as if I've pressed the mouse button down)_. The window remains inactive, but text is selected. I have to click/activate the windows to stop it _(depending on where/how the mouse is moving, it will sometimes scroll select until the mouse is moved completely out, or the window is activated and clicked to unselect.

1. Open multiple Kitty windows
2. Open multiple tabs within the Kitty window(s) _(sometimes this triggers it, sometimes not)_
3. Perform an `ls`, or anything that display text within the sessions
4. Move mouse over all Kitty windows, some will randomly begin selecting text within the session as the mouse is moved over the inactive window

**Screenshots**

**Environment details**
```
kitty 0.33.1 created by Kovid Goyal
Linux x 6.8.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 x86_64
EndeavourOS Linux 6.8.7-arch1-1 (/dev/tty)

DISTRIB_ID="EndeavourOS"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="EndeavourOS Linux"
DISTRIB_CODENAME="rolling"
Running under: Wayland
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /usr/bin/zsh
Loaded config files:
  /home/x/.config/kitty/kitty.conf

Config options different from defaults:
Changed shortcuts:
	kitty_mod+t →  launch --cwd=current --type=tab
Colors:
	background           #001e26   
	color0               #002731   
	color1               #d01b24   
	color10              #465a61   
	color11              #52676f   
	color12              #708183   
	color13              #5856b9   
	color14              #81908f   
	color15              #fcf4dc   
	color2               #728905   
	color3               #a57705   
	color4               #2075c7   
	color5               #c61b6e   
	color6               #259185   
	color7               #e9e2cb   
	color8               #465a61   
	color9               #bd3612   
	cursor               #708183   
	foreground           #708183   
	selection_background #9aeaca   
	selection_foreground #001e26   

Important environment variables seen by the kitty process:
	PATH                                /home/x/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
	LANG                                en_US.UTF-8
	EDITOR                              nano
	SHELL                               /usr/bin/zsh
	DISPLAY                             :1
	WAYLAND_DISPLAY                     wayland-0
	USER                                x
	LC_ADDRESS                          en_US.UTF-8
	LC_IDENTIFICATION                   en_US.UTF-8
	LC_MEASUREMENT                      en_US.UTF-8
	LC_MONETARY                         en_US.UTF-8
	LC_NAME                             en_US.UTF-8
	LC_NUMERIC                          en_US.UTF-8
	LC_PAPER                            en_US.UTF-8
	LC_TELEPHONE                        en_US.UTF-8
	LC_TIME                             en_US.UTF-8
	XDG_CONFIG_DIRS                     /home/x/.config/kdedefaults:/etc/xdg
	XDG_CURRENT_DESKTOP                 KDE
	XDG_MENU_PREFIX                     plasma-
	XDG_RUNTIME_DIR                     /run/user/2222
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SESSION_TYPE                    wayland
	XDG_VTNR                            1
d
```

**Comment by drammelt** [comment] 2024-07-07 20:32
This happens still in kitty 0.35.2

Only happens in wayland sessions. I can reproduce consistently...

Open kitty with 3 internal windows.
Open Firefox on second monitor.
Select text in firefox.
Click on bottom right window in kitty.
Click on top window in kitty.
Move mouse to bottom right window, text will be selected in bottom right window with no mouse click.

**Comment by kovidgoyal** [comment] 2024-07-07 23:55
Still doesnt repro for me with those steps. And wayland is meaningless, what actual compositor.

**Comment by drammelt** [comment] 2024-07-08 01:37
Sorry here is the debug info
```
kitty 0.35.2 created by Kovid Goyal
Linux x 6.6.37-cachy-x86-64-v3 #2 SMP PREEMPT_DYNAMIC x x86_64

This is x (Linux x86_64 6.6.37-cachy-x86-64-v3) 13:3
[input.txt](https://github.com/user-attachments/files/16121771/input.txt)
0:54

DISTRIB_ID="Gentoo"
Running under: Wayland (kwin 6.1.2) missing: single_pixel_buffer
OpenGL: '3.1.0 NVIDIA 555.58.02' Detected version: 3.1
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib64/kitty
  extensions dir: /usr/lib64/kitty/kitty
  system shell: /bin/zsh
Loaded config files:
  /home/daniel/.config/kitty/kitty.conf

Config options different from defaults:
background_blur               1
background_opacity            0.96
bold_font                     MonoLisa Bold
bold_italic_font              MonoLisa Bold Italic
enable_audio_bell             False
font_family                   MonoLisa Regular
font_features:
{'MonoLisa-Regular': ('+zero', '+ss04', '+ss07', '+ss08', '+ss09'),
 'MonoLisa-RegularItalic': ('+zero', '+ss04', '+ss07', '+ss08', '+ss09')}
font_size                     14.0
initial_window_height         (45, 'cells')
initial_window_width          (140, 'cells')
italic_font                   MonoLisa Regular Italic
remember_window_size          False
scrollback_pager              ['less', '--RAW-CONTROL-CHARS', '+INPUT_LINE_NUMBER']
scrollback_pager_history_size 1073741824
tab_bar_style                 powerline
tab_powerline_style           slanted
```

**Comment by drammelt** [comment] 2024-07-08 01:43
[input.txt](https://github.com/user-attachments/files/16121775/input.txt)

This is the input log, first click is clicking in the top kitty window, after last click text selection is enabled in the last (bottom right window). Also closing kitty  internal windows does not clear selection. It looks like kitty thinks the left button is being held down.

**Comment by kovidgoyal** [comment] 2024-07-08 02:01
Doesnt repro for me in kde wayland. Your input log ends with
```
[22.122] Release mouse_button: 0 mods: none handled as drag end
[22.622] MouseEvent matched action: mouse_handle_click
[22.622] on_mouse_input: click button: left mods: none grabbed: 0 handled_in_kitty: 1
```

which shows that kitty thinks the button was released and the drag (aka selection) finished.

**Comment by drammelt** [comment] 2024-07-08 05:12
Do have any tips on how to start tracking down what is going on?

I tried various versions back to 0.21.0 and it reproduces consistently. The other user from (#7382) was using KDE 5.27.5 and 5.27.11 with wayland, I am using KDE 6.1.2 with wayland. There is almost zero likely hood we have wayland versions in common as debian is far out of date.

The issue only happens in Kitty, I have never experienced the issue with any other application or terminal (Konsole/Alacritty).

**Comment by kovidgoyal** [comment] 2024-07-08 05:22
All the mouse related code is in mouse.c and wayland code is in wl_init.c and wl_window.c. Start with mouse.c and some prints see whats going on.

**Comment by drammelt** [comment] 2024-07-08 09:21
Thanks, I think I found it. It is when the mouse comes back from the external focus. The click event in the window registers a click but never releases. Subsequent clicks register release but the original one has not.

It runs this code when mouse re-enters window
```
    switch((MouseSelectionType)code) {
        case MOUSE_SELECTION_NORMAL:
            screen_start_selection(screen, w->mouse_pos.cell_x, w->mouse_pos.cell_y, w->mouse_pos.in_left_half_of_cell, false, EXTEND_CELL);
            break;
```

But never runs the deselect code
```
        else if (action == GLFW_RELEASE && button == global_state.active_drag_button) {
            w = window_for_id(global_state.active_drag_in_window);
            if (w) {
                end_drag(w);
                printf("handled as drag end\n");
                dispatch_possible_click(w, button, modifiers);
                return;
            }
        }
```

**Comment by drammelt** [comment] 2024-07-08 09:23
[input2.txt](https://github.com/user-attachments/files/16125451/input2.txt)

This is the input log with debug output, I have added comments to clarify what I am doing. You can see the "handled as drag end" is missing when clicking back in the window. I am not well versed in C, but let me know if you need more and I can give it a go.

**Comment by kovidgoyal** [comment] 2024-07-08 15:10
I dont follow in your first comment you say no release event is
delivered leaving a persistent selection. In your input2.txt log you
have marked the release event as bogus. What's bogus about it? Are you
saying you didnt actually release the mouse? Or that the release event
didnt end the selection? Or something else?

And are you doing the following:

1) Start a drag in kitty to select
2) move mouse to firefox
3) release pressed button
4) selection continues to update in kitty

because I cannot replicate. Do you have some non-standard kwin settings?
focus follows mouse perhaps? Because that would cause it. If you release
the mouse after focus has switched to firefox then kitty wont get the
release event. This is a bug in kwin's focus follows mouse
implementation if so. Focus should not follow mouse when a drag is
active in the focused window.

**Comment by drammelt** [comment] 2024-07-08 19:23
> I dont follow in your first comment you say no release event is delivered leaving a persistent selection. In your input2.txt log you have marked the release event as bogus. What's bogus about it? Are you saying you didnt actually release the mouse? Or that the release event didnt end the selection? Or something else?
I don't see how that is unclear, check every other mouse release they call the function and run
`printf("handled as drag end\n");`
The mouse click that comes back into the window never calls this, it is an orphaned select.

Here maybe this helps?
```
+++++ SELECT START +++++on_mouse_input: press button: left mods: none grabbed: 0 handled_in_kitty: 1
...
Release mouse_button: 0 mods: none grabbed: 0
on_mouse_input: release button: left mods: none grabbed: 0 handled_in_kitty: 0
```
This code
```
mouse_selection(Window *w, int code, int button) {
...
    switch((MouseSelectionType)code) {
        case MOUSE_SELECTION_NORMAL:
            printf("+++++ SELECT START +++++");
            screen_start_selection(screen, w->mouse_pos.cell_x, w->mouse_pos.cell_y, w->mouse_pos.in_left_half_of_cell, false, EXTEND_CELL);
            break;
```

This code is never called....
```
mouse_selection(Window *w, int code, int button) {
...
   if (global_state.active_drag_in_window) {
        printf("+++++ SELECT END? +++++\n");
        if (button == -1) {  // drag move
...
        else if (action == GLFW_RELEASE && button == global_state.active_drag_button) {
            w = window_for_id(global_state.active_drag_in_window);
            if (w) {
                end_drag(w);
                printf("handled as drag end\n");
                dispatch_possible_click(w, button, modifiers);
                return;
```

I dont see how this can be unclear the message from
`                printf("handled as drag end\n");`
Is not in the logs, No other message from the mouse even function is in the logs, it never happened. Its a bogus message because kitty never handles the event. I am guessing that message comes from GLFW since the text is not in kitty source.

> 
> And are you doing the following:
1. Open kitty, Ctrl-Alt-Enter 3 times to get 3 windows
2. Click in bottom right  window in kitty, type ls or something to display some text so selection is obvious.
3. Move mouse to Firefox on second monitor, select some text. Release mouse
4. Move mouse back to bottom right kitty window.
5. Click mouse.
6. Move mouse to top kitty window.
7. Click mouse.
8. Move mouse back to bottom right kitty window.

> 
> because I cannot replicate. Do you have some non-standard kwin settings? focus follows mouse perhaps? Because that would cause it. If you release the mouse after focus has switched to firefox then kitty wont get the release event. This is a bug in kwin's focus follows mouse implementation if so. Focus should not follow mouse when a drag is active in the focused window.

No non standard settings, its actually a fresh install. This also happened for me on KDE 5.27.11 on Gentoo and I can repo it on Debian 12 as well using stock settings.

**Comment by kovidgoyal** [comment] 2024-07-09 02:15
On Mon, Jul 08, 2024 at 12:23:59PM -0700, drammelt wrote:
> > I dont follow in your first comment you say no release event is delivered leaving a persistent selection. In your input2.txt log you have marked the release event as bogus. What's bogus about it? Are you saying you didnt actually release the mouse? Or that the release event didnt end the selection? Or something else?
> I don't see how that is unclear, check every other mouse release they call the function and run
> `printf("handled as drag end\n");`
> The mouse click that comes back into the window never calls this, it is an orphaned select.

What is a mouse click that comes back into a window? What are you
actually clicking? There is no such thing as a click. There are press
and release events. A "click" is synthesized from a press followed by a
release. Which one are you talking of, press or release?

>
> Here maybe this helps?
> ```
> +++++ SELECT START +++++on_mouse_input: press button: left mods: none grabbed: 0 handled_in_kitty: 1
> ...
> Release mouse_button: 0 mods: none grabbed: 0
> on_mouse_input: release button: left mods: none grabbed: 0 handled_in_kitty: 0
> ```
> This code
> ```
> mouse_selection(Window *w, int code, int button) {
> ...
>     switch((MouseSelectionType)code) {
>         case MOUSE_SELECTION_NORMAL:
>             printf("+++++ SELECT START +++++");
>             screen_start_selection(screen, w->mouse_pos.cell_x, w->mouse_pos.cell_y, w->mouse_pos.in_left_half_of_cell, false, EXTEND_CELL);
>             break;
> ```
>
> This code is never called....
> ```
> mouse_selection(Window *w, int code, int button) {
> ...
>    if (global_state.active_drag_in_window) {
>         printf("+++++ SELECT END? +++++\n");
>         if (button == -1) {  // drag move
> ...
>         else if (action == GLFW_RELEASE && button == global_state.active_drag_button) {
>             w = window_for_id(global_state.active_drag_in_window);
>             if (w) {
>                 end_drag(w);
>                 printf("handled as drag end\n");
>                 dispatch_possible_click(w, button, modifiers);
>                 return;
> ```
>
> I dont see how this can be unclear the message from
> `                printf("handled as drag end\n");`
> Is not in the logs, No other message from the mouse even function is in the logs, it never happened. Its a bogus message because kitty never handles the event. I am guessing that message comes from GLFW since the text is not in kitty source.

What on earth. GLFW is embedded in kitty's source. As I said originally
look in wl_window.c and wl_init.c.

I *think* what you are trying to say is that the release event is not
trigerring an end of selection. The relevant control for that is line
792-3 in mouse.c. Put some prints in there to see which if fails. Is it
because of active_drag_button or active_drag_in_window. I would guess
its active_drag_in_window. This is set in a few places in mouse.c and
glfw.c put some prints in there and check when it is changed.

If I had to guess, I would say it's happening in glfw.c at line 522
where there is a workaround precisely for kwin. Comment that out and see
if it solves your issue.

>
> >
> > And are you doing the following:
> 1. Open kitty, Ctrl-Alt-Enter 3 times to get 3 windows

ctrl+alt+enter doesnt launch kitty or open new kitty OS windows. Do you
mean 3 kitty instances or 3 OS windows in one kitty instance? The
shortcut for opening a new kitty OS window is ctrl+shift+n and a new
kitty window inside an existing kitty OS Window is ctrl+shift+enter

> 2. Click in bottom right  window in kitty, type ls or something to display some text so selection is obvious.

Click means a single press and release or create a selection or what?

> 3. Move mouse to Firefox on second monitor, select some text. Release mouse

Move mouse to Firefox with the button held down or up? Is it neccessary
for Firefox to be on a second monitor or does it reproduce with just one
monitor?

> 4. Move mouse back to bottom right kitty window.
> 5. Click mouse.
> 6. Move mouse to top kitty window.
> 7. Click mouse.
> 8. Move mouse back to bottom right kitty window.

**Comment by drammelt** [comment] 2024-07-09 02:24
> If I had to guess, I would say it's happening in glfw.c at line 522
where there is a workaround precisely for kwin. Comment that out and see
if it solves your issue.

Fixed by removing that.

**Closed** 2024-07-09 02:33 UTC
Labels: bug

**Comment by oldlonecoder** [comment] 2024-09-29 17:54
I have discovered that Kitty does not conforms to the XTerm mouse tracking on particular 
CSI commands : "?1002" (#define SET_BTN_EVENT_MOUSE 1002), "?1003" (#define SET_ANY_EVENT_MOUSE 1003)
Once a mouse button is pressed, KITTY ignore every subsequent release of that "pressed" button until pressing any other button, then ignores the release event for the new button event as well.

I have tested a corret behaviour on Konsole; Gnome-terminal; XTrem;  UXTerm, etc...

**Comment by oldlonecoder** [comment] 2024-09-30 13:54
I don't know at which level GFLW/OpenGL is working with the terminal console. I am too lazy to read the code... But here this simple question : Is it reading input events at direct XWindow/Wayland before the ptty/terminal receives the mouse events, or is it that GFLW/OpenGL just gets/pull the mouse event from the terminal itself as of normal console programs ? 

Actually I experience two OpenGL/GLFW terminals that have the same misbehaviour : 
Kitty (and Alacritty - Oh Rust! You still think you beat C ?...).

What I can say is that I am actually playing with a personal project in C++ doing a TUI and I am exacly at the mouse tracking stuff. So setting the terminal to raw and mouse track events: 
"\x1b[?1000;1003;1006;1015h" actually gives me every mouse events.
So on Kitty/Alacritty, (as of the latest release of Kitty 0.36.3 [Archlinux]), the stdin poll triggers on ALL mouse button press/release, but still recieves in argument 0 for ex.: 0x20 (left mouse button pressed -no movement: '2') when it must have received 0x23 ( 3 = release / or no button pressed); the left-button-drag value would be 0x40 ( 4 = moved ), and then 0x43 or 0x23 on button release; Interesting enough is that to "be aware" that the button was released, you have to explicitely move the mouse - after - having released the button used to drag.

Thank you sir for reading me, and a big hug for the beautiful name your parents gave you - and you to your work (Kitty) we're all enjoying to use.
