### ISSUE TITLE
On macOS closing a window should not switch to another workspace

### ISSUE THREAD

**Issue by aequitas** [kovidgoyal/kitty#1379] opened 2019-02-13 20:51 UTC
The behaviour of Kitty when closing windows in workspaces is different from other applications on macOS.

When using workspaces on macOS. If a Kitty terminal window is open in one workspace. Closing the last Kitty window in another workspace should not shift focus to the window in the other workspace (and thereby switching to that workspace). But rather stay on the same workspace.

Also Kitty seems to focus on the previous window when closing a window, disregarding which workspace the window is in. So closing a window in a workspace which still has other Kitty windows open also causes a switch of workspace.

If you like I can make a video to clarify what I mean.

**Comment by Luflosi** [comment] 2019-02-14 00:08
I can reproduce this issue and I agree it should be fixed.
If I remove the two lines from `_glfwPlatformFocusWindow()` from `glfw/cocoa_window.m`, this issue disappears, so we should figure out where this function is called when it shouldn't be called.

**Comment by kovidgoyal** [comment] 2019-02-14 01:26
This is by design, since otherwise closing kitty windows does not focus other windows at all on macOS. See destroy_os_window() in glfw.c. If you want to fix this you would need to make that code workspace aware and restrict focusing switching to other windows on the same worksace.

**Comment by Luflosi** [comment] 2019-02-14 01:44
Hmm, you're right. I'll try to look into it when I have some time.

**Comment by kovidgoyal** [comment] 2019-02-14 03:14
You'd basically need to use private APIs, like here: https://chromium.googlesource.com/chromium/src/+/c2818d44191bc4342c2ae322f3e0cb218dd2ec66/chrome/browser/cocoa/nswindow_additions.mm

**Comment by aequitas** [comment] 2019-02-14 09:11
@kovidgoyal I figured the behavior is because of that. I think making the code workspace aware would be the best solution. @Luflosi is this something you want to pick up or should I have a go at it?

**Comment by Luflosi** [comment] 2019-02-14 11:01
@aequitas feel free to have a go at it, I'm quite busy atm.

**Comment by aequitas** [comment] 2019-02-14 20:54
After some experimenting I ended up with a working PoC to read workspaces: https://github.com/kovidgoyal/kitty/pull/1383

There is still some work to be done. The linkedlist stack for focus history might not be ideal for this use case so I'd have to see how to solve that. As now you might have to look deeper into the stack to find the next window (in the current workspace) to focus to.

I'll try to get it sorted out over the weekend.

**Closed** 2019-02-16 07:52 UTC

**Comment by aequitas** [comment] 2019-02-16 11:21
@kovidgoyal awesome, looks a lot better than what I was going for. 

I've been testing it out and in concept your changes work as expected, only this function seems to return 0 for all workspaces and 1 for the first workspace:  
https://github.com/kovidgoyal/kitty/blob/7fd4ec50c9ffeefac9d5271a5f490225eab60f21/kitty/cocoa_window.m#L376

Which makes it effectively not work (except for workspace 1).

I'll try to investigate why as this is a direct call to the private API so it should work.

**Comment by kovidgoyal** [comment] 2019-02-16 17:59
Sorry, I have no idea why that should happen, not really a mac expert.

**Comment by aequitas** [comment] 2019-02-16 18:47
No problem. I will investigate it further and open a PR if I find a solution or maybe it's just a fluke on my system. Thanks for implementing this.

**Comment by koekeishiya** [comment] 2019-02-19 13:29
@kovidgoyal @aequitas 

The `CGS***Workspace` APIs have all been deprecated at least since the release of macOS El Capitan.
The new versions are an abstraction under the name of `CGSSpace`. I have written code in *chunkwm* to identify the (potential multiple workspaces) a window is visible on, see: https://github.com/koekeishiya/chunkwm/blob/master/src/common/accessibility/display.mm#L642

You can safely get rid of the `macos_space` abstraction that I have for my purposes, and have it simply return an array of workspace ids. What you would be interested in there is the `SpaceId` value, however note that this is an ID internal to macOS and does not map 1-1 to the incrementing desktop ID visible in mission-control. This should not matter with regards to what you are trying to achieve here.

Do let me know if you require more information and I will try to help out.

**Comment by kovidgoyal** [comment] 2019-02-19 14:25
@koekeishiya Thanks I have changed the code to use CGSSpace.

@aequitas I have not tested my changes as I dont currently have access to my mac (beyond seeingthat theycompile) please do that.

**Comment by aequitas** [comment] 2019-02-19 14:30
@koekeishiya thanks for investigating. 

@kovidgoyal I can test this out later today when I'm on my mac.

**Comment by Luflosi** [comment] 2019-02-19 18:14
@kovidgoyal I don't think it works. Here is what I tried:
1. Open kitty
2. Open a second OS window (same workspace)
3. Close that window again
4. The first window doesn't get focus

I haven't looked at the code at all so I don't know what's going on.

**Comment by aequitas** [comment] 2019-02-19 19:24
@kovidgoyal I've tested current master. I think there is a error in the logic of: https://github.com/kovidgoyal/kitty/blob/master/kitty/glfw.c#L610

`i` starts as `-1` but this causes the entire loop to be skipped.

Also `window_in_same_cocoa_workspace` never seems to be called.

The logic to read space ID's for windows seems to work fine as I get back a different ID for a window in each workspace.

**Comment by koekeishiya** [comment] 2019-02-19 19:38
@kovidgoyal @aequitas 

I expect the `i = -1` to be a typo considering it is of type `size_t`, thus rendering the loop meaningless.
If you are testing this locally, make `i` start at `0` and I suspect it will all work fine.
