### ISSUE TITLE
key input issue - clean_sym vs composed_sym ?

### ISSUE THREAD

**Issue by bew** [kovidgoyal/kitty#1980] opened 2019-09-18 22:20 UTC
Hello,

I'm having an issue with the keybind `Alt+/` not doing anything in **terminal apps** (cat, zsh, nvim, ..)

I'm using the **french keyboard layout**, which has the slash and colon symbols on the same key (to get the slash I do `Shift+colon`).

The actual keys I have to press are `Alt Shift colon` (useful for the debug output below).

Here is the relevant debug output:
```
Press scancode: 0x40 clean_sym: Alt_L composed_sym: Alt_L mods: none glfw_key: 342 (LEFT ALT) xkb_key: 65513 (Alt_L)
on_key_input: glfw key: 342 native_code: 0xffe9 action: PRESS mods: 0x0 text: '' state: 0 sent key to child

Press scancode: 0x32 clean_sym: Shift_L composed_sym: Shift_L mods: alt glfw_key: 340 (LEFT SHIFT) xkb_key: 65505 (Shift_L)
on_key_input: glfw key: 340 native_code: 0xffe1 action: PRESS mods: 0x4 text: '' state: 0 sent key to child

Press scancode: 0x3c clean_sym: colon composed_sym: slash mods: alt+shift glfw_fallback_key: 46 (PERIOD) xkb_key: 46 (period)
on_key_input: glfw key: 46 native_code: 0x2e action: PRESS mods: 0x5 text: '' state: 0 sent key to child

Release scancode: 0x3c clean_sym: colon mods: alt+shift glfw_fallback_key: 46 (PERIOD) xkb_key: 46 (period)
on_key_input: glfw key: 46 native_code: 0x2e action: RELEASE mods: 0x5 text: '' state: 0 ignoring as keyboard mode does not allow release events

Release scancode: 0x32 clean_sym: Shift_L mods: alt+shift glfw_key: 340 (LEFT SHIFT) xkb_key: 65505 (Shift_L)
on_key_input: glfw key: 340 native_code: 0xffe1 action: RELEASE mods: 0x5 text: '' state: 0 ignoring as keyboard mode does not allow release events

Release scancode: 0x40 clean_sym: Alt_L mods: alt glfw_key: 342 (LEFT ALT) xkb_key: 65513 (Alt_L)
on_key_input: glfw key: 342 native_code: 0xffe9 action: RELEASE mods: 0x4 text: '' state: 0 ignoring as keyboard mode does not allow release events
```

The most interesting lines seems to be:
```
Press scancode: 0x3c clean_sym: colon composed_sym: slash mods: alt+shift glfw_fallback_key: 46 (PERIOD) xkb_key: 46 (period)
on_key_input: glfw key: 46 native_code: 0x2e action: PRESS mods: 0x5 text: '' state: 0 sent key to child
```
We can see `clean_sym: colon composed_sym: slash`, but I'm not sure what is actually sent for the `on_key_input` since the `text: ''` is empty..

Tested on version `0.14.4` and git version.
On Archlinux, with X11.

**Comment by bew** [comment] 2019-09-18 22:59
Same issue with another keybind: `Alt+#`

The numbersign (`#`) is on the same key as quotedbl (`"`) and the number `3`:
- quotedbl is the direct symbol
- `3` is obtained with shift
- numbersign is obtained with AltGr (a special key on french keyboard, Alt_R in practice)

The relevant debug log for the key press:
```
Press scancode: 0xc clean_sym: quotedbl composed_sym: numbersign active_unknown_mods: Mod5 consumed_unknown_mods: Mod5 mods: alt glfw_fallback_key: 51 (3) xkb_key: 51 (3)
on_key_input: glfw key: 51 native_code: 0x33 action: PRESS mods: 0x4 text: '' state: 0 sent key to child
```
We have: `clean_sym: quotedbl composed_sym: numbersign`.

Btw, I'm not sure what `active_unknown_mods: Mod5 consumed_unknown_mods: Mod5` is about, my mod5 is configured as `mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)` (from `xmodmap`), no idea what those 2 keys are.. But I don't think it's useful here.

----
It looks like the solution would be to use the `composed_sym` field of the press event, since it seems to be always valid when present.

**Comment by Luflosi** [comment] 2019-09-18 23:11
Can you try the code from #1979, which I just created a couple hours ago? That combined with my previous and already merged pull request #1928 should fix your issues.

**Comment by Luflosi** [comment] 2019-09-18 23:15
And don't map `Alt+/` but `alt+shift+:` if those are the keys that you have to press.

**Comment by bew** [comment] 2019-09-18 23:17
> And don't map `Alt+/` but `alt+shift+:` if those are the keys that you have to press.

It's not a kitty mapping, but a keybind I use in zsh, so I have to use the keys that the termina app will receive AFAIK

I will try your PR

**Comment by Luflosi** [comment] 2019-09-18 23:20
> a keybind I use in zsh

Oh, then my PR will most likely not do anything. Are you using macOS? If so see https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.macos_option_as_alt.

**Comment by bew** [comment] 2019-09-18 23:21
No, I'm using Archlinux

**Comment by Luflosi** [comment] 2019-09-18 23:26
Then I don't know why this isn't working, sorry.
Maybe @kovidgoyal knows why.

**Comment by kovidgoyal** [comment] 2019-09-19 00:40
That's likely because the key press is alt+shift+/ not alt+/

There is no alt+shift+/ key combination in traditional terminal keyboard protocols, so you get nothing. I suggest mapping alt+: instead of alt+/ in your shell config. Ar if you dont want to do that, use send_text in kitty.conf to map alt+shift+slash to \x1b\x2f which IIRC is alt+/

**Closed by kovidgoyal** 2019-09-19 00:40 UTC

**Comment by bew** [comment] 2019-09-19 00:56
I think there is a misunderstanding here @kovidgoyal 

> There is no alt+shift+/ key combination in traditional terminal keyboard protocols

I'm aware of that, but I'm not trying to map `alt+shift+/`, but `alt+/`. With the french keyboard layout it happens to require the `shift` key to type the slash, but I don't expect the terminal app to receive the shift key

The keybind in my zsh config is something like:
```zsh
bindkey '^[/' some_function1
bindkey '^[#' some_function2
```
(with `^[` replaced with an actual escape char)

==> Note that in `urxvt` these 2 keybinds (`alt+/` and `alt+#`) works correctly without any special configuration.

**Comment by bew** [comment] 2019-09-19 01:30
Ok, actually I'm having this issue with Alt + most french-related keys:

The french keyboard looks like this (image from wikipedia):
![azerty](https://user-images.githubusercontent.com/9730330/65203668-f5c2bb80-da8b-11e9-9446-582b5b71e19c.png)

As you can see, the key with `1` (**let's call it K1**) gives `&` when pressed directly, and `1` when pressed with shift.

Here is a comparaison between urxvt and kitty:

On each terminal, I press the key **K1** (the key with the 1 on it, see above) using some mods:
1. K1 only
2. Shift + K1
3. (Ctrl+V then) Alt + K1
4. (Ctrl+V then) Alt + Shift + K1

With a space between each step for clarity.

On urxvt terminal, I get `& 1 ^[& ^[1`

On kitty terminal, I get `& 1 ^[1 ^[!` (as if the keyboard was in qwerty layout when I press alt)

Do you see my point?

**Comment by kovidgoyal** [comment] 2019-09-19 01:33
Just add the send_text command I mentioned to kitty.conf and you will be
fine.

**Comment by bew** [comment] 2019-09-19 01:35
> Just add the send_text command I mentioned to kitty.conf and you will be fine.

That would be a workaround, but the core behavior is still wrong, don't you agree?

**Comment by kovidgoyal** [comment] 2019-09-19 02:00
Well, you are welcome to come up with a patch to fix it. I dont know of
a robust way to do so. One cannot both support binding a shortcut like
shift+alt+key and also support mapping shift+alt+key to alt+shifted_key
automatically. The toolkit reports only one of these. For US ASCII keys
kitty works around it by manually mapping well known shifted keys. For
arbitrary keyboard layouts that cant be done.

Well technically one can, but it requires changes to the
toolkit to report both key event types based on the current keyboard
layout. That is way too much work, at least for me.

**Comment by bew** [comment] 2019-09-19 02:59
After reading https://github.com/kovidgoyal/kitty/issues/606 and https://github.com/xkbcommon/libxkbcommon/issues/61 I think I start to understand the problem and the general logic behind the current kitty behavior regarding these "complex" keybinds :thinking: 

Now reading the code of the function `glfw_xkb_handle_key_event` in `glfw/xkb_glfw.c`, I currently don't understand the relationship between the xkb keysym and the final glfw key:

- Do the key events comes from xkb and converted somehow to glfw? (then why can't we use the resolved keysym using xkb?)
- Or do the key events comes from glfw directly? (then why are you manipulating xkb-related stuff?)

**Comment by kovidgoyal** [comment] 2019-09-19 03:18
On Wed, Sep 18, 2019 at 07:59:31PM -0700, Benoit de Chezelles wrote:
> 
> Now reading the code of the function `glfw_xkb_handle_key_event` in `glfw/xkb_glfw.c`, I currently don't understand the relationship between the xkb keysym and the final glfw key:
> 
> - Do the key events comes from xkb and converted somehow to glfw? (then why can't we use the resolved keysym using xkb?)

kitty is cross platform, which means key events need to be abstracted
somehow. So xkb keys are mapped to glfw keys, just as cocoa keys are
mapped to glfw keys.

The problem is not in the mapping, it is that the key combination
alt+shift+: represents two things, alt+shift+: and alt+/ glfw currently
reports only one thing to kitty. So kitty has no way of knowing which
one to use. It uses the former not the latter, as that is what glfw
sends. If it used the latter there would be now way to bind to
alt+shift+key. To fix this properly one would need to report both things
to kitty and re-write the kitty key handling code to make use of that
extra information. And also make the same changes in the glfw cocoa
backend.

**Comment by bew** [comment] 2019-09-22 08:19
> To fix this properly one would need to report both things
to kitty and re-write the kitty key handling code to make use of that
extra information.

That is something I'd love to have too, and I'm willing to try to implement this if it's ok with you.

---

I've been reading the input implementation in alacritty, they are not using glfw but a bunch of rust libraries that separates the GL drawing ([glutin](https://github.com/rust-windowing/glutin)) from the window creation/input handling ([winit](https://github.com/rust-windowing/winit)), which directly exposes the physical scancode, mods, and the virtual key code after OS keyboard layout application (so basically the data you described as the proper solution :tada:).

From what I understand, kitty embeds a version of glfw in the root of the repository (in `glfw/`) + a few glue/wrapper files used by kitty to interact with glfw (`xkb_glfw.{c,h}`, `dbus_glfw.{c,h}`, `ibus_glfw.{c,h}`), right?

> glfw currently reports only one thing to kitty. So kitty has no way of knowing which one to use. It uses the former not the latter, **as that is what glfw sends**.

Does that mean that glfw actually does not send both? / there is not way to get both?
OR that the wrapper you did around glfw's X input handling currently only reports this?

---

Also, should I open a new issue for this? I guess so? (to put discussion and implementation questions there)

**Comment by kovidgoyal** [comment] 2019-09-22 08:43
On Sun, Sep 22, 2019 at 01:19:14AM -0700, Benoit de Chezelles wrote:
> > To fix this properly one would need to report both things
> to kitty and re-write the kitty key handling code to make use of that
> extra information.
> 
> That is something I'd love to have too, and I'm willing to try to implement this if it's ok with you.

Sure, feel free.

> 
> ---
> 
> I've been reading the input implementation in alacritty, they are not using glfw but a bunch of rust libraries that separates the GL drawing ([glutin](https://github.com/rust-windowing/glutin)) from the window creation/input handling ([winit](https://github.com/rust-windowing/winit)), which directly exposes the physical scancode, mods, and the virtual key code after OS keyboard layout application (so basically the data you described as the proper solution :tada:).
> 
> From what I understand, kitty embeds a version of glfw in the root of the repository (in `glfw/`) + a few glue/wrapper files used by kitty to interact with glfw (`xkb_glfw.{c,h}`, `dbus_glfw.{c,h}`, `ibus_glfw.{c,h}`), right?
> 
> > glfw currently reports only one thing to kitty. So kitty has no way of knowing which one to use. It uses the former not the latter, **as that is what glfw sends**.
> 
> Does that mean that glfw actually does not send both? / there is not way to get both?
> OR that the wrapper you did around glfw's X input handling currently only reports this?

glfw does not send both. And kitty does not have a wrapper around glfw,
kitty has a fork of glfw, indeed the major reason for the forsk wsa
glfw's extremely inadequate key handling which I improved to dd support
or dead keys, live keyboard layout switching, etc. 

If you want to get started the wy to do it is to change the
glfwKeyboardCallback function to accept a struct instead of individual
parameters. Then in the future, it will be easier to add inormation to
the struct. 

The information we need is what is currently passed, and in addition the
effective key after consuming the shift modifier. Then the kitty key
handling code will need to be re-written to take this information into
account. Currently it hardcodes shifted key info for the US ascii layout
(look for shifted_keys in keys.py

And there is also the question of cocoa and what to do there, since I
dont recall if this information is even available there.

> 
> ---
> 
> Also, should I open a new issue for this? I guess so? (to put discussion and implementation questions there)

I dont really care, continue here or we can move the discussion to a new
issue/PR.

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by Luflosi** [comment] 2019-09-22 10:11
If you get this working for Linux I'll try to make it work for macOS.

**Comment by bew** [comment] 2019-09-22 12:55
What is the `state` param given to `_glfwInputKeyboard` (then the keyboard callback) ?

**Comment by kovidgoyal** [comment] 2019-09-22 13:02
It is used by the IME subsystem, for example for writing east asian
text. It is documented in glfw3.h

**Comment by bew** [comment] 2019-09-22 13:31
Indeed thanks
Note: The word `status` is missing in these docs (`glfw3.h` & `glfw-wrapper.h`):
```diff
- *  @param[in] Used for Input Method events. Zero for normal key events.
+ *  @param[in] status Used for Input Method events. Zero for normal key events.
```

For the struct, it seems that the public GLFW API never passes a non-opaque struct to the caller / callback / user..
So I figured I would make a struct in the internals of glfw, pass it as an opaque struct to the callback and add a few methods (one for each field?) to extract the data from the struct from the callback, and re-create a struct (mirroring the one in glfw) in kitty's codebase to easily pass all the information around, does that sound right to you?

fyi, the struct I'm going to go with looks like this for now (pretty much WIP):
```c
struct _GLFWkeyevent
{
  GLFWwindow *win;
  int scancode;
  int action;

  int key;
  int mods;

  int virtual_key; // default: -1
  int virtual_mods; // default: -1
  // or: os_key / resolved_key / ?
  // or: os_mods / resolved_mods / ?

  char text[64]; // default: empty

  int state; // FIXME: store it here ?
};
```

**Comment by kovidgoyal** [comment] 2019-09-22 14:11
On Sun, Sep 22, 2019 at 06:31:10AM -0700, Benoit de Chezelles wrote:
> For the struct, it seems that the public GLFW API never passes a non-opaque struct to the caller / callback / user..
> So I figured I would make a struct in the internals of glfw, pass it as an opaque struct to the callback and add a few methods (one for each field?) to extract the data from the struct from the callback, and re-create a struct (mirroring the one in glfw) in kitty's codebase to easily pass all the information around, does that sound right to you?

That sounds fine to me, although given the glfw is now just a part of
kitty, I dont particularly mind exposing a struct directly. However
wrapping it in a function interface is definitely preferable in general.

> 
> fyi, the struct I'm going to go with looks like this for now (pretty much WIP):
> ```c
> struct _GLFWkeyevent
> {
>   GLFWwindow *win;
>   int scancode;
>   int action;
> 
>   int key;
>   int mods;
> 
>   int virtual_key; // default: -1
>   int virtual_mods; // default: -1
>   // or: os_key / resolved_key / ?
>   // or: os_mods / resolved_mods / ?
> 
>   char text[64]; // default: empty
> 
>   int state; // FIXME: store it here ?
> };
> ```

I think for a first PR just create a struct that passes exactly the same
info as the existing callback gets. We will add/modify the struct later
as needed.

**Comment by bew** [comment] 2019-09-22 15:07
> I think for a first PR just create a struct that passes exactly the same
info as the existing callback gets. We will add/modify the struct later
as needed.

> given the glfw is now just a part of kitty, I dont particularly mind exposing a struct directly.

Ok I'll do that.

What is the reasoning behind `glfw3.h` vs `glfw-wrapper.h` ?
Do I duplicate the struct definition in the 2 ? Would it be possible (here or later) to include `glfw3.h` in the wrapper to avoid the duplications?

**Comment by kovidgoyal** [comment] 2019-09-22 15:17
On Sun, Sep 22, 2019 at 08:07:16AM -0700, Benoit de Chezelles wrote:
> Ok I'll do that.
> 
> What is the reasoning behind `glfw3.h` vs `glfw-wrapper.h` ?
> Do I duplicate the struct definition in the 2 ? Would it be possible (here or later) to include `glfw3.h` in the wrapper to avoid the duplications?

It's a legacy from when glfw and kitty were separate. And is used to
make glfw backend independent. You dont need to
duplicate it, it is auto-generated by running glfw/glfw.py

**Comment by bew** [comment] 2019-09-22 15:24
Nevermind, diffing the two gave me the reasoning.

I still think it would benefit to include `glfw3.h` in the wrapper, and simply add all the wrappers after it.

**Comment by bew** [comment] 2019-09-22 15:26
Oh ok, I don't touch it then (I'll add a line saying that this file is autogenerated though, to avoid thinking about this later)

**Comment by kovidgoyal** [comment] 2019-09-22 15:32
On Sun, Sep 22, 2019 at 08:24:12AM -0700, Benoit de Chezelles wrote:
> Nevermind, diffing the two gave me the reasoning.
> 
> I still think it would benefit to include `glfw3.h` in the wrapper, and simply add all the wrappers after it.

Why? Since the rest of the wrappers have to be generated anyway, what do
we gain?

**Comment by kovidgoyal** [comment] 2019-09-22 15:32
On Sun, Sep 22, 2019 at 08:26:27AM -0700, Benoit de Chezelles wrote:
> Oh ok, I don't touch it then (I'll add a line saying that this file is autogenerated though, to avoid thinking about this later)

Sure I should have done that.

**Comment by bew** [comment] 2019-09-22 15:48
> Since the rest of the wrappers have to be generated anyway, what do
we gain?

Sorry it wasn't clear.. Kitty's codebase always includes `glfw-wrapper.h` (but not `glfw3.h`), so If I add the new struct `GLFWkeyevent` to `glfw3.h`, I won't be able to reference its fields in Kitty's codebase directly

Now, either I change the python generator to keep the full definition of the struct (based on a special comment or something) or we include one into the other (and can strip the opaque type definitions from the generator), or I'm I missing something?

**Comment by bew** [comment] 2019-09-22 16:29
Actually, putting the new type among the rest of the opaque types generated it to the wrapper as well, so I guess it's fine.

**Comment by bew** [comment] 2019-09-24 15:54
So I got something working (extract the struct, change everywhere), still a few things to change I think, I'll open a PR soon!

Also, what is difference between the xkb states `state`, `clean_state` ?

---

I noticed a change between 0.14.4 & current master for the second example I gave, using `Alt-&` which should give `^[&` but was giving `^[1` (using the fallback keymap).
Since @Luflosi's https://github.com/kovidgoyal/kitty/commit/e619eb9c, the `&` ampersand has now a glfw key for it (GLFW_KEY_AMPERSAND), and the behavior is now the same as the `alt+shift+:` keybinding (but without the shift problem): nothing is output on the terminal
```
Press scancode: 0x40 clean_sym: Alt_L composed_sym: Alt_L mods: none glfw_key: 342 (LEFT ALT) xkb_key: 65513 (Alt_L)
on_key_input: glfw key: 342 native_code: 0xffe9 action: PRESS mods: 0x0 text: '' state: 0 sent key to child

Press scancode: 0xa clean_sym: ampersand composed_sym: ampersand mods: alt glfw_key: 38 (AMPERSAND) xkb_key: 38 (ampersand)
on_key_input: glfw key: 38 native_code: 0x26 action: PRESS mods: 0x4 text: '' state: 0 sent key to child
```
I think it's because there is nothing in `text`, because this line:
https://github.com/kovidgoyal/kitty/blob/fb1c318a09ede964300a7e6e5a71c4c7a18cdb06/glfw/xkb_glfw.c#L606
prevents getting the text when ctrl / super / alt is pressed (but then I don't know why it works when I do a simple keybind like `Alt+x`).

I tried to remove the condition, but now I get `&` when I press `Alt+&`, the alt (serialized as `^[`) is not sent... do you have any idea why?

_Hopefully all these issues will go away with my later work to add physical keys + 'resolved' keys detection...._

**Comment by kovidgoyal** [comment] 2019-09-25 00:31
On Tue, Sep 24, 2019 at 08:54:54AM -0700, Benoit de Chezelles wrote:
> So I got something working (extract the struct, change everywhere), still a few things to change I think, I'll open a PR soon!
> 
> Also, what is difference between the xkb states `state`, `clean_state` ?

One is the current state after processing all key events to date, the
other is the state when no key events have been processed. This allows
us to get the actual keyname based on the current layout without
modifiers changing it.
