### ISSUE TITLE
Support `--icon` to set application icon

### ISSUE THREAD

**Issue by blueyed** [kovidgoyal/kitty#2842] opened 2020-07-10 12:26 UTC
When converting my scripts from urxvt to kitty I'm missing the `-icon` option from it:

> -icon file
> Compile pixbuf: Use the specified image as application icon. This is used by
> many window managers, taskbars and pagers to represent the application
> window; resource iconFile.

This is useful to have e.g. a distinct icon when using urxvt/kitty to spawn the
editor for Firefox (via Tridactyl), where a separate icon (other than the one
for "normal" kitty instances) is nice to have.

(using Arch Linux, awesomeWM)

**Comment by Luflosi** [comment] 2020-07-10 12:29
Duplicate of #2424.

**Comment by kovidgoyal** [comment] 2020-07-10 12:30
Not something I care about as it's X11 specific, but patches are welcome.
Although in most advanced window managers you can simply assign an icon
based on WM_CLASS which you can set via the --class option.

On Fri, Jul 10, 2020 at 05:27:07AM -0700, Daniel Hahler wrote:
> When converting my scripts from urxvt to kitty I'm missing the `-icon` option from it:
> 
> > -icon file
> > Compile pixbuf: Use the specified image as application icon. This is used by
> > many window managers, taskbars and pagers to represent the application
> > window; resource iconFile.
> 
> This is useful to have e.g. a distinct icon when using urxvt/kitty to spawn the
> editor for Firefox (via Tridactyl), where a separate icon (other than the one
> for "normal" kitty instances) is nice to have.
> 
> (using Arch Linux, awesomeWM)
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/2842

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by blueyed** [comment] 2020-07-10 12:31
Thanks (and sorry for missing the other issue in the first place).
I agree that configuring through the window manager appears to make more sense then.

**Closed** 2020-07-10 12:31 UTC
Labels: enhancement
