### ISSUE TITLE
Add option to change font size with key+scroll wheel

### ISSUE THREAD

**Issue by aarobc** [kovidgoyal/kitty#3019] opened 2020-10-09 20:42 UTC
**Is your feature request related to a problem? Please describe.**
Many other applications (eg: chrome, firefox, jetbrains, vscode) use control+scroll to scale their UI, or have it as an option. Consistent behavior between applications is pleasant and reduces fatigue.

**Describe the solution you'd like**
To allow for maximum flexibility, the configuration could be enabled in the config like this:
```
map ctrl+scroll_up   change_font_size all +2.0
map ctrl+scroll_down change_font_size all -2.0
```

**Describe alternatives you've considered**
It might be possible to implement this with something like autokey, but it would be quite difficult.

**Comment by Luflosi** [comment] 2020-10-09 21:51
Duplicate of #1839.

**Closed** 2020-10-10 02:02 UTC
Labels: enhancement
