### ISSUE TITLE
Title bar buttons gone ?

### ISSUE THREAD

**Issue by baosann** [kovidgoyal/kitty#5064] opened 2022-05-07 09:59 UTC
**Describe the bug**
kitty has no button in title bar 

![Screenshot from 2022-05-07 16-39-15](https://user-images.githubusercontent.com/90030004/167249047-53f7be87-63c3-4612-a8b4-a523f51e746c.png)
Anw why does the title bar look so boring ? ( Looks like it was not using the system theme )
**Environment details**
```
Ubuntu 22.04
Gnome 42
Wayland
```

**Comment by kovidgoyal** [comment] 2022-05-07 15:17
Ask the morons that develop GNOME. Duplicate of #3284

**Closed by kovidgoyal** 2022-05-07 15:17 UTC
Labels: bug

**Comment by kovidgoyal** [comment] 2024-04-25 09:15
hey @SaekoYes instead of being a GNOME-esque moron why dont you click on the link to the duplicate issue in my post which explains in exhaustive detail.
