### ISSUE TITLE
kitty skip new line character ('\n') after resize

### ISSUE THREAD

**Issue by ui3o** [kovidgoyal/kitty#4837] opened 2022-03-15 20:38 UTC
**Describe the bug**
I have a program which refresh a cli menu after terminal resize. When the terminal going to have a **smaller** size and the menu will be refreshed the lines will be printed.
**BUG:** After make the terminal size bigger the line delimiter will be ignored by kitty and the last line will be joined to the previous line.

**To Reproduce**
**Run this nodejs program**:
```
// for test running  
setTimeout(() => { process.exit(); }, 15000);

process.stdout.on('resize', async () => {
  process.stdout.write('\x1b[3F');
  await test();
  process.exit();
});

const line = async (long = false) => {
  if (long) process.stdout.write('      ' + 'a'.repeat(process.stdout.columns - 6 - 2) + `\x1b[K`);
  if (!long) process.stdout.write('      ' + 'b'.repeat(6) + `\x1b[K`);
  process.stdout.write('\n');
}

const test = async () => {
  await line(true);
  await line();
  process.stdout.write(`\x1b[0J`);
}
test();
```

1. run the nodejs program above
2. **resize** the terminal a little bit **smaller**
3. after the program exit resize the terminal to a little bit bigger and see the joined lines

**Screenshots**
1. On top left there is a kitty terminal
2. On bottom left  here is an alacritty terminal
3. After the program exit, when the terminal was resized back the kitty terminal join the last line to the previous line. This cause the problem, because not possible to calculate how many lines was printed. If the second line is short this going the be one line!! _**The line delimiter always need to be line delimiter.**_

https://user-images.githubusercontent.com/43638725/158465455-605926ce-417f-4eec-9bc2-70f9fac7c0a0.mp4

**Environment details**
```nodejs
kitty 0.24.2 created by Kovid Goyal
Linux xyz-lp 5.13.19-2-MANJARO #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64
Manjaro Linux 5.13.19-2-MANJARO  (xyz-lp) (/dev/tty)


DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.4
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/zsh
```

**Additional context**
Possible to reproduce with `kitty --config NONE`.

**Comment by kovidgoyal** [comment] 2022-03-16 01:17
No. You need to output an explicit newline if you want there to be a
line break. Otherwise lines that are wrapped because of size are
combined. This is by design and is not going to change.

**Comment by ui3o** [comment] 2022-03-16 08:58
No. ```console.log();``` makes an explicit line break. But I modified the code to ```process.stdout.write('\n');``` and it is the same.

If you run the sample code, and do not resize the window you can see after program exit if you make the size bigger second line always stay on the second place which is good!

If test with the _reproduce_ description you can see the issue.

I made a new screenshot about the compare.

https://user-images.githubusercontent.com/43638725/158553494-94eedbec-98e2-4522-a52b-c692937532e0.mp4

**Comment by kovidgoyal** [comment] 2022-03-16 09:51
Now fixed.

**Closed by kovidgoyal** 2022-03-16 09:51 UTC
Labels: bug

**Comment by ui3o** [comment] 2022-03-16 09:55
Thank you for a quick fix! Are you going to make a new release?

**Comment by kovidgoyal** [comment] 2022-03-16 09:56
Not anytime soon, no. You can use the kitty nightly builds if you wish
in the meantime.

**Comment by ui3o** [comment] 2022-03-16 10:16
When you trigger nightly builds?

**Comment by kovidgoyal** [comment] 2022-03-17 04:06
https://github.com/kovidgoyal/kitty/releases/tag/nightly

**Comment by ui3o** [comment] 2022-03-22 08:26
I tested it, and now it is fixed! Thank for it!
