### ISSUE TITLE
macos retina (high DPI) display 

### ISSUE THREAD

**Issue by koekeishiya** [kovidgoyal/kitty#77] opened 2017-05-18 16:38 UTC
I noticed that there is support for retina (high DPI) displays, and it works great for the most part.

My issue is that the fontsize is so much smaller on my built-in retina display, compared to my external displays. I can manually bump the font-size up using defined keybinds, but it is kinda annoying to deal with this manually everytime i move Kitty between my displays.

I was wondering if it was possible to automatically use 2x the configured fontsize for retina displays, or somehow automatically scale it based on DPI, so that I don't have to deal with this manually.

Except for this minor annoyance, Kitty has become my favourite terminal application for mac thus far, thanks a lot for making it available!

**Comment by kovidgoyal** [comment] 2017-05-19 00:51
The font size in kitty is defined in pts, i.e. it should be resolution independent. The problem is that actual font rendering takes two parameters, the size and dpi. There is currently no support for multi-monitor setups/moving windows between monitors, etc. It should not be too hard to add, but it is not something I am very interested in, as I dont use multi-monitor setups. 

Basically, you would need to change get_logical_dpi() to get the DPI of the monitor that the kitty window is currently in instead of the primary monitor and also setup some callback so you are notified by glfw when the monitor resolution changes (I dont know if glfw supports this or not). In the callback, change the globally stored dpi and redraw the screen using a process similar to the dynamic font resize functionality that already exists, except this time change the dpi not the font size.

**Comment by cweagans** [comment] 2017-12-13 18:07
This would be an awesome feature to have. It looks like this might also address instances where Kitty is started, and then the monitor resolution changes. I've run into this before when plugging into a projector to present. If macOS is mirroring the displays, then the main display resolution will usually change and it messes up the font size in Kitty.

**Comment by kovidgoyal** [comment] 2017-12-14 15:36
I pushed a possible fix for this to the dpi branch, but again, I have no way to test it.

**Comment by thomasjachmann** [comment] 2017-12-20 10:47
@kovidgoyal Just tested it on a Retina MacbookPro (2016) running macOS Sierra (10.12.6).

When a new window opens on the internal (retina) screen, everything is fine. Moving the window back and forth between the internal and the external (non retina) screen looks perfect. The window has the expected size, the font size doesn't jump between big and small and the rows and columns of the terminal stay the same.

When a new window opens on the external screen, the font has twice the size, though. When moving the window to the retina monitor fixes that and from then on, it behaves as described above.

I just had it once that the font became bigger again when moving the window to the non-retina screen. This could be fixed by going to the retina screen and back again.

**Closed** 2017-12-20 17:25 UTC
Labels: enhancement, help wanted

**Comment by kovidgoyal** [comment] 2017-12-20 17:32
This https://github.com/kovidgoyal/kitty/commit/70a4720bf92473ce21e720ab3c591a5127843595 should fix the issue with the window being opened on the secondary monitor having incorrect font size.

**Comment by moxuz** [comment] 2018-12-19 00:42
@kovidgoyal I have noticed this same issue but when mirroring my display from my high DPI MBP to a lower resolution screen. If I open it while using the lower DPI screen (mirrored from my MBP) then unplug the screen and re-plug it in the resolution of Kitty is now tiny. I have to restart Kitty to get back to a normal resolution.

**Comment by kovidgoyal** [comment] 2018-12-19 00:50
I'm not a macos user, but as far as kitty is concerned, as long as the OS sends a DPI change event, kitty will automatically re-adjust font sizes. Presumably in your scenario no DPI change events are being sent. Sadly I dont have the hardware to debug that, so you will have to do so yourself.

**Comment by ValentinMATHIEU** [comment] 2019-01-14 11:41
I experienced a similar issue.

When I setup the font size as `font_size 12.0`:
- if i open a fresh kitty instance directly on the mac: OK
- if i open a fresh kitty instance directly on the external display: it's big

=> To temporally fix the big font i simply move the window from the ext display to the mac one and back to the external display

**Comment by franco** [comment] 2019-09-19 17:48
I'm experiencing the same problem as described by @ValentinMATHIEU
