### ISSUE TITLE
Unable to capture stdin on MacOS

### ISSUE THREAD

**Issue by rvolosatovs** [kovidgoyal/kitty#1603] opened 2019-05-09 09:13 UTC
On MacOS the application works perfectly when run from Launchpad or Spotlight, however if `kitty` is started from an open terminal emulator(tried `kitty`, `alacritty`, `iTerm` and built-in `Terminal.app`), the `kitty` window appears, but it can not capture stdin - all input is just printed out in the parent terminal emulator.
This behavior is very weird and I cannot replicate in on Linux - looks like something MacOS-specific. Any idea what could be causing this and how to fix this?
Note, that this does not happen with other apps, e.g. I am able to run `alacritty` from open `kitty` terminal just fine - it seems that `kitty` is unable to capture the `stdin` of the parent process.
I tried running `kitty` with no config, but it does not seem to help.

I'm on `0.13.3` installed via Nix

**Comment by Luflosi** [comment] 2019-05-09 09:16
Can you execute `type -a kitty` and tell us what the output is please?

**Comment by Luflosi** [comment] 2019-05-09 09:26
If the path to the kitty executable is `/Applications/kitty.app/Contents/Frameworks/kitty/kitty/launcher/kitty`, then I'm pretty sure that this was fixed in cab1ba4e501083f597847b9e5a910151e6ea8d61. But no stable release with that fix was  released yet. You'll have to wait for the next stable version, build kitty from source (which is pretty easy) or execute `/Applications/kitty.app/Contents/MacOS/kitty` instead.

**Comment by rvolosatovs** [comment] 2019-05-09 12:03
In my case, due to the nature of Nix package manager, `kitty` is a symlink, a chain of symlinks in fact.
The bug only occurs when kitty is called as a symlink.
The issue is easy to reproduce:
```sh
/etc/profiles/per-user/rvolosatovs/Applications/kitty.app/Contents/MacOS/kitty
```
works as expected, however
```sh
ln -s /etc/profiles/per-user/rvolosatovs/Applications/kitty.app/Contents/MacOS/kitty /tmp/test
/tmp/test
rm /tmp/test
```
starts a (unfocused) kitty window, which does not accept stdin

**Comment by Luflosi** [comment] 2019-05-09 13:09
In this case this is a duplicate of #1539 and you can't use kitty using the symlink to the binary. Symlinks to the app bundle (kitty.app) seem to work though but I doubt that this will help you much when using kitty from nix.

**Closed** 2019-05-09 20:58 UTC
