### ISSUE TITLE
kitty won't open on wayland

### ISSUE THREAD

**Issue by hangman1998** [kovidgoyal/kitty#5043] opened 2022-04-30 18:03 UTC
Distro: Ubuntu 22.04 on wayland.
system: nvidia optimus laptop.
installed kitty following the [install guide](https://sw.kovidgoyal.net/kitty/binary/) .
version: 
``` bash
~ ➜ kitty --version
kitty 0.25.0 created by Kovid Goyal
```
running kitty produces the following:
``` bash
~ ➜ kitty
[destroyed object]: error 7: failed to import supplied dmabufs: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a
[120 22:29:09.140935] [glfw error 65544]: Wayland: fatal display error: Protocol error
```
* having the same issue with kitty version 0.21 which is available through Ubuntu 22.04 repository (`sudo apt install kitty`)
* works perfectly fine on a X11 session.
* having the same issue with `alactritty 0.11.dev`
* `wezterm` and `foot` which are other wayland based terminals work just fine.

**Comment by kovidgoyal** [comment] 2022-05-01 01:40
You dont say what wayland compositor you are using. I am guessing its
mutter from GNOME 42 which is a buggy pile of crap. Duplicate of #4878

**Closed by kovidgoyal** 2022-05-01 01:40 UTC
Labels: bug
