### ISSUE TITLE
Abort when looking up a unicode symbol in the interactive searcher

### ISSUE THREAD

**Issue by lenormf** [kovidgoyal/kitty#2941] opened 2020-08-28 16:50 UTC
**Describe the bug**
When trying to lookup a "check" unicode character using <kbd>$mod</kbd>+<kbd>u</kbd>, the terminal is aborted.

**To Reproduce**
Steps to reproduce the behaviour:
1. <kbd>$mod</kbd>+<kbd>u</kbd>
2. type the letters `c` and `h`

The terminal freezes for a while, then gets aborted:

```
kitty: ../harfbuzz/src/hb-buffer.hh:150: void hb_buffer_t::allocate_var(unsigned int, unsigned int): Assertion `0 == (allocated_var_bits & bits)' failed.
```

Reproduced with `kitty --config NONE` on the master branch.

**Comment by kovidgoyal** [comment] 2020-08-28 16:56
Doesn't reproduce for me. Linux, X11, harfbuzz 2.7, freetype 2.10.2

**Comment by lenormf** [comment] 2020-08-28 18:02
I'm using Arch and have the same versions your report. I'm behind on updates, I'll upgrade all my system, reboot, and try again.

**Comment by lenormf** [comment] 2020-08-29 13:40
The issue is still reproducible, even after all my packages were upgraded. What can I do to help debug this?

**Comment by kovidgoyal** [comment] 2020-08-29 13:47
No clue, sorry. That abort is coming from inside the harfbuzz library. Which means its a font rendering issue. Try installing symbola and noto color emoji fonts. That might fix it, and run with --debug-font-fallback which will tell you what fonts are being used when the abort happens.

**Comment by trygveaa** [comment] 2020-08-29 14:12
I can also reproduce this issue in Arch. The issue seems to be with U+11093 'KAITHI LETTER CHA', kitty crashes when trying to render this. If you have a small window, the unicode input might not show it when typing `ch`, so you could try to type the full name instead.

The issue happens outside of kitty too though. If I try to visit a page in Chrome that contains that character, the tab crashes (and the whole of Chrome crashes if I paste it in the address bar). However, xterm and Firefox can render the character fine without any crash.

Additionally, if I try to visit https://www.compart.com/en/unicode/U+11093 in either Chrome or Firefox, X11 crashes.

**Comment by kovidgoyal** [comment] 2020-08-29 14:34
Works fine for me with 

kitty --debug-font-fallback python -c "input(chr(0x11093))"

Uses Noto Sans Kaithi for rendering, so install that font and you should
be fine. Closing as this is a bug in harfbuzz, not kitty. If you want it
fixed, run with --debug-font-fallback to see what font is being used for
it on your system and report it to harfbuzz.

**Closed by kovidgoyal** 2020-08-29 14:34 UTC
Labels: bug

**Comment by trygveaa** [comment] 2020-08-29 14:45
It's a regression in harfbuzz. It works fine with harfbuzz 2.7.0, but crashes with harfbuzz 2.7.1.

**Comment by trygveaa** [comment] 2020-08-29 14:51
2.7.2 was just released some hours ago, and the release notes says it's fixed: https://github.com/harfbuzz/harfbuzz/releases/tag/2.7.2:

> Fix a regression in the previous release that caused a crash with Kaithi.

**Comment by lenormf** [comment] 2020-08-29 15:40
Thank you both, I'll upgrade harfbuzz whenever possible!
