### ISSUE TITLE
Kitty not drawing window decorations correctly

### ISSUE THREAD

**Issue by ellisgeek** [kovidgoyal/kitty#1659] opened 2019-05-28 21:20 UTC
Just today I began having a strange issue with Kitty where the window border is not correctly drawn. No other applications are exhibiting this issue.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/556100/58511833-428f2900-8161-11e9-8ace-b330c0c6a570.gif)
![Screenshot from 2019-05-28 15-45-32](https://user-images.githubusercontent.com/556100/58511844-491da080-8161-11e9-8a30-8e31cd067cab.png)

```
 ~ $> kitty --debug-gl --debug-keyboard --debug-font-fallback
[148 15:41:14.288797] Preloaded font faces:
[148 15:41:14.288826] normal face: /usr/share/fonts/TTF/VeraMono.ttf:0
[148 15:41:14.288834] bold face: /usr/share/fonts/TTF/VeraMoBd.ttf:0
[148 15:41:14.288841] italic face: /usr/share/fonts/TTF/VeraMoIt.ttf:0
[148 15:41:14.288848] bi face: /usr/share/fonts/TTF/VeraMoBI.ttf:0
GL version string: '4.5 (Core Profile) Mesa 19.0.5' Detected version: 4.5
[148 15:41:14.612696] [PARSE ERROR] Unknown OSC code: 13
```
```
 ~ $> kitty --debug-config
kitty 0.14.0 created by Kovid Goyal
Linux VHPLCLIT002L 5.1.5-arch1-2-ARCH #1 SMP PREEMPT Mon May 27 03:37:39 UTC 2019 x86_64
Running under: Wayland
Antergos Linux \r (\l)
Loaded config files: /home/esaille/.config/kitty/kitty.conf

Config options different from defaults:
adjust_line_height 1
background_opacity 0.95
font_family        Fura Code NerdFont Regular
font_size          10.0
scrollback_lines   4294967295
tab_bar_style      separator
tab_separator       <powerline stuff>
```

```
 ~ $> echo $XDG_SESSION_TYPE
wayland
 ~ $> neofetch
              `.-/::/-``                   user@computer 
            .-/osssssssso/.                -------------------- 
           :osyysssssssyyys+-              OS: Antergos Linux x86_64 
        `.+yyyysssssssssyyyyy+.            Host: Vostro 5481 
       `/syyyyyssssssssssyyyyys-`          Kernel: 5.1.5-arch1-2-ARCH 
      `/yhyyyyysss++ssosyyyyhhy/`          Uptime: 1 hour, 50 mins 
     .ohhhyyyyso++/+oso+syy+shhhho.        Packages: 1803 (pacman), 3 (snap) 
    .shhhhysoo++//+sss+++yyy+shhhhs.       Shell: fish 3.0.2 
   -yhhhhs+++++++ossso+++yyys+ohhddy:      Resolution: 1920x1080, 1920x1080 
  -yddhhyo+++++osyyss++++yyyyooyhdddy-     DE: GNOME 3.32.2 
 .yddddhso++osyyyyys+++++yyhhsoshddddy`    Theme: vimix-dark-laptop-beryl [GTK2/3] 
`odddddhyosyhyyyyyy++++++yhhhyosddddddo    Icons: Vimix-White [GTK2/3] 
.dmdddddhhhhhhhyyyo+++++shhhhhohddddmmh.   Terminal: kitty 
ddmmdddddhhhhhhhso++++++yhhhhhhdddddmmdy   
dmmmdddddddhhhyso++++++shhhhhddddddmmmmh   CPU: Intel i7-8565U (8) @ 4.600GHz 
-dmmmdddddddhhyso++++oshhhhdddddddmmmmd-   GPU: Intel UHD Graphics 620 
.smmmmddddddddhhhhhhhhhdddddddddmmmms.     Memory: 5992MiB / 15853MiB 
   `+ydmmmdddddddddddddddddddmmmmdy/.
      `.:+ooyyddddddddddddyyso+:.`                                 
```

**Comment by Luflosi** [comment] 2019-05-28 21:24
Duplicate of #1645. Try the workaround in https://github.com/kovidgoyal/kitty/issues/1645#issuecomment-496221126.

**Comment by Luflosi** [comment] 2019-05-28 21:27
@kovidgoyal watch the gif closely. There is a weird behaviour where resizing the window can make it get bigger in unexpected directions. I also had this problem before.

**Comment by kovidgoyal** [comment] 2019-05-29 01:34
@Luflosi I dont see what you mean? Since we cant see the mouse in the gif, how do we know the window is getting bigger in unexpected directions?

**Comment by Luflosi** [comment] 2019-05-29 17:20
What I described was probably fixed by the fix for #1662 but I can't test it now because I managed to make my Arch installation unbootable, which was my only Linux system with Wayland.

**Comment by ellisgeek** [comment] 2019-05-30 14:41
Due to how screen recording is under wayland you cannot capture the mouse but @Luflosi is correct, The window does change dimensions in strange ways. Also thanks for pointing me towards that work around.

**Comment by Luflosi** [comment] 2019-06-04 09:44
What I described was not fixed by the fix for #1662. #1680 also describes the same issue.

**Comment by kovidgoyal** [comment] 2019-06-04 09:47
aI

**Comment by kovidgoyal** [comment] 2019-06-04 09:50
I have no idea what you are describing. And I can reproduce no funny resizing under weston, which also does not do server side window decorations. I'm afraid I am not interested in installing GNOME to try to reproduce whatever issue there is with it.

**Closed by kovidgoyal** 2019-06-04 09:50 UTC

**Comment by Luflosi** [comment] 2019-06-04 09:52
Then I'll try to fix it myself when I have some time.

**Comment by kovidgoyal** [comment] 2019-06-04 09:56
Sure, I am happy to receive a patch.

**Comment by kovidgoyal** [comment] 2019-06-04 14:10
Well, I had a brainwave as to the cause, and fixed it, I think, since I have no way to check the fix.

**Comment by Luflosi** [comment] 2019-06-04 15:25
Yeah, that fixed it 🎉 gj
