### ISSUE TITLE
Line selection breaks when line is longer than screen

### ISSUE THREAD

**Issue by cizra** [kovidgoyal/kitty#951] opened 2018-09-10 18:02 UTC
Suppose a program outputs a single line longer than fits on your screen. It gets wrapped:
![screenshot from 2018-09-10 20-59-02](https://user-images.githubusercontent.com/2131991/45315248-90fd8880-b53c-11e8-96d6-b1f2050f81fe.png)

Now you want to copy-paste the line somewhere else, so you triple-click on the line expecting it to end up in SELECTION. Instead, the next prompt (or sometimes the previous prompt) also gets grabbed:
![screenshot from 2018-09-10 20-59-07](https://user-images.githubusercontent.com/2131991/45315249-90fd8880-b53c-11e8-835b-78908b94ef1e.png)

**Comment by kovidgoyal** [comment] 2018-09-11 09:08
I cannot reproduce that, steps I tried:
1) Run: kitty python -c "print('a' * 500); input('bbbb ')"
2) Triple click anywhere on the "aaaa" part
3) The bbbb part is not selected

What version of kitty are you on? If you are on 0.12.1 then can you come up with some set of steps to reproduce?

**Comment by cizra** [comment] 2018-09-11 09:13
I added `export PS1='my prompt $ '` to .bashrc just to reduce complexity. Then

**Comment by cizra** [comment] 2018-09-11 11:17
How do I split Kitty into 2 windows, on command line?

**Comment by kovidgoyal** [comment] 2018-09-11 12:04
Use a session file, see https://sw.kovidgoyal.net/kitty/ (the section on sessions)

**Comment by kovidgoyal** [comment] 2018-09-11 12:19
Something like:

```
layout tall
launch bash
launch bash -c "echo your long line; bash"
```

**Comment by cizra** [comment] 2018-09-11 17:02
And how can I set the size of the terminal? The repro seems to depend on size as well. Or perhaps I could craft an output based on existing size...

**Comment by cizra** [comment] 2018-09-11 17:49
I can't figure out a way to reproduce this consistently — in a given lifetime of Kitty, it either happens or doesn't, consistently. It might need some in-place redrawing (like ctrl-r does) or specific window sizes or such.

Meanwhile, poking around with windows and session scripts, I discovered another bug #958 — 100% reproducible with the session script.

**Comment by kovidgoyal** [comment] 2018-09-19 14:15
If you can come up with a scenario to reproduce feel free to update this bug report. until then I am closing. Mouse selection is being refactored anyway in #949 #967

**Closed by kovidgoyal** 2018-09-19 14:15 UTC
