### ISSUE TITLE
Kitty displaying some ligatures incorrectly with Fira Code.

### ISSUE THREAD

**Issue by Fingel** [kovidgoyal/kitty#2775] opened 2020-06-18 23:13 UTC
Hi,

Super happy I found kitty, as it seems it is one of the only terminals to run on linux and support ligatures. I'm using Fira Code (which Kitty seems to have a nice history with) and I noticed the arrows and some other ligatures are not rendering properly. It seems that the first character in these long, line like ligatures is always separated. I've attached two screenshots to illustrate, one from iterm2 and the other kitty.

Iterm2:
<img width="213" alt="iterm2" src="https://user-images.githubusercontent.com/3046397/85080482-2308db00-b17e-11ea-8c03-73cbadea8e71.png">

Kitty:
<img width="213" alt="kitty" src="https://user-images.githubusercontent.com/3046397/85080487-29975280-b17e-11ea-81f9-e23bd30e1882.png">

It would be great to have these rendering properly!

**Comment by Luflosi** [comment] 2020-06-18 23:36
Duplicate of #2695. Read the Fira Code issue linked there. Fira Code v3 will display properly.

**Comment by Luflosi** [comment] 2020-06-18 23:42
Here is another issue with some more info: https://github.com/tonsky/FiraCode/issues/1081.

**Closed** 2020-06-19 03:18 UTC
