### ISSUE TITLE
Chinese input method bug?

### ISSUE THREAD

**Issue by amikai** [kovidgoyal/kitty#3964] opened 2021-08-21 13:43 UTC
**Describe the bug**
In traditional Chinese input method, type some word and press cmd + v (in fact cmd + any key). 
see the gif.
The expected behavior is copy from system clipboard.

**To Reproduce**
In my kitty config, i set this `map cmd+v paste_from_clipboard`, but using `kitty --config NONE` is also the same result.

1. Use traditional Chinese input method
2. Type some word
3. Press cmd + v

**Screenshots**
![CleanShot 2021-08-21 at 21 30 35](https://user-images.githubusercontent.com/13815956/130323490-fd01171f-9633-467e-9388-fd776bd8a3ab.gif)
**Environment details**

```
kitty 0.23.0 created by Kovid Goyal
Darwin amikai-macbook.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.1 BuildVersion:	20C69
Loaded config files:
  /Users/amikai_chuang/.config/kitty/kitty.conf

Config options different from defaults:
copy_on_select       clipboard
font_family          Hack Nerd Font
font_size            18.0
macos_option_as_alt  3
url_style            1
Added mouse actions:
	 ctrl+b1 -2 ungrabbed KeyAction('mouse_click_url_or_select')
Changed shortcuts:
	shift+ctrl+- KeyAction('change_font_size', (True, '-', 1.0))
	shift+ctrl+= KeyAction('change_font_size', (True, '+', 1.0))
Colors:
	background           #282828   
	color0               #282828   
	color1               #cc241d   
	color10              #b8bb26   
	color11              #fabd2d   
	color12              #83a598   
	color13              #d3869b   
	color14              #8ec07c   
	color15              #928374   
	color2               #98971a   
	color3               #d79921   
	color4               #458588   
	color5               #b16286   
	color6               #689d6a   
	color7               #a89984   
	color8               #928374   
	color9               #fb4934   
	cursor               #928374   
	cursor_text_color    #000000   
	foreground           #ebdbb2   
	selection_background #3c3836   
	selection_foreground #928374   
```
# Note
I found that clicking the link first and then pressing cmd works, but holding cmd while click the link won't work. i think this is a bug.

**Comment by kovidgoyal** [comment] 2021-08-21 16:50
This is by design. kitty uses an extended keyboard protocol
https://sw.kovidgoyal.net/kitty/keyboard-protocol/ which can represent
more keys than the traditional encoding, including cmd+key. In this case
cmd+v is being encoded and send as a CSI u escape code which is what
you are seeing. 

Is cmd+v part of your input method or are you pressing it to paste?
Assuming it is not part of your input method, the bug is that the input
method is sending the key as some key other than v which you can confirm
using kitty --debug-input. I dont think this can be fixed in kitty. You
can workaround it by using a mapping for whatever key the input method
is sending (which you can find via --debug-input) in kitty.cof to
trigger a paste.

See the section on key mapping in https://sw.kovidgoyal.net/kitty/conf/ 
for details.

**Closed by kovidgoyal** 2021-08-21 16:50 UTC
Labels: bug

**Comment by amikai** [comment] 2021-08-22 10:11
@koekeishiya I don't much about the csi escape code, can you give me some mapping example.
I can't found the example of mapping from csi code in document.

**Comment by kovidgoyal** [comment] 2021-08-22 10:15
you dont need to map to an escape code map it to paste_from_clipboard

**Comment by amikai** [comment] 2021-08-22 10:31
@kdarkhan I upload my `kitty --debug-input` output of `cmd + v`  few minutes, could give me some instuctions?

**Comment by amikai** [comment] 2021-08-22 11:57
I found that is my IME (Zhuyin) problem, but `cmd + v` is not part of IME.

![CleanShot 2021-08-22 at 19 49 37](https://user-images.githubusercontent.com/13815956/130354058-da8dc691-18ba-4444-9c19-31d46d5073af.gif)
