### ISSUE TITLE
Text display issue when creating new OS window

### ISSUE THREAD

**Issue by kris-anderson** [kovidgoyal/kitty#1788] opened 2019-07-09 02:20 UTC
I'm running into a display issue. When I open a new window everything is fine. If I create a new tab things appear fine as well. But as soon as I open a new window within Kitty my existing window compresses a bit and there appear to be blank lines that overlay on top of my text making the text appear cut-off. 

It's hard to explain, so a picture may help here:
![Screen Shot 2019-07-08 at 7 14 30 PM](https://user-images.githubusercontent.com/1562427/60854370-e3d3bb00-a1b4-11e9-9bac-0e8a36e6cecd.jpg)

Here's a video as well:
https://drive.google.com/file/d/1HXGZeHmKzD5N7qT8xGkm4JSoPj-XewGH/view?usp=sharing

You can also see in the video that when this happens, the mouse selection is off somehow. Even though I'm trying to select a specific line it's actually selecting the line above the one I'm attempting to select.

I've tried a few different fonts (and no font defined) but I get the same results. Any idea on if there's something I can try changing in my config?

`❯ kitty --debug-config
kitty 0.14.2 created by Kovid Goyal
Darwin kris.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
ProductName:    Mac OS X ProductVersion:        10.14.5 BuildVersion:   18F132
Loaded config files: /Users/kris/.config/kitty/kitty.conf

Config options different from defaults:
background           Color(red=250, green=250, blue=250)
bold_font            Hack Bold
bold_italic_font     Hack Bold Italic
color1               Color(red=242, green=89, blue=11)
color10              Color(red=163, green=217, blue=0)
color11              Color(red=231, green=196, blue=70)
color12              Color(red=104, green=113, blue=255)
color13              Color(red=163, green=122, blue=204)
color14              Color(red=86, green=217, blue=173)
color15              Color(red=254, green=255, blue=255)
color2               Color(red=118, green=204, blue=0)
color3               Color(red=242, green=151, blue=23)
color4               Color(red=65, green=165, blue=217)
color5               Color(red=153, green=101, blue=204)
color6               Color(red=77, green=191, blue=152)
color7               Color(red=92, green=103, blue=115)
color8               Color(red=207, green=207, blue=207)
color9               Color(red=214, green=100, blue=106)
cursor               Color(red=255, green=105, blue=0)
enable_audio_bell    False
font_family          Hack Regular
font_size            15.0
foreground           Color(red=78, green=87, blue=96)
italic_font          Hack Italic
selection_background Color(red=230, green=227, blue=210)`

**Comment by kris-anderson** [comment] 2019-07-09 03:35
The display issue seems to only happen on my Thunderbolt Display. I don't see this on my 2013 Retina Macbook Pro via the laptop's screen. I do still have scaling differences when a new OS window is opened though. Here's a video:

https://drive.google.com/file/d/1gHSOPOX04iDjFN_AUPJvslWQiUSCBDRV/view?usp=sharing

**Comment by kovidgoyal** [comment] 2019-07-09 04:48
Weird, I have no clue what the issue with the thunderbolt display is. If you are seeing different font sizes in different OS windows, it's likely because the OS is reporting different DPI values for them. You can confirm that by putting in some print statements in get_window_content_scale() in glfw.c

**Comment by markhellewell** [comment] 2019-07-10 01:12
I’m seeing this too on Ubuntu 18.04, but only since an apt upgrade on 2019-07-05 which updated the following packages:
`Upgrade: libdrm-nouveau2:amd64 (2.4.95-1~18.04.1, 2.4.97-1ubuntu1~18.04.1), libdrm-nouveau2:i386 (2.4.95-1~1
8.04.1, 2.4.97-1ubuntu1~18.04.1), libegl-mesa0:amd64 (18.2.8-0ubuntu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), l
ibsystemd0:amd64 (237-3ubuntu10.23, 237-3ubuntu10.24), libsystemd0:i386 (237-3ubuntu10.23, 237-3ubuntu10.24)
, libglapi-mesa:amd64 (18.2.8-0ubuntu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), libglapi-mesa:i386 (18.2.8-0ubun
tu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), libbz2-1.0:amd64 (1.0.6-8.1ubuntu0.1, 1.0.6-8.1ubuntu0.2), libxatra
cker2:amd64 (18.2.8-0ubuntu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), udev:amd64 (237-3ubuntu10.23, 237-3ubuntu1
0.24), libegl1-mesa:amd64 (18.2.8-0ubuntu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), libudev1:amd64 (237-3ubuntu1
0.23, 237-3ubuntu10.24), libudev1:i386 (237-3ubuntu10.23, 237-3ubuntu10.24), libgbm1:amd64 (18.2.8-0ubuntu0~
18.04.2, 19.0.2-1ubuntu1.1~18.04.1), libdrm-amdgpu1:amd64 (2.4.95-1~18.04.1, 2.4.97-1ubuntu1~18.04.1), libdr
m-amdgpu1:i386 (2.4.95-1~18.04.1, 2.4.97-1ubuntu1~18.04.1), libnss-myhostname:amd64 (237-3ubuntu10.23, 237-3
ubuntu10.24), systemd-sysv:amd64 (237-3ubuntu10.23, 237-3ubuntu10.24), libwayland-egl1-mesa:amd64 (18.2.8-0u
buntu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), libpam-systemd:amd64 (237-3ubuntu10.23, 237-3ubuntu10.24), libdr
m2:amd64 (2.4.95-1~18.04.1, 2.4.97-1ubuntu1~18.04.1), libdrm2:i386 (2.4.95-1~18.04.1, 2.4.97-1ubuntu1~18.04.
1), systemd:amd64 (237-3ubuntu10.23, 237-3ubuntu10.24), libgl1-mesa-dri:amd64 (18.2.8-0ubuntu0~18.04.2, 19.0
.2-1ubuntu1.1~18.04.1), libgl1-mesa-dri:i386 (18.2.8-0ubuntu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), libosmesa
6:amd64 (18.2.8-0ubuntu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), libosmesa6:i386 (18.2.8-0ubuntu0~18.04.2, 19.0
.2-1ubuntu1.1~18.04.1), libnss-systemd:amd64 (237-3ubuntu10.23, 237-3ubuntu10.24), bzip2:amd64 (1.0.6-8.1ubu
ntu0.1, 1.0.6-8.1ubuntu0.2), code:amd64 (1.35.1-1560350270, 1.36.0-1562161087), libgl1-mesa-glx:amd64 (18.2.
8-0ubuntu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), libgl1-mesa-glx:i386 (18.2.8-0ubuntu0~18.04.2, 19.0.2-1ubunt
u1.1~18.04.1), libdrm-intel1:amd64 (2.4.95-1~18.04.1, 2.4.97-1ubuntu1~18.04.1), libdrm-intel1:i386 (2.4.95-1
~18.04.1, 2.4.97-1ubuntu1~18.04.1), libdrm-radeon1:amd64 (2.4.95-1~18.04.1, 2.4.97-1ubuntu1~18.04.1), libdrm
-radeon1:i386 (2.4.95-1~18.04.1, 2.4.97-1ubuntu1~18.04.1), mesa-vdpau-drivers:amd64 (18.2.8-0ubuntu0~18.04.2
, 19.0.2-1ubuntu1.1~18.04.1), mesa-vdpau-drivers:i386 (18.2.8-0ubuntu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), 
linux-firmware:amd64 (1.173.6, 1.173.8), mesa-va-drivers:amd64 (18.2.8-0ubuntu0~18.04.2, 19.0.2-1ubuntu1.1~1
8.04.1), mesa-va-drivers:i386 (18.2.8-0ubuntu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), tzdata:amd64 (2019a-0ubuntu0.18.04, 2019b-0ubuntu0.18.04), libglx-mesa0:amd64 (18.2.8-0ubuntu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), libglx-mesa0:i386 (18.2.8-0ubuntu0~18.04.2, 19.0.2-1ubuntu1.1~18.04.1), libdrm-common:amd64 (2.4.95-1~18.04.1, 2.4.97-1ubuntu1~18.04.1)`

**Comment by kovidgoyal** [comment] 2019-07-10 02:52
@markhellewell that has nothig to do with this issue, see #1484

**Comment by kris-anderson** [comment] 2019-07-11 06:53
Just a note that I can also reproduce this on a different macbook pro (this one a 2016 15") on the laptop screen.

<img width="597" alt="Screen Shot 2019-07-10 at 10 51 16 PM" src="https://user-images.githubusercontent.com/1562427/61028593-e0cffa80-a36d-11e9-8efd-a37ac4da45fd.png">

**Comment by mmzeeman** [comment] 2019-07-17 07:53
Have the same problem on Ubuntu 18.

**Comment by kovidgoyal** [comment] 2019-07-20 08:04
Am closing this issue since I cannot reproduce and people seem to confusing it with the urelated broken mesa versions on Ubuntu issue.

Feel free to followup on the closed issue if there are new developments/information.

**Closed by kovidgoyal** 2019-07-20 08:04 UTC
